const { v4: uuidv4 } = require('uuid');
const Q = (l,s,t,o,a,src,yr) => ({question_id:uuidv4(),level:l,subject:s,question_text:t,options:o,correct_answer:a,source:src,year:yr,language:'english',created_at:new Date()});

module.exports = [
Q('junior','social','The "Mauryan Empire" was founded by-',['Ashoka','Chandragupta Maurya','Bindusara','Harsha'],'Chandragupta Maurya','CTET 2011',2011),
Q('junior','social','Who was the first Prime Minister of India?',['Mahatma Gandhi','Jawaharlal Nehru','Sardar Patel','Lal Bahadur Shastri'],'Jawaharlal Nehru','UPTET 2012',2012),
Q('junior','social','The "Rig Veda" consists of how many books (mandalas)?',['8','10','12','15'],'10','CTET 2013',2013),
Q('junior','social','The "Civil Disobedience Movement" started with-',['Dandi March','Quit India','Khilafat','None'],'Dandi March','UPTET 2014',2014),
Q('junior','social','Which article of the Indian Constitution provides for "Equality before Law"?',['Article 14','Article 15','Article 16','Article 17'],'Article 14','CTET 2015',2015),
Q('junior','social','The "Rajya Sabha" members are elected for a term of-',['4 years','5 years','6 years','Permanent'],'6 years','UPTET 2016',2016),
Q('junior','social','The "Amazon Rainforest" is located in which continent?',['Africa','South America','Asia','Australia'],'South America','CTET 2017',2017),
Q('junior','social','Who was the first woman Prime Minister of India?',['Sarojini Naidu','Indira Gandhi','Sushma Swaraj','None'],'Indira Gandhi','UPTET 2018',2018),
Q('junior','social','The "Dandi March" was against which law?',['Salt tax','Forest law','Press law','None'],'Salt tax','CTET 2019',2019),
Q('junior','social','The "Supreme Court" of India is located at-',['Mumbai','Kolkata','Chennai','New Delhi'],'New Delhi','UPTET 2020',2020),
Q('junior','social','Which planet is known as the "Red Planet"?',['Venus','Mars','Jupiter','Saturn'],'Mars','CTET 2021',2021),
Q('junior','social','The "Battle of Haldighati" was fought between-',['Akbar and Maharana Pratap','Babur and Rana Sanga','Hemu and Akbar','None'],'Akbar and Maharana Pratap','UPTET 2021',2021),
Q('junior','social','Who founded the "Prarthana Samaj"?',['Atmaram Pandurang','Raja Ram Mohan Roy','Swami Dayananda','None'],'Atmaram Pandurang','CTET 2022',2022),
Q('junior','social','The "Preamble" of the Indian Constitution was amended by which act?',['42nd','44th','52nd','61st'],'42nd','UPTET 2022',2022),
Q('junior','social','The "Tropic of Cancer" does not pass through which state?',['Rajasthan','Chhattisgarh','Odisha','Tripura'],'Odisha','CTET 2023',2023),
Q('junior','social','Who was the first Chief Justice of India?',['H.J. Kania','M. Patanjali Sastri','Mehr Chand Mahajan','None'],'H.J. Kania','UPTET 2023',2023),
Q('junior','social','The "Satyashodhak Samaj" was founded by-',['Jyotiba Phule','B.R. Ambedkar','Mahatma Gandhi','None'],'Jyotiba Phule','CTET 2018',2018),
Q('junior','social','Which is the largest producer of sugar in the world?',['India','Brazil','Cuba','China'],'Brazil','UPTET 2017',2017),
Q('junior','social','The "Fundamental Duties" were added to the Constitution by-',['42nd Amendment','44th Amendment','73rd Amendment','None'],'42nd Amendment','CTET 2016',2016),
Q('junior','social','The "Municipalities" were given constitutional status by which amendment?',['73rd','74th','42nd','44th'],'74th','UPTET 2015',2015),
Q('junior','social','Who was the Governor-General of India during the 1857 revolt?',['Lord Canning','Lord Dalhousie','Lord Bentinck','None'],'Lord Canning','CTET 2014',2014),
Q('junior','social','Which state is known as the "Spice Garden of India"?',['Tamil Nadu','Karnataka','Kerala','Andhra Pradesh'],'Kerala','UPTET 2013',2013),
Q('junior','social','The "United Nations" was established in-',['1919','1945','1950','None'],'1945','CTET 2012',2012),
Q('junior','social','The "Indian Standard Time" is based on which meridian?',['80° E','82.5° E','85° E','None'],'82.5° E','UPTET 2012',2012),
Q('junior','social','Who was the first Indian to win a Nobel Prize?',['C.V. Raman','Rabindranath Tagore','Mother Teresa','None'],'Rabindranath Tagore','CTET 2011',2011),
Q('junior','social','The "Samaveda" is a collection of-',['Hymns','Melodies','Rituals','None'],'Melodies','UPTET 2011',2011),
Q('junior','social','The "State Emblem" of India features which animals?',['Lions, Elephant, Horse, Bull','Tigers, Elephant, Deer','Lions, Tiger, Cow','None'],'Lions, Elephant, Horse, Bull','CTET 2023',2023),
Q('junior','social','Which is the highest mountain peak in India?',['K2 (Godwin Austen)','Mount Everest','Kanchenjunga','Nanda Devi'],'K2 (Godwin Austen)','UPTET 2020',2020),
Q('junior','social','The "Governor" of a state is appointed by-',['Chief Minister','President','Prime Minister','None'],'President','CTET 2022',2022),
Q('junior','social','Who was the first Indian woman to become the President of INC?',['Annie Besant','Sarojini Naidu','Indira Gandhi','None'],'Sarojini Naidu','UPTET 2019',2019),
Q('junior','social','The "Quit India Movement" was launched in response to-',['Cripps Proposals','Simon Commission Report','Wavell Plan','None'],'Cripps Proposals','CTET 2021',2021),
Q('junior','social','The "Sun Temple" of Konark was built by-',['Narasimhadeva I','Rajendra Chola','Chandragupta','None'],'Narasimhadeva I','UPTET 2018',2018),
Q('junior','social','The "White Revolution" is also known as-',['Operation Flood','Operation Milk','Project Green','None'],'Operation Flood','CTET 2020',2020),
Q('junior','social','Who founded the "Aligarh Muslim University"?',['Sir Sayyid Ahmad Khan','Mohammad Ali Jinnah','Abul Kalam Azad','None'],'Sir Sayyid Ahmad Khan','UPTET 2017',2017),
Q('junior','social','The "Minimum age" for voting in India is-',['18 years','21 years','25 years','None'],'18 years','CTET 2019',2019),
Q('junior','social','Which is the largest freshwater lake in the world?',['Lake Superior','Lake Victoria','Lake Baikal','Caspian Sea'],'Lake Superior','CTET 2016',2016),
Q('junior','social','The "Ghadar Party" was founded in-',['1913','1915','1919','None'],'1913','UPTET 2022',2022),
Q('junior','social','The "Parliamentary system" in India was taken from-',['USA','UK','Canada','None'],'UK','CTET 2015',2015),
Q('junior','social','Which river is known as the "Vridha Ganga"?',['Krishna','Godavari','Cauvery','Narmada'],'Godavari','UPTET 2021',2021),
Q('junior','social','The "Upanishads" are books on-',['Religion','Yoga','Philosophy','Law'],'Philosophy','CTET 2014',2014),
Q('junior','social','Who was the first woman to win a Nobel Prize?',['Marie Curie','Mother Teresa','Sarojini Naidu','None'],'Marie Curie','UPTET 2014',2014),
Q('junior','social','The "Khajuraho Temples" were built by-',['Chandelas','Cholas','Pushtis','None'],'Chandelas','CTET 2013',2013),
Q('junior','social','Which is the smallest ocean in the world?',['Atlantic','Indian','Arctic','Pacific'],'Arctic','UPTET 2013',2013),
Q('junior','social','The "Kaziranga National Park" is famous for-',['Lions','Rhinos','Tigers','Elephants'],'Rhinos','CTET 2012',2012),
Q('junior','social','The "Constitution Day" of India is celebrated on-',['26th Jan','15th Aug','26th Nov','None'],'26th Nov','UPTET 2012',2012),
Q('junior','social','The "First World War" began in-',['1912','1914','1918','1939'],'1914','CTET 2011',2011),
Q('junior','social','Which of the following is a Kharif crop?',['Wheat','Barley','Rice','Gram'],'Rice','UPTET 2023',2023),
Q('junior','social','The "Comptroller and Auditor General" is appointed by-',['President','Prime Minister','Finance Minister','None'],'President','CTET 2020',2020),
Q('junior','social','The "Grey Revolution" is related to-',['Wool','Fertilizers','Milk','None'],'Fertilizers','UPTET 2011',2011),
Q('junior','social','The "International Women\'s Day" is celebrated on-',['8th March','5th June','1st Dec','None'],'8th March','CTET 2022',2022),
];
