const { v4: uuidv4 } = require('uuid');
const Q = (l,s,t,o,a,src,yr) => ({question_id:uuidv4(),level:l,subject:s,question_text:t,options:o,correct_answer:a,source:src,year:yr,language:'english',created_at:new Date()});

module.exports = [
Q('junior','social','The first session of the Indian National Congress was held in-',['Calcutta','Bombay','Madras','Delhi'],'Bombay','CTET 2011',2011),
Q('junior','social','Who was the first Governor-General of independent India?',['Lord Mountbatten','C. Rajagopalachari','Lord Dalhousie','Lord Canning'],'Lord Mountbatten','UPTET 2012',2012),
Q('junior','social','The Indus Valley Civilization was primarily located in-',['North India','South India','North-West India','East India'],'North-West India','CTET 2013',2013),
Q('junior','social','The "Quit India Movement" was launched in the year-',['1940','1942','1945','1947'],'1942','UPTET 2014',2014),
Q('junior','social','Which of the following is a fundamental right in India?',['Right to property','Right to equality','Right to work','None'],'Right to equality','CTET 2015',2015),
Q('junior','social','The President of India is elected for a term of-',['4 years','5 years','6 years','7 years'],'5 years','UPTET 2016',2016),
Q('junior','social','The longest river in the world is-',['Amazon','Nile','Ganga','Mississipi'],'Nile','CTET 2017',2017),
Q('junior','social','The Constitution of India was adopted on-',['15th Aug 1947','26th Nov 1949','26th Jan 1950','None'],'26th Nov 1949','UPTET 2018',2018),
Q('junior','social','Who is known as the "Iron Man of India"?',['Jawaharlal Nehru','Subhash Chandra Bose','Sardar Vallabhbhai Patel','Mahatma Gandhi'],'Sardar Vallabhbhai Patel','CTET 2019',2019),
Q('junior','social','The highest judicial body in India is-',['High Court','District Court','Supreme Court','None'],'Supreme Court','UPTET 2020',2020),
Q('junior','social','Which planet is known as the "Red Planet"?',['Earth','Mars','Venus','Jupiter'],'Mars','CTET 2021',2021),
Q('junior','social','The first battle of Panipat was fought in-',['1526','1556','1761','None'],'1526','UPTET 2021',2021),
Q('junior','social','Who wrote the book "Discovery of India"?',['Mahatma Gandhi','Jawaharlal Nehru','B.R. Ambedkar','Rabindranath Tagore'],'Jawaharlal Nehru','CTET 2022',2022),
Q('junior','social','The Capital of India was shifted from Calcutta to Delhi in-',['1905','1911','1919','1947'],'1911','UPTET 2022',2022),
Q('junior','social','The Earth rotates from-',['East to West','West to East','North to South','South to North'],'West to East','CTET 2023',2023),
Q('junior','social','Who was the first female Prime Minister of India?',['Pratibha Patil','Indira Gandhi','Sushma Swaraj','Sarojini Naidu'],'Indira Gandhi','UPTET 2023',2023),
Q('junior','social','The "Ghadar Party" was founded in-',['San Francisco','Berlin','London','Tokyo'],'San Francisco','CTET 2018',2018),
Q('junior','social','Which mountain range separates Europe from Asia?',['Himalayas','Alps','Ural','Andes'],'Ural','UPTET 2017',2017),
Q('junior','social','The "Preamble" of the Indian Constitution starts with the words-',['We, the people of India','Justice, Liberty, Equality','Sovereign, Socialist','None'],'We, the people of India','CTET 2016',2016),
Q('junior','social','The largest producer of wheat in the world is-',['India','USA','China','Russia'],'China','UPTET 2015',2015),
Q('junior','social','Who started the "Bhoodan Movement"?',['Vinoba Bhave','Jayaprakash Narayan','Mahatma Gandhi','Baba Amte'],'Vinoba Bhave','CTET 2014',2014),
Q('junior','social','Which city is known as the "Pink City" of India?',['Jaipur','Udaipur','Jodhpur','Agra'],'Jaipur','UPTET 2013',2013),
Q('junior','social','The "World Trade Organization" (WTO) was established in-',['1945','1991','1995','2000'],'1995','CTET 2012',2012),
Q('junior','social','The "Right to Information Act" (RTI) was passed in India in-',['2000','2005','2010','2012'],'2005','UPTET 2012',2012),
Q('junior','social','Who was the founder of the Maurya Empire?',['Ashoka','Chandragupta Maurya','Bindusara','Harsha'],'Chandragupta Maurya','CTET 2011',2011),
Q('junior','social','The main source of Indian history of the ancient period is-',['Coins','Inscriptions','Literary sources','All of these'],'All of these','UPTET 2011',2011),
Q('junior','social','The "National Song" of India was written by-',['Rabindranath Tagore','Bankim Chandra Chatterjee','Sarojini Naidu','None'],'Bankim Chandra Chatterjee','CTET 2023',2023),
Q('junior','social','Which is the smallest state of India in terms of area?',['Sikkim','Goa','Tripura','Manipur'],'Goa','UPTET 2020',2020),
Q('junior','social','The "Rajya Sabha" is also known as-',['Lower House','Upper House','House of People','None'],'Upper House','CTET 2022',2022),
Q('junior','social','Who was the first Law Minister of independent India?',['Jawaharlal Nehru','B.R. Ambedkar','Sardar Patel','Maulana Azad'],'B.R. Ambedkar','UPTET 1019',2019),
Q('junior','social','The "Dandi March" was related to-',['Salt Satyagraha','Non-Cooperation','Civil Disobedience','Quit India'],'Salt Satyagraha','CTET 2021',2021),
Q('junior','social','The "Sun Temple" is located at-',['Konark','Madurai','Khajuraho','Agra'],'Konark','UPTET 2018',2018),
Q('junior','social','The "Green Revolution" in India was related to-',['Milk','Agriculture','Forestry','Fisheries'],'Agriculture','CTET 2020',2020),
Q('junior','social','Who was the founder of "Arya Samaj"?',['Swami Vivekananda','Dayananda Saraswati','Raja Ram Mohan Roy','None'],'Dayananda Saraswati','UPTET 2017',2017),
Q('junior','social','The "Panchayati Raj" system was first introduced in-',['Rajasthan','Andhra Pradesh','Bihar','Punjab'],'Rajasthan','CTET 2019',2019),
Q('junior','social','Which is the largest desert in the world?',['Thar','Sahara','Gobi','Atacama'],'Sahara','CTET 2016',2016),
Q('junior','social','The "Battle of Plassey" was fought in-',['1757','1764','1857','1947'],'1757','UPTET 2022',2022),
Q('junior','social','The "Fundamental Duties" were added to the Constitution by-',['42nd Amendment','44th Amendment','73rd Amendment','None'],'42nd Amendment','CTET 2015',2015),
Q('junior','social','Which river is known as "Dakshin Ganga"?',['Krishna','Kaveri','Godavari','Narmada'],'Godavari','UPTET 2021',2021),
Q('junior','social','The "Vedas" are written in which language?',['Pali','Prakrit','Sanskrit','Hindi'],'Sanskrit','CTET 2014',2014),
Q('junior','social','Who was the first woman to climb Mount Everest?',['Junko Tabei','Bachendri Pal','Santosh Yadav','None'],'Junko Tabei','UPTET 2014',2014),
Q('junior','social','The "Red Fort" in Delhi was built by-',['Akbar','Shah Jahan','Humayun','Sher Shah Suri'],'Shah Jahan','CTET 2013',2013),
Q('junior','social','Which is the largest ocean in the world?',['Atlantic','Indian','Pacific','Arctic'],'Pacific','UPTET 2013',2013),
Q('junior','social','The "Kaziranga National Park" is famous for-',['Tigers','One-horned Rhinoceros','Elephants','Lions'],'One-horned Rhinoceros','CTET 2012',2012),
Q('junior','social','The "First War of Independence" started in-',['1857','1757','1942','1947'],'1857','UPTET 2012',2012),
Q('junior','social','The "Bharat Ratna" is the highest ___ award of India.',['Military','Civilian','Sport','Literary'],'Civilian','CTET 2011',2011),
Q('junior','social','Which of the following is a Kharif crop?',['Wheat','Gram','Rice','Mustard'],'Rice','UPTET 2023',2023),
Q('junior','social','The "Parliament" of India consists of-',['Lok Sabha and Rajya Sabha','Lok Sabha, Rajya Sabha and President','Lok Sabha and President','None'],'Lok Sabha, Rajya Sabha and President','CTET 2020',2020),
Q('junior','social','The "White Revolution" is related to-',['Egg','Milk','Fish','Grain'],'Milk','UPTET 2011',2011),
Q('junior','social','The "Earth Day" is celebrated on-',['22nd April','5th June','16th Sept','1st Dec'],'22nd April','CTET 2022',2022),
];
