const { v4: uuidv4 } = require('uuid');
const Q = (l,s,t,o,a,src,yr) => ({question_id:uuidv4(),level:l,subject:s,question_text:t,options:o,correct_answer:a,source:src,year:yr,language:'english',created_at:new Date()});

module.exports = [
Q('primary','pedagogy','According to Vygotsky, cognitive development is a ___ process.',['Individual','Social','Biological','Mechanical'],'Social','CTET 2018',2018),
Q('primary','pedagogy','The "Laws of Learning" were formulated by-',['Pavlov','Thorndike','Skinner','Kohler'],'Thorndike','UPTET 2017',2017),
Q('primary','pedagogy','Which of the following is a characteristic of childhood?',['Thinking is ego-centric','Abstract reasoning starts','Rapid physical growth like infancy','None'],'Thinking is ego-centric','CTET 2019',2019),
Q('primary','pedagogy','The concept of "Mental Age" was first used in the scale developed by-',['Binet and Simon','Terman','Stern','Cattell'],'Binet and Simon','UPTET 2016',2016),
Q('primary','pedagogy','Which of the following is a tool for Summative Assessment?',['Class tests','Oral questions','Term-end exams','Assignments'],'Term-end exams','CTET 2021',2021),
Q('primary','pedagogy','The development that proceeds from the center of the body towards the extremities is-',['Cephalocaudal','Proximodistal','General to specific','Linear'],'Proximodistal','CTET 2022',2022),
Q('primary','pedagogy','"Meaningful learning" according to constructivists involves-',['Passive absorption of information','Active creation of knowledge from experience','Rote memorization','Modeling the teacher'],'Active creation of knowledge from experience','CTET 2023',2023),
Q('primary','pedagogy','Who is the author of "Emile"?',['Plato','Aristotle','Rousseau','Dewey'],'Rousseau','UPTET 2015',2015),
Q('primary','pedagogy','The IQ of a gifted child is generally-',['Above 140','Above 110','Above 90','Above 120'],'Above 140','UPTET 2018',2018),
Q('primary','pedagogy','The main purpose of a "Diagnostic Test" is to identify-',['The rank of the student','The learning gaps of the student','The intelligence of the student','The interest of the student'],'The learning gaps of the student','CTET 2020',2020),
Q('primary','pedagogy','Which of the following is an example of an extrinsic motivation?',['Enjoying the activity','Learning for curiosity','Winning a trophy','Gaining self-satisfaction'],'Winning a trophy','CTET 2022',2022),
Q('primary','pedagogy','According to Erikson, the stage of "Trust vs Mistrust" occurs during-',['Infancy','Early Childhood','School Age','Adolescence'],'Infancy','UPTET 2019',2019),
Q('primary','pedagogy','The "Gestalt" theory of learning emphasizes-',['Trial and error','Conditioning','Perception of the whole','Imitation'],'Perception of the whole','CTET 2017',2017),
Q('primary','pedagogy','Micro-teaching cycle duration is usually-',['30 minutes','36 minutes','45 minutes','60 minutes'],'36 minutes','UPTET 2021',2021),
Q('primary','pedagogy','Which of the following is NOT a stage of Piaget\'s cognitive development?',['Sensorimotor','Pre-operational','Post-operational','Concrete operational'],'Post-operational','CTET 2016',2016),
Q('primary','pedagogy','The process by which children learn the values and norms of their society is-',['Growth','Socialization','Maturation','Evaluation'],'Socialization','CTET 2015',2015),
Q('primary','pedagogy','Which type of reinforcement is most effective for long-term behavior change?',['Continuous','Intermittent (Partial)','Punishment','Negative reinforcement'],'Intermittent (Partial)','CTET 2023',2023),
Q('primary','pedagogy','The concept of "Multiple Intelligences" was given by-',['Spearman','Gardner','Thurstone','Binet'],'Gardner','UPTET 2014',2014),
Q('primary','pedagogy','Which of the following is a primary law of learning according to Thorndike?',['Law of effect','Law of exercise','Law of readiness','All of these'],'All of these','UPTET 2013',2013),
Q('primary','pedagogy','The period of "Adolescence" is often called the period of-',['Peace','Stress and storm','Silent growth','None'],'Stress and storm','CTET 2012',2012),
Q('primary','pedagogy','Who said "Child is a book which the teacher has to learn from page to page"?',['Plato','Rousseau','Aristotle','None'],'Rousseau','UPTET 2012',2012),
Q('primary','pedagogy','The "Discovery Learning" method was advocated by-',['Bruner','Piaget','Skinner','Pavlov'],'Bruner','CTET 2011',2011),
Q('primary','pedagogy','Which of the following is a learner-centered teaching method?',['Lecture','Demonstration','Project','Dictation'],'Project','UPTET 2011',2011),
Q('primary','pedagogy','Language is a tool for-',['Communication','Thinking','Expression','All of these'],'All of these','CTET 2023',2023),
Q('primary','pedagogy','The term "Maturation" refers to-',['Social development','Biological growth and readiness','Emotional stability','Intelligence'],'Biological growth and readiness','UPTET 2020',2020),
Q('primary','pedagogy','Which of the following is an objective of NCF 2005?',['Connecting knowledge to life outside school','Ensuring rote learning','Increasing exam pressure','Focusing only on textbooks'],'Connecting knowledge to life outside school','CTET 2021',2021),
Q('primary','pedagogy','Creativity can be fostered by-',['Giving freedom to explore','Restricting questions','Imposing strict discipline','None'],'Giving freedom to explore','CTET 2022',2022),
Q('primary','pedagogy','The "Classical Conditioning" theory was given by-',['Skinner','Pavlov','Watson','Thorndike'],'Pavlov','UPTET 2018',2018),
Q('primary','pedagogy','Inclusive education emphasizes-',['Separation of disabled students','Equal opportunities for all','Special classes for bright students','None'],'Equal opportunities for all','CTET 2019',2019),
Q('primary','pedagogy','The term "Pedagogy" refers to-',['Study of children','Science of teaching','Study of exams','Management of school'],'Science of teaching','UPTET 2017',2017),
Q('primary','pedagogy','A child who can solve problems logicially but needs concrete objects is in which stage?',['Sensorimotor','Pre-operational','Concrete operational','Formal operational'],'Concrete operational','CTET 2018',2018),
Q('primary','pedagogy','Emotional intelligence involves-',['Self-awareness','Self-regulation','Empathy','All of these'],'All of these','UPTET 2016',2016),
Q('primary','pedagogy','Which of the following is a project aid?',['Overhead projector','Blackboard','Charts','Maps'],'Overhead projector','CTET 2017',2017),
Q('primary','pedagogy','The "Action Research" is used by-',['Scientists','Teachers and practitioners','Philosophers','Historians'],'Teachers and practitioners','UPTET 2015',2015),
Q('primary','pedagogy','The main focus of a teacher should be on-',['Syllabus completion','Learning of every child','Discipline','Administrative work'],'Learning of every child','CTET 2020',2020),
Q('primary','pedagogy','Which of the following is a gross motor skill?',['Cutting paper','Drawing','Jumping','Writing'],'Jumping','CTET 2014',2014),
Q('primary','pedagogy','The "Law of Exercise" refers to-',['Practice','Interest','Readiness','Reward'],'Practice','UPTET 2014',2014),
Q('primary','pedagogy','What is the full form of RTE?',['Right to Education','Rule to Education','Right to Energy','None'],'Right to Education','CTET 2013',2013),
Q('primary','pedagogy','According to Kohlberg, moral reasoning depends on-',['Age','Context','Cognitive development','Society'],'Cognitive development','CTET 2012',2012),
Q('primary','pedagogy','Which of the following is a trait of a creative thinker?',['Conformity','Flexibility','Rigidity','Fear of failure'],'Flexibility','CTET 2011',2011),
Q('primary','pedagogy','The best way to handle a hyperactive child is to-',['Punish them','Give them extra tasks involving physical activity','Ignore them','Keep them in a separate room'],'Give them extra tasks involving physical activity','UPTET 2023',2023),
Q('primary','pedagogy','Which of the following is a form of non-verbal communication?',['Speech','Writing','Body language','E-mail'],'Body language','CTET 2023',2023),
Q('primary','pedagogy','The theory of "Operant Conditioning" is associated with-',['Pavlov','Skinner','Watson','Bandura'],'Skinner','UPTET 2022',2022),
Q('primary','pedagogy','Which of the following is a characteristic of an effective teacher?',['Subject mastery','Empathy for students','Fairness','All of these'],'All of these','CTET 2022',2022),
Q('primary','pedagogy','What is the minimum age for a child to be admitted to school according to NEP 2020?',['3 years','5 years','6 years','4 years'],'3 years','UPTET 2021',2021),
Q('primary','pedagogy','The "Play-way" method was introduced by-',['Froebel','Dewey','Kilpatrick','Thorndike'],'Froebel','CTET 2021',2021),
Q('primary','pedagogy','The concept of "Object Permanence" is developed during-',['Sensorimotor stage','Pre-operational stage','Concrete operational','Formal operational'],'Sensorimotor stage','CTET 2020',2020),
Q('primary','pedagogy','Which of the following is a barrier to inclusive education?',['Lack of resources','Negative attitude','Inaccessible infrastructure','All of these'],'All of these','UPTET 2020',2020),
Q('primary','pedagogy','The "S-R Theory" (Stimulus-Response) is given by-',['Pavlov','Thorndike','Watson','Skinner'],'Thorndike','UPTET 2019',2019),
Q('primary','pedagogy','Which of the following is a key element of the learning process?',['Learner','Stimulus','Response','All of these'],'All of these','CTET 2019',2019),
];
