const { v4: uuidv4 } = require('uuid');
const Q = (l,s,t,o,a,src,yr) => ({question_id:uuidv4(),level:l,subject:s,question_text:t,options:o,correct_answer:a,source:src,year:yr,language:'english',created_at:new Date()});

module.exports = [
Q('primary','pedagogy','According to Piaget, which stage of cognitive development is characterized by the ability to think abstractly?',['Sensorimotor','Pre-operational','Concrete operational','Formal operational'],'Formal operational','CTET 2019',2019),
Q('primary','pedagogy','Who developed the concept of the Zone of Proximal Development (ZPD)?',['Jean Piaget','Lev Vygotsky','B.F. Skinner','Albert Bandura'],'Lev Vygotsky','CTET 2018',2018),
Q('primary','pedagogy','The concept of "scaffolding" in learning was introduced by-',['Jerome Bruner','Lev Vygotsky','Jean Piaget','Ivan Pavlov'],'Jerome Bruner','UPTET 2019',2019),
Q('primary','pedagogy','Which type of intelligence was NOT proposed by Howard Gardner in his multiple intelligences theory?',['Logical-Mathematical','Musical','Emotional','Interpersonal'],'Emotional','CTET 2021',2021),
Q('primary','pedagogy','Inclusive education refers to-',['Special schools for disabled children','Education for gifted children only','Educating all children regardless of their abilities in the same classroom','Separate classrooms for girls and boys'],'Educating all children regardless of their abilities in the same classroom','CTET 2022',2022),
Q('primary','pedagogy','According to Kohlberg, at which level of moral development do individuals follow rules to avoid punishment?',['Pre-conventional','Conventional','Post-conventional','Transcendental'],'Pre-conventional','CTET 2017',2017),
Q('primary','pedagogy','The "Trial and Error" theory of learning was given by-',['Thorndike','Pavlov','Skinner','Kohler'],'Thorndike','UPTET 2018',2018),
Q('primary','pedagogy','Which of the following is a primary agent of socialization for children?',['School','Media','Family','Government'],'Family','CTET 2020',2020),
Q('primary','pedagogy','The NCF 2005 emphasizes that the role of a teacher should be-',['Authoritative','Dictatorial','Facilitative','Permissive'],'Facilitative','CTET 2018',2018),
Q('primary','pedagogy','"Dyslexia" is primarily associated with difficulties in-',['Calculating','Writing','Reading','Speaking'],'Reading','CTET 2019',2019),
Q('primary','pedagogy','Which of the following is a tool for Formative Assessment?',['Term-end examination','Projects and assignments','Final grades','Standardized tests'],'Projects and assignments','UPTET 2021',2021),
Q('primary','pedagogy','The development of a child starts from the-',['Birth','Infancy stage','Pre-natal stage','Post-natal stage'],'Pre-natal stage','CTET 2016',2016),
Q('primary','pedagogy','Who is known as the father of behaviorism?',['John B. Watson','William James','Sigmund Freud','Erik Erikson'],'John B. Watson','UPTET 2017',2017),
Q('primary','pedagogy','Social learning theory was proposed by-',['B.F. Skinner','Albert Bandura','Jean Piaget','Noam Chomsky'],'Albert Bandura','CTET 2021',2021),
Q('primary','pedagogy','The term "Nature" in the nature-nurture debate refers to-',['Environmental forces','Biological givens or genetic information','Temperament of an individual','Complex forces of the physical world'],'Biological givens or genetic information','CTET 2015',2015),
Q('primary','pedagogy','Which of the following is an example of an intrinsic motivator?',['Praise from teacher','A gold medal','Personal interest in the subject','Avoiding a fine'],'Personal interest in the subject','CTET 2022',2022),
Q('primary','pedagogy','Erikson’s theory of psychosocial development consists of how many stages?',['5','6','7','8'],'8','UPTET 2018',2018),
Q('primary','pedagogy','According to Maslow’s hierarchy, which is the highest level of human needs?',['Safety needs','Social needs','Self-actualization','Esteem needs'],'Self-actualization','CTET 2023',2023),
Q('primary','pedagogy','Constructivism as a theory emphasizes-',['The role of imitation','The role of the learner in creating their own functional knowledge','Memorizing information','Conditioning behavior'],'The role of the learner in creating their own functional knowledge','CTET 2019',2019),
Q('primary','pedagogy','The IQ of a child is 100. This means that-',['The child is below average','The child’s mental age is equal to their chronological age','The child is a genius','The child is mentally retarded'],'The child’s mental age is equal to their chronological age','UPTET 2016',2016),
Q('primary','pedagogy','Which method of teaching is most suitable for primary school children?',['Lecture method','Discovery method','Play-way method','Demonstration method'],'Play-way method','CTET 2020',2020),
Q('primary','pedagogy','The right of children to Free and Compulsory Education Act (RTE) was enacted in-',['2005','2009','2010','2012'],'2009','CTET 2011',2011),
Q('primary','pedagogy','What is the main purpose of CCE (Continuous and Comprehensive Evaluation)?',['To rank students','To identify the learning gaps and provide remedial teaching','To declare students pass or fail','To increase the load on students'],'To identify the learning gaps and provide remedial teaching','UPTET 2019',2019),
Q('primary','pedagogy','ADHD stands for-',['Attention Deficit Hyperactivity Disorder','Active Deficit High Disorder','Attention Disorder High Disease','None of the above'],'Attention Deficit Hyperactivity Disorder','CTET 2021',2021),
Q('primary','pedagogy','The "Insightful Learning" theory was given by-',['Thorndike','Kohler','Pavlov','Skinner'],'Kohler','UPTET 2020',2020),
Q('primary','pedagogy','Which of the following is NOT a sign of an intelligent young child?',['One who has the ability to carry on abstract thinking','One who can adjust oneself in a new environment','One who has the ability to cram long essays very quickly','One who can communicate fluently and appropriately'],'One who has the ability to cram long essays very quickly','CTET 2012',2012),
Q('primary','pedagogy','Growth is a ___ process while development is a ___ process.',['Qualitative, Quantitative','Quantitative, Qualitative','Social, Physical','Biological, Social'],'Quantitative, Qualitative','CTET 2014',2014),
Q('primary','pedagogy','The principle of "Cephalocaudal" development suggests that growth proceeds from-',['Center to periphery','Head to toe','Toe to head','General to specific'],'Head to toe','CTET 2022',2022),
Q('primary','pedagogy','A teacher should always encourage students to be-',['Passive listeners','Active participants','Silent observers','Rote learners'],'Active participants','CTET 2023',2023),
Q('primary','pedagogy','Micro-teaching is most effective for-',['Primary students','Teacher trainees','High school students','None of the above'],'Teacher trainees','UPTET 2015',2015),
Q('primary','pedagogy','The "Law of Readiness" was proposed by-',['Skinner','Thorndike','Watson','Dewey'],'Thorndike','UPTET 2013',2013),
Q('primary','pedagogy','Which of the following is a fine motor skill?',['Running','Jumping','Writing','Climbing'],'Writing','CTET 2020',2020),
Q('primary','pedagogy','Language acquisition theory was given by-',['Vygotsky','Chomsky','Piaget','Bruner'],'Chomsky','CTET 2018',2018),
Q('primary','pedagogy','Creativity is usually associated with-',['Convergent thinking','Divergent thinking','Modeling','Imitation'],'Divergent thinking','CTET 2017',2017),
Q('primary','pedagogy','The period of "Infancy" ranges from-',['Birth to 2 years','2 to 6 years','6 to 12 years','12 to 18 years'],'Birth to 2 years','CTET 2015',2015),
Q('primary','pedagogy','Which of the following is a secondary agent of socialization?',['Family','Neighborhood','School','Parental workplace'],'School','CTET 2022',2022),
Q('primary','pedagogy','The "Theory of Identity Crisis" was given by-',['Freud','Erikson','Piaget','Jung'],'Erikson','UPTET 2017',2017),
Q('primary','pedagogy','Assessment for learning uses-',['Summative evaluation','Diagnostic and formative evaluation','Final grades only','Peer assessment only'],'Diagnostic and formative evaluation','CTET 2021',2021),
Q('primary','pedagogy','Which philosopher believed that a child’s mind is a "Tabula Rasa" (Clean Slate)?',['Jean-Jacques Rousseau','John Locke','Immanuel Kant','Plato'],'John Locke','UPTET 2014',2014),
Q('primary','pedagogy','The use of teaching aids makes the learning process-',['Boring','Difficult','Interesting and effective','Expensive'],'Interesting and effective','CTET 2020',2020),
Q('primary','pedagogy','In an inclusive classroom, the teacher should-',['Focus only on the bright students','Ignore the disabled students','Believe that every child has a potential to learn as per their abilities','Discriminate against slow learners'],'Believe that every child has a potential to learn as per their abilities','CTET 2023',2023),
Q('primary','pedagogy','Moral development theory was primarily developed by-',['Piaget and Kohlberg','Watson and Skinner','Pavlov and Thorndike','Bandura and Maslow'],'Piaget and Kohlberg','CTET 2018',2018),
Q('primary','pedagogy','The primary goal of education should be-',['Obtaining high marks','Clearing competitive exams','Overall development of the personality','Memorizing textbooks'],'Overall development of the personality','UPTET 2021',2021),
Q('primary','pedagogy','Learning by doing is most effective because-',['It is easy to manage','It promotes active engagement and better retention','It is less expensive','Children like to work'],'It promotes active engagement and better retention','CTET 2019',2019),
Q('primary','pedagogy','The term "Puberty" refers to-',['Early childhood','Late childhood','The transition from childhood to adulthood','Adulthood'],'The transition from childhood to adulthood','UPTET 2018',2018),
Q('primary','pedagogy','Who said, "Education is the manifestation of perfection already in man"?',['Mahatma Gandhi','Rabindranath Tagore','Swami Vivekananda','Sri Aurobindo'],'Swami Vivekananda','UPTET 2016',2016),
Q('primary','pedagogy','The concept of "Mental Age" was introduced by-',['Terman','Binet','Stern','Cattell'],'Binet','UPTET 2015',2015),
Q('primary','pedagogy','Which of the following is a visual aid?',['Radio','Tape recorder','Charts','Language lab'],'Charts','CTET 2017',2017),
Q('primary','pedagogy','A child who struggles with mathematical operations may have-',['Dyslexia','Dysgraphia','Dyscalculia','Dyspraxia'],'Dyscalculia','CTET 2022',2022),
Q('primary','pedagogy','The most effective way to teach a new concept is to move from-',['Abstract to concrete','Complex to simple','Concrete to abstract','Unknown to known'],'Concrete to abstract','CTET 2023',2023),
];
