const { v4: uuidv4 } = require('uuid');
const Q = (l,s,t,o,a,src,yr) => ({question_id:uuidv4(),level:l,subject:s,question_text:t,options:o,correct_answer:a,source:src,year:yr,language:'english',created_at:new Date()});

module.exports = [
Q('junior','science','The process of conversion of water vapor into water is called-',['Evaporation','Condensation','Sublimation','Freezing'],'Condensation','CTET 2011',2011),
Q('junior','science','Which of the following is a chemical change?',['Melting of ice','Boiling of water','Burning of paper','Breaking of glass'],'Burning of paper','UPTET 2012',2012),
Q('junior','science','The smallest unit of an element that maintains the properties of that element is-',['Atom','Molecule','Compound','Cell'],'Atom','CTET 2013',2013),
Q('junior','science','Which of the following is a major constituent of natural gas?',['Methane','Ethane','Propane','Butane'],'Methane','UPTET 2014',2014),
Q('junior','science','The force that opposes the motion of an object is called-',['Gravity','Friction','Inertia','Magnetic force'],'Friction','CTET 2015',2015),
Q('junior','science','Which of the following is a conductor of electricity?',['Wood','Plastic','Copper','Rubber'],'Copper','UPTET 2016',2016),
Q('junior','science','The speed of light is approximately-',['300,000 km/s','30,000 km/s','3,000 km/s','3,000,000 km/s'],'300,000 km/s','CTET 2017',2017),
Q('junior','science','Which of the following is an acid?',['Sodium Hydroxide','Calcium Carbonate','Hydrochloric Acid','Sodium Chloride'],'Hydrochloric Acid','UPTET 2018',2018),
Q('junior','science','The SI unit of force is-',['Joule','Watt','Newton','Pascal'],'Newton','CTET 2019',2019),
Q('junior','science','Which organ in the human body is responsible for pumping blood?',['Lungs','Kidney','Heart','Liver'],'Heart','UPTET 2020',2020),
Q('junior','science','The process of photosynthesis takes place in which part of the plant?',['Roots','Stems','Leaves','Flowers'],'Leaves','CTET 2021',2021),
Q('junior','science','Which of the following is a non-renewable source of energy?',['Solar','Wind','Coal','Hydro'],'Coal','UPTET 2021',2021),
Q('junior','science','The human heart has how many chambers?',['2','3','4','5'],'4','CTET 2022',2022),
Q('junior','science','Which of the following is used in pencils?',['Graphite','Lead','Carbon','Coal'],'Graphite','UPTET 2022',2022),
Q('junior','science','The study of heredity is called-',['Ecology','Genetics','Evolution','Cytology'],'Genetics','CTET 2023',2023),
Q('junior','science','Which gas is released during photosynthesis?',['Carbon dioxide','Oxygen','Nitrogen','Hydrogen'],'Oxygen','UPTET 2023',2023),
Q('junior','science','Which of the following is a vector quantity?',['Mass','Speed','Velocity','Time'],'Velocity','CTET 2018',2018),
Q('junior','science','The normal temperature of a healthy human body is-',['98.6°F','37°C','Both A and B','None'],'Both A and B','UPTET 2017',2017),
Q('junior','science','Which of the following is a noble gas?',['Oxygen','Hydrogen','Helium','Nitrogen'],'Helium','CTET 2016',2016),
Q('junior','science','The change in direction of light when it passes from one medium to another is called-',['Reflection','Refraction','Dispersion','Diffraction'],'Refraction','UPTET 2015',2015),
Q('junior','science','Which of the following is a synthetic fiber?',['Cotton','Wool','Nylon','Silk'],'Nylon','CTET 2014',2014),
Q('junior','science','The chemical formula of common salt is-',['HCl','NaCl','NaOH','KOH'],'NaCl','UPTET 2013',2013),
Q('junior','science','Which planet is known as the Blue Planet?',['Mars','Earth','Venus','Neptune'],'Earth','CTET 2012',2012),
Q('junior','science','Which of the following is a mammal?',['Whale','Shark','Goldfish','Turtle'],'Whale','UPTET 2012',2012),
Q('junior','science','The power house of the cell is-',['Nucleus','Mitochondria','Ribosome','Golgi body'],'Mitochondria','CTET 2011',2011),
Q('junior','science','Which of the following is an example of an alloy?',['Iron','Copper','Steel','Aluminum'],'Steel','UPTET 2011',2011),
Q('junior','science','Which instrument is used to measure blood pressure?',['Thermometer','Barometer','Sphygmomanometer','Stethoscope'],'Sphygmomanometer','CTET 2023',2023),
Q('junior','science','Which of the following is a carbohydrate?',['Glucose','Protein','Fat','Vitamin'],'Glucose','UPTET 2020',2020),
Q('junior','science','The deficiency of Vitamin A causes-',['Scurvy','Rickets','Night blindness','Beriberi'],'Night blindness','CTET 2022',2022),
Q('junior','science','Which of the following is a producer in an ecosystem?',['Rabbit','Snake','Green plants','Eagle'],'Green plants','UPTET 2019',2019),
Q('junior','science','The atmospheric pressure is measured using a-',['Anemometer','Hygrometer','Barometer','Thermometer'],'Barometer','CTET 2021',2021),
Q('junior','science','Which of the following is a source of Vitamin C?',['Milk','Egg','Lemon','Meat'],'Lemon','UPTET 2018',2018),
Q('junior','science','The process of rusting of iron is an example of-',['Reduction','Oxidation','Sublimation','Distillation'],'Oxidation','CTET 2020',2020),
Q('junior','science','Which of the following is a physical property of matter?',['Flammability','Reactivity','Boiling point','Toxicity'],'Boiling point','UPTET 2017',2017),
Q('junior','science','The value of Acceleration due to gravity (g) on Earth is approx-',['9.8 m/s²','10.8 m/s²','8.8 m/s²','None'],'9.8 m/s²','CTET 2019',2019),
Q('junior','science','Which of the following is a digestive enzyme?',['Insulin','Pepsin','Hemoglobin','Thyroxine'],'Pepsin','CTET 2016',2016),
Q('junior','science','Which of the following is a conductor of heat?',['Plastic','Wood','Silver','Glass'],'Silver','UPTET 2022',2022),
Q('junior','science','The pH value of pure water is-',['0','7','14','None'],'7','CTET 2015',2015),
Q('junior','science','Which of the following is a primary color?',['Green','Orange','Purple','Brown'],'Green','UPTET 2021',2021),
Q('junior','science','The part of the eye which is sensitive to light is-',['Cornea','Iris','Retina','Lens'],'Retina','CTET 2014',2014),
Q('junior','science','Which of the following is an example of a simple machine?',['Lever','Computer','Car','Motorcycle'],'Lever','UPTET 2014',2014),
Q('junior','science','The sound waves cannot travel through-',['Air','Water','Steel','Vacuum'],'Vacuum','CTET 2013',2013),
Q('junior','science','Which of the following is a base?',['Lemon juice','Vinegar','Baking soda solution','Distilled water'],'Baking soda solution','UPTET 2013',2013),
Q('junior','science','The chemical symbol for Gold is-',['Ag','Au','Fe','Cu'],'Au','CTET 2012',2012),
Q('junior','science','Which of the following is a vertebrate?',['Insects','Worms','Fish','Crabs'],'Fish','UPTET 2012',2012),
Q('junior','science','The boiling point of water in Celsius is-',['0°C','50°C','100°C','200°C'],'100°C','CTET 2011',2011),
Q('junior','science','Which of the following is a non-metal that is liquid at room temperature?',['Mercury','Bromine','Iodine','Chlorine'],'Bromine','UPTET 2023',2023),
Q('junior','science','Which of the following is a plant hormone?',['Adrenaline','Thyroxine','Auxin','Insulin'],'Auxin','CTET 2020',2020),
Q('junior','science','The primary source of energy for the body is-',['Proteins','Vitamins','Carbohydrates','Minerals'],'Carbohydrates','UPTET 2011',2011),
Q('junior','science','Which of the following is an example of a balanced diet?',['Only rice','Only milk','A variety of foods in right proportions','Fast food'],'A variety of foods in right proportions','CTET 2022',2022),
];
