const { v4: uuidv4 } = require('uuid');
const Q = (l,s,t,o,a,src,yr) => ({question_id:uuidv4(),level:l,subject:s,question_text:t,options:o,correct_answer:a,source:src,year:yr,created_at:new Date()});

module.exports = [
Q('primary','english','Choose the correct article: "He is ___ honest man."',['a','an','the','no article'],'an','CTET 2018',2018),
Q('primary','english','Choose the correct article: "She is ___ university student."',['a','an','the','no article'],'a','UPTET 2018',2018),
Q('primary','english','Identify the noun: "Happiness is important."',['Happiness','Is','Important','None'],'Happiness','CTET 2017',2017),
Q('primary','english','The plural of "child" is-',['Childs','Children','Childrens','Childes'],'Children','UPTET 2017',2017),
Q('primary','english','The plural of "tooth" is-',['Tooths','Teeth','Teeths','Toothes'],'Teeth','CTET 2016',2016),
Q('primary','english','Which is a pronoun?',['Delhi','Rohan','He','Beautiful'],'He','UPTET 2016',2016),
Q('primary','english','Choose the adjective: "It was a sunny day."',['It','Was','Sunny','Day'],'Sunny','CTET 2021',2021),
Q('primary','english','The feminine of "actor" is-',['Actress','Actorin','Actoress','Actor'],'Actress','UPTET 2021',2021),
Q('primary','english','Choose the correct preposition: "The book is ___ the table."',['in','at','on','over'],'on','CTET 2020',2020),
Q('primary','english','Choose the correct preposition: "He is afraid ___ dogs."',['at','of','with','from'],'of','UPTET 2020',2020),
Q('primary','english','The synonym of "Huge" is-',['Small','Tiny','Large','Short'],'Large','CTET 2019',2019),
Q('primary','english','The antonym of "Beautiful" is-',['Ugly','Pretty','Lovely','Nice'],'Ugly','UPTET 2019',2019),
Q('primary','english','Identify the verb: "They are playing cricket."',['They','Are','Playing','Cricket'],'Playing','CTET 2022',2022),
Q('primary','english','The past tense of "Go" is-',['Goes','Gone','Went','Going'],'Went','UPTET 2022',2022),
Q('primary','english','Choose the correctly spelled word-',['Received','Recieved','Recived','Receved'],'Received','CTET 2023',2023),
Q('primary','english','"A piece of cake" means-',['To eat cake','Very easy','Difficult task','Expensive'],'Very easy','UPTET 2023',2023),
Q('junior','english','Identify the figure of speech: "The wind whispered."',['Simile','Metaphor','Personification','Hyperbole'],'Personification','CTET 2019',2019),
Q('junior','english','Identify the figure of speech: "Life is like a dream."',['Simile','Metaphor','Oxymoron','Onomatopoeia'],'Simile','UPTET 2019',2019),
Q('junior','english','Identify the figure of speech: "He is a lion in battle."',['Simile','Metaphor','Hyperbole','Pun'],'Metaphor','CTET 2020',2020),
Q('junior','english','The passive voice of "He wrote a letter" is-',['A letter is written by him','A letter was written by him','A letter was wrote by him','He has written a letter'],'A letter was written by him','UPTET 2020',2020),
Q('junior','english','The antonym of "Optimist" is-',['Pessimist','Theist','Atheist','Pacifist'],'Pessimist','CTET 2021',2021),
Q('junior','english','One who believes in God is a-',['Atheist','Theist','Optimist','Pessimist'],'Theist','UPTET 2021',2021),
Q('junior','english','Language Acquisition Device (LAD) was proposed by-',['Skinner','Piaget','Chomsky','Vygotsky'],'Chomsky','CTET 2022',2022),
Q('junior','english','The primary skills of language are-',['Reading and Writing','Listening and Speaking','Speaking and Writing','Reading and Listening'],'Listening and Speaking','UPTET 2022',2022),
Q('junior','english','Grammar-Translation Method focuses on-',['Speaking','Writing','Listening','Literary language and translation'],'Literary language and translation','CTET 2023',2023),
Q('junior','english','Direct Method is also known as-',['Natural Method','Translation Method','Bilingual Method','Grammar Method'],'Natural Method','UPTET 2023',2023),
Q('junior','english','The "Bilingual Method" was developed by-',['C.J. Dodson','Harold Palmer','Michael West','F.S. Gouin'],'C.J. Dodson','CTET 2018',2018),
Q('junior','english','Remedial teaching is for-',['Gifted students','Weak students','All students','Teachers'],'Weak students','UPTET 2018',2018),
Q('junior','english','Phonemes are-',['Meaningful units of sound','Units of meaning','Sentences','Grammar rules'],'Meaningful units of sound','CTET 2017',2017),
Q('junior','english','Morphemes are-',['Units of sound','Smallest meaningful units of language','Paragraphs','Grammar'],'Smallest meaningful units of language','UPTET 2017',2017),
];
