const { v4: uuidv4 } = require('uuid');
const Q = (l,s,t,o,a,src,yr) => ({question_id:uuidv4(),level:l,subject:s,question_text:t,options:o,correct_answer:a,source:src,year:yr,language:'english',created_at:new Date()});

module.exports = [
Q('primary','evs','The animals that eat both plants and meat are called-',['Herbivores','Carnivores','Omnivores','Decomposers'],'Omnivores','CTET 2011',2011),
Q('primary','evs','Which of the following is an example of a desert plant?',['Rose','Cactus','Lotus','Tulip'],'Cactus','UPTET 2012',2012),
Q('primary','evs','The "Silk" is obtained from which insect?',['Bee','Silkworm','Butterfly','Ant'],'Silkworm','CTET 2013',2013),
Q('primary','evs','Which of the following is a Rabi crop?',['Wheat','Rice','Maize','Cotton'],'Wheat','UPTET 2014',2014),
Q('primary','evs','The gas used by plants for photosynthesis is-',['Oxygen','Nitrogen','Carbon Dioxide','Argon'],'Carbon Dioxide','CTET 2015',2015),
Q('primary','evs','Which bird is known as the "National Bird of India"?',['Peacock','Sparrow','Pigeon','Crow'],'Peacock','UPTET 2016',2016),
Q('primary','evs','The largest state in India by area is-',['Uttar Pradesh','Maharashtra','Rajasthan','Madhya Pradesh'],'Rajasthan','CTET 2017',2017),
Q('primary','evs','Which of the following is a renewable source of energy?',['Coal','Petroleum','Solar','Natural Gas'],'Solar','UPTET 2018',2018),
Q('primary','evs','The main source of Vitamin C is-',['Milk','Orange','Apple','Potato'],'Orange','CTET 2019',2019),
Q('primary','evs','Which of the following is an air-borne disease?',['Typhoid','Cholera','Flu','Malaria'],'Flu','UPTET 2020',2020),
Q('primary','evs','The deepest point on Earth is-',['Mariana Trench','Dead Sea','Mount Everest','None'],'Mariana Trench','CTET 2021',2021),
Q('primary','evs','Which planet is known as the "Morning Star"?',['Venus','Mars','Jupiter','Saturn'],'Venus','UPTET 2021',2021),
Q('primary','evs','The process of water cycle includes-',['Evaporation','Condensation','Precipitation','All of these'],'All of these','CTET 2022',2022),
Q('primary','evs','Which of the following is a man-made fiber?',['Nylon','Wool','Silk','Cotton'],'Nylon','UPTET 2022',2022),
Q('primary','evs','The study of earth and its features is called-',['Geography','History','Biology','Physics'],'Geography','CTET 2023',2023),
Q('primary','evs','Which of the following is a rich source of Protein?',['Milk','Rice','Sugar','Oil'],'Milk','UPTET 2023',2023),
Q('primary','evs','The "Kaziranga National Park" is located in-',['Assam','Kerala','Gujarat','Rajasthan'],'Assam','CTET 2018',2018),
Q('primary','evs','Which of the following gas is necessary for burning?',['Oxygen','Nitrogen','Carbon Dioxide','Hydrogen'],'Oxygen','UPTET 2017',2017),
Q('primary','evs','The "Valley of Flowers" is located in-',['Kerala','Uttarakhand','Sikkim','Himachal Pradesh'],'Uttarakhand','CTET 2016',2016),
Q('primary','evs','Which of the following is a non-renewable source of energy?',['Wind','Solar','Petroleum','Water'],'Petroleum','UPTET 2015',2015),
Q('primary','evs','The main component of the atmosphere is-',['Oxygen','Nitrogen','Carbon Dioxide','Argon'],'Nitrogen','CTET 2014',2014),
Q('primary','evs','Which of the following is a mammal that can fly?',['Bird','Bat','Flying squirrel','None'],'Bat','UPTET 2013',2013),
Q('primary','evs','The deficiency of Vitamin D causes-',['Scurvy','Rickets','Goitre','Anaemia'],'Rickets','CTET 2012',2012),
Q('primary','evs','Which of the following is a warm-blooded animal?',['Snake','Fish','Dog','Frog'],'Dog','UPTET 2012',2012),
Q('primary','evs','The "Ozone Day" is celebrated on-',['5th June','16th Sept','22nd April','1st Dec'],'16th Sept','CTET 2011',2011),
Q('primary','evs','Which of the following is an artificial ecosystem?',['A forest','A field','A pond','A desert'],'A field','UPTET 2011',2011),
Q('primary','evs','The "Green Revolution" is related to-',['Milk','Agriculture','Fish','Cotton'],'Agriculture','CTET 2023',2023),
Q('primary','evs','Which of the following is a natural fiber?',['Nylon','Rayon','Silk','Polyester'],'Silk','UPTET 2020',2020),
Q('primary','evs','The main source of energy for the body is-',['Proteins','Vitamins','Carbohydrates','Minerals'],'Carbohydrates','CTET 2022',2022),
Q('primary','evs','Which of the following is an abiotic factor?',['Plants','Animals','Air','Fungi'],'Air','UPTET 2019',2019),
Q('primary','evs','The process of plants releasing water vapor is-',['Evaporation','Condensation','Transpiration','None'],'Transpiration','CTET 2021',2021),
Q('primary','evs','Which of the following is used to treat Malaria?',['Quinine','Penicillin','Aspirin','None'],'Quinine','UPTET 2018',2018),
Q('primary','evs','The "Chernobyl Disaster" was related to-',['Gas leak','Nuclear explosion','Flood','Earthquake'],'Nuclear explosion','CTET 2020',2020),
Q('primary','evs','Which of the following is a source of Vitamin A?',['Milk','Orange','Papaya','Potato'],'Papaya','UPTET 2017',2017),
Q('primary','evs','The "Brahmaputra" river originates from-',['Gangotri','Manasarovar Lake','Rohtang','None'],'Manasarovar Lake','CTET 2019',2019),
Q('primary','evs','Which of the following is a greenhouse gas?',['Oxygen','Nitrogen','Carbon Dioxide','Argon'],'Carbon Dioxide','UPTET 2016',2016),
Q('primary','evs','The "Narmada Bachao Andolan" was led by-',['Sunderlal Bahuguna','Medha Patkar','Baba Amte','None'],'Medha Patkar','CTET 2018',2018),
Q('primary','evs','Which of the following is a vector of Dengue?',['Anopheles Mosquito','Aedes Mosquito','Housefly','Cockroach'],'Aedes Mosquito','UPTET 2015',2015),
Q('primary','evs','The "World Water Day" is celebrated on-',['22nd March','5th June','22nd April','None'],'22nd March','CTET 2017',2017),
Q('primary','evs','Which of the following is a fossil fuel?',['Coal','Wood','Sunlight','Wind'],'Coal','UPTET 2014',2014),
Q('primary','evs','The "Troposphere" is the ___ layer of atmosphere.',['Lowest','Middle','Highest','None'],'Lowest','CTET 2016',2016),
Q('primary','evs','Which of the following is a non-biodegradable waste?',['Paper','Plastic','Food waste','Cloth'],'Plastic','UPTET 2013',2013),
Q('primary','evs','The study of birds is called-',['Ornithology','Botany','Zoology','None'],'Ornithology','CTET 2015',2015),
Q('primary','evs','Which of the following is a source of Vitamin B?',['Milk','Rice','Meat','All of these'],'All of these','UPTET 2012',2012),
Q('primary','evs','The "Project Elephant" was launched in-',['1973','1992','2000','None'],'1992','CTET 2014',2014),
Q('primary','evs','Which of the following is a carnivore?',['Lion','Deer','Rabbit','Sheep'],'Lion','UPTET 2011',2011),
Q('primary','evs','The layer of the atmosphere where satellites orbit is-',['Exosphere','Troposphere','Stratosphere','None'],'Exosphere','CTET 2013',2013),
Q('primary','evs','Which of the following is a pollutant?',['Oxygen','Carbon Monoxide','Nitrogen','Argon'],'Carbon Monoxide','UPTET 2023',2023),
Q('primary','evs','The main source of light for Earth is-',['Moon','Sun','Stars','Lamp'],'Sun','CTET 2012',2012),
Q('primary','evs','How many legs does an insect have?',['4','6','8','None'],'6','UPTET 2010',2010),
];
