const { v4: uuidv4 } = require('uuid');
const Q = (l,s,t,o,a,src,yr) => ({question_id:uuidv4(),level:l,subject:s,question_text:t,options:o,correct_answer:a,source:src,year:yr,language:'english',created_at:new Date()});

module.exports = [
Q('primary','pedagogy','According to Vygotsky, the distance between actual development and potential development is-',['Scaffolding','ZPD','MKO','None'],'ZPD','CTET 2018',2018),
Q('primary','pedagogy','The concept of "Mental Hygiene" was given by-',['C.W. Beers','Binet','Watson','None'],'C.W. Beers','UPTET 2017',2017),
Q('primary','pedagogy','Which of the following is a "Cognitive Developmental Theory" besides Piaget\'s?',['Bruner\'s','Skinner\'s','Pavlov\'s','None'],'Bruner\'s','CTET 2019',2019),
Q('primary','pedagogy','Who gave the "Theory of Psychosocial Development"?',['Freud','Erikson','Piaget','None'],'Erikson','UPTET 2016',2016),
Q('primary','pedagogy','In an inclusive classroom, a teacher should use-',['Standardized instruction','Flexible grouping','Labeling children','None'],'Flexible grouping','CTET 2021',2021),
Q('primary','pedagogy','The stage of "Generativity vs Stagnation" occurs during-',['Adolescence','Young Adulthood','Middle Adulthood','Old Age'],'Middle Adulthood','CTET 2022',2022),
Q('primary','pedagogy','Which of the following is a principle of learning?',['Activity','Interest','Repetition','All of these'],'All of these','UPTET 2018',2018),
Q('primary','pedagogy','The "Micro-teaching" technique was first developed at-',['Stanford University','Harvard University','Oxford University','None'],'Stanford University','CTET 2020',2020),
Q('primary','pedagogy','According to Piaget, "Assimilation" means-',['Changing existing schemas','Fitting new info into existing schemas','Creating new schemas','None'],'Fitting new info into existing schemas','CTET 2019',2019),
Q('primary','pedagogy','The "Dalton Plan" was developed by-',['Helen Parkhurst','Dewey','Kilpatrick','Froebel'],'Helen Parkhurst','UPTET 2021',2021),
Q('primary','pedagogy','Which of the following is a "Technique of Motivation"?',['Reward and Punishment','Competition','Knowledge of results','All of these'],'All of these','CTET 2022',2022),
Q('primary','pedagogy','The term "Aptitude" refers to-',['Existing knowledge','Potential to learn a specific skill','General intelligence','None'],'Potential to learn a specific skill','CTET 2023',2023),
Q('primary','pedagogy','Who gave the "Two-Factor Theory of Intelligence"?',['Spearman','Thurstone','Thorndike','None'],'Spearman','UPTET 2020',2020),
Q('primary','pedagogy','Which of the following is a "Graphic Aid"?',['Radio','Chart','Television','Model'],'Chart','CTET 2017',2017),
Q('primary','pedagogy','The "Cognitive Approach" emphasizes-',['S-R connection','Mental processes','Physical growth','None'],'Mental processes','CTET 2016',2016),
Q('primary','pedagogy','What is the purpose of "Remedial Teaching"?',['To teach new syllabus','To fix learning gaps','To test students','To punish students'],'To fix learning gaps','UPTET 2019',2019),
Q('primary','pedagogy','Which of the following is an "Intrinsic Motive"?',['Praise','Curiosity','Grades','Money'],'Curiosity','CTET 2015',2015),
Q('primary','pedagogy','The term "Socialization" means-',['Making friends','Adapting to social norms','Fighting with others','None'],'Adapting to social norms','CTET 2014',2014),
Q('primary','pedagogy','Which of the following is a characteristic of "Formal Operational Stage"?',['Hypothetico-deductive reasoning','Animism','Object permanence','None'],'Hypothetico-deductive reasoning','CTET 2013',2013),
Q('primary','pedagogy','The "Right to Education" became a fundamental right under which article?',['21A','19','45','None'],'21A','CTET 2012',2012),
Q('primary','pedagogy','Who developed the "Social Cognitive Theory"?',['Bandura','Piaget','Vygotsky','None'],'Bandura','CTET 2011',2011),
Q('primary','pedagogy','Which of the following is a "Principle of Maturation"?',['It depends on learning','It is a biological process','It is a social process','None'],'It is a biological process','UPTET 2012',2012),
Q('primary','pedagogy','The "Play-way Method" is most effective for-',['Primary education','Secondary education','Higher education','None'],'Primary education','UPTET 2011',2011),
Q('primary','pedagogy','Learning is influenced by-',['Emotional factors','Social factors','Cognitive factors','All of these'],'All of these','CTET 2023',2023),
Q('primary','pedagogy','The "Father of Genetic Epistemology" is-',['Piaget','Vygotsky','Bruner','None'],'Piaget','UPTET 2023',2023),
Q('primary','pedagogy','Which of the following is a "Type of Thinking"?',['Logical','Creative','Critical','All of these'],'All of these','CTET 2022',2022),
Q('primary','pedagogy','The "Inclusive Education" model was first applied in-',['Schools for disabled','Regular schools','Special schools','None'],'Regular schools','CTET 2021',2021),
Q('primary','pedagogy','Who gave the "Law of Multiple Response"?',['Thorndike','Skinner','Pavlov','None'],'Thorndike','UPTET 2022',2022),
Q('primary','pedagogy','Which of the following is a "Projective Test of Personality"?',['SCT (Sentence Completion Test)','I.Q. Test','Achievement Test','None'],'SCT (Sentence Completion Test)','CTET 2020',2020),
Q('primary','pedagogy','The "Concept of Scaffolding" was given by-',['Bruner','Vygotsky','Piaget','None'],'Bruner','UPTET 2021',2021),
Q('primary','pedagogy','Which of the following is an "Affective Process"?',['Thinking','Feeling','Walking','Breathing'],'Feeling','CTET 2019',2019),
Q('primary','pedagogy','The "Resource Teacher" is responsible for-',['Special needs children','School management','Teaching only science','None'],'Special needs children','UPTET 2020',2020),
Q('primary','pedagogy','Which of the following is a "Probability Sampling" method?',['Purposive','Convenience','Simple random','Quota'],'Simple random','CTET 2018',2018),
Q('primary','pedagogy','The term "Zone of Proximal Development" was used by-',['Vygotsky','Piaget','Bruner','None'],'Vygotsky','UPTET 2017',2017),
Q('primary','pedagogy','Which of the following is a "Teacher-centered" method?',['Lecture','Demonstration','Lecture-demonstration','All of these'],'All of these','CTET 2017',2017),
Q('primary','pedagogy','The "Connectionism Theory" was given by-',['Thorndike','Pavlov','Skinner','None'],'Thorndike','UPTET 2016',2016),
Q('primary','pedagogy','Which of the following is a "Qualitative Assessment"?',['Observation','Interview','Rating scale','All of these'],'All of these','CTET 2016',2016),
Q('primary','pedagogy','The "Primary Agency of Socialization" is-',['Family','School','Media','None'],'Family','UPTET 2015',2015),
Q('primary','pedagogy','Which of the following is a "Acquired Motive"?',['Hunger','Thirst','Achievement','Sleep'],'Achievement','CTET 2015',2015),
Q('primary','pedagogy','The "Law of Primacy" means-',['First things learned are best remembered','Last things are best','None','Both'],'First things learned are best remembered','UPTET 2014',2014),
Q('primary','pedagogy','Which of the following is an "Activity Aid"?',['Field trips','Radio','Tape recorder','Charts'],'Field trips','CTET 2014',2014),
Q('primary','pedagogy','The "Global Plan" of education was given by-',['Dewey','Froebel','None','Washburne'],'Washburne','UPTET 2013',2013),
Q('primary','pedagogy','Which of the following is a "Psychomotor Domain" level?',['Imitation','Precision','Articulation','All of these'],'All of these','CTET 2013',2013),
Q('primary','pedagogy','The "Concept of Introversion and Extroversion" was given by-',['Jung','Freud','Adler','None'],'Jung','UPTET 2012',2012),
Q('primary','pedagogy','Which of the following is a "Negative Reinforcer"?',['Removal of a painful stimulus','Giving a candy','Praise','None'],'Removal of a painful stimulus','CTET 2012',2012),
Q('primary','pedagogy','The "Group Factor Theory of Intelligence" was given by-',['Thurstone','Spearman','Gardner','None'],'Thurstone','UPTET 2011',2011),
Q('primary','pedagogy','Which of the following is an "Assessment of Learning"?',['Summative','Formative','Diagnostic','None'],'Summative','CTET 2011',2011),
Q('primary','pedagogy','The "Pragmatism" philosophy in education emphasizes-',['Ideas','Utility and experience','Nature','None'],'Utility and experience','UPTET 2023',2023),
Q('primary','pedagogy','Which of the following is a "Test of Interest"?',['Strong Vocational Interest Blank','I.Q. Test','Achievement Test','None'],'Strong Vocational Interest Blank','CTET 2023',2023),
Q('primary','pedagogy','The "Concept of Micro-teaching" was given by-',['Dwight Allen','Froebel','Dewey','None'],'Dwight Allen','UPTET 2022',2022),
];
