const { v4: uuidv4 } = require('uuid');
const Q = (l,s,t,o,a,src,yr) => ({question_id:uuidv4(),level:l,subject:s,question_text:t,options:o,correct_answer:a,source:src,year:yr,language:'english',created_at:new Date()});

module.exports = [
Q('primary','pedagogy','According to Bandura, most human behavior is learned through-',['Classical conditioning','Operant conditioning','Observational learning','Trial and error'],'Observational learning','CTET 2018',2018),
Q('primary','pedagogy','The concept of "IQ" was first calculated by-',['Binet','Stern','Terman','Spearman'],'Terman','UPTET 2017',2017),
Q('primary','pedagogy','Which of the following is an example of a "Fine Motor Skill"?',['Writing','Swimming','Running','Jumping'],'Writing','CTET 2019',2019),
Q('primary','pedagogy','Who gave the "Hierarchical Theory of Needs"?',['Freud','Maslow','Skinner','Pavlov'],'Maslow','UPTET 2016',2016),
Q('primary','pedagogy','In an inclusive classroom, emphasis should be on-',['Performance oriented goals','Undifferentiated instruction','Providing opportunities for every child to reach their potential','Segregation of children'],'Providing opportunities for every child to reach their potential','CTET 2021',2021),
Q('primary','pedagogy','The stage of "Identity vs Role Confusion" occurs during-',['Infancy','Childhood','Adolescence','Adulthood'],'Adolescence','CTET 2022',2022),
Q('primary','pedagogy','Which of the following is a primary law of learning?',['Law of Readiness','Law of Multiple Response','Law of Analogy','Law of Partial Activity'],'Law of Readiness','UPTET 2018',2018),
Q('primary','pedagogy','The "Project Method" of teaching was developed by-',['Dewey','Kilpatrick','Froebel','Montessori'],'Kilpatrick','CTET 2020',2020),
Q('primary','pedagogy','According to Piaget, "Schema" is-',['A physical action','A mental organization of information','A sensory organ','A biological trait'],'A mental organization of information','CTET 2019',2019),
Q('primary','pedagogy','The full form of ADHD is-',['Attention Deficit Hyperactivity Disorder','Active Deficit High Disorder','Attention Disorder High Disease','None'],'Attention Deficit Hyperactivity Disorder','UPTET 2021',2021),
Q('primary','pedagogy','Which of the following is a type of "Divergent Thinking"?',['Rote memorization','Problem solving with multiple solutions','Matching words','Choosing one correct answer'],'Problem solving with multiple solutions','CTET 2022',2022),
Q('primary','pedagogy','The "Zone of Proximal Development" refers to-',['The distance between what a child can do alone and with help','The area where a child cannot learn','The physical space of a classroom','The time taken to learn a task'],'The distance between what a child can do alone and with help','CTET 2023',2023),
Q('primary','pedagogy','Who is known for the "Theory of Insightful Learning"?',['Kohler','Thorndike','Pavlov','Skinner'],'Kohler','UPTET 2020',2020),
Q('primary','pedagogy','Which of the following is a "Visual Aid"?',['Radio','Tape recorder','Globe','Language lab'],'Globe','CTET 2017',2017),
Q('primary','pedagogy','The "Constructivist Approach" suggests that-',['Learner is passive','Learner actively constructs knowledge','Teacher is the only source of knowledge','Learning is memorization'],'Learner actively constructs knowledge','CTET 2016',2016),
Q('primary','pedagogy','What is the role of a teacher in a child-centered classroom?',['Dictator','Facilitator','Evaluator','Silent observer'],'Facilitator','UPTET 2019',2019),
Q('primary','pedagogy','Which of the following is an "Intrinsic Reward"?',['Money','Praise','Sense of achievement','A certificate'],'Sense of achievement','CTET 2015',2015),
Q('primary','pedagogy','The term "Nature" in "Nature vs Nurture" refers to-',['Environment','Heredity','Society','School'],'Heredity','CTET 2014',2014),
Q('primary','pedagogy','Which of the following is a characteristic of "Formal Operational Stage"?',['Ego-centrism','Object permanence','Abstract thinking','Animism'],'Abstract thinking','CTET 2013',2013),
Q('primary','pedagogy','The "RTE Act 2009" ensures education for children aged-',['3-6 years','6-14 years','6-18 years','None'],'6-14 years','CTET 2012',2012),
Q('primary','pedagogy','Who developed the "Social Development Theory"?',['Piaget','Vygotsky','Bandura','Chomsky'],'Vygotsky','CTET 2011',2011),
Q('primary','pedagogy','Which of the following is a "Secondary Law of Learning"?',['Law of Primacy','Law of Effect','Law of Readiness','Law of Exercise'],'Law of Primacy','UPTET 2012',2012),
Q('primary','pedagogy','The "Heuristic Method" was given by-',['Armstrong','Dewey','Kilpatrick','None'],'Armstrong','UPTET 2011',2011),
Q('primary','pedagogy','Learning is most effective when it is-',['Teacher directed','Student centered','Textbook based','Exam oriented'],'Student centered','CTET 2023',2023),
Q('primary','pedagogy','The "IQ" formula is-',['MA/CA * 100','CA/MA * 100','MA * CA / 100','None'],'MA/CA * 100','UPTET 2023',2023),
Q('primary','pedagogy','Which of the following is a barrier to communication?',['Clarity','Active listening','Noise','Feedback'],'Noise','CTET 2022',2022),
Q('primary','pedagogy','The "Scaffolding" technique is best used for-',['Advanced learners','Beginners or struggling learners','Only gifted children','Adults only'],'Beginners or struggling learners','CTET 2021',2021),
Q('primary','pedagogy','Who is the father of "Micro-teaching"?',['Dwight Allen','Froebel','Dewey','None'],'Dwight Allen','UPTET 2022',2022),
Q('primary','pedagogy','Which of the following is a "Projective Technique"?',['Interview','Questionnaire','Rorschach Inkblot Test','Case study'],'Rorschach Inkblot Test','CTET 2020',2020),
Q('primary','pedagogy','The "Concept of Universal Grammar" was given by-',['Piaget','Skinner','Chomsky','Vygotsky'],'Chomsky','UPTET 2021',2021),
Q('primary','pedagogy','Which of the following is a "Cognitive Process"?',['Walking','Thinking','Digesting','Breathing'],'Thinking','CTET 2019',2019),
Q('primary','pedagogy','The "Case Study Method" is used for-',['Generalizing behavior','Understanding specific problems of a child','Comparing two groups','Large surveys'],'Understanding specific problems of a child','UPTET 2020',2020),
Q('primary','pedagogy','Which of the following is NOT a type of "Reliability"?',['Test-retest','Split-half','Content validity','Parallel forms'],'Content validity','CTET 2018',2018),
Q('primary','pedagogy','The term "Tabula Rasa" means-',['Blank slate','Intelligent mind','Emotional being','Social animal'],'Blank slate','UPTET 2017',2017),
Q('primary','pedagogy','Which of the following is a "Cooperative Learning" strategy?',['Lecture','Jigsaw','Competition','Rote learning'],'Jigsaw','CTET 2017',2017),
Q('primary','pedagogy','The "Trial and Error Theory" is also known as-',['Classical conditioning','Connectionism','Gestalt theory','Social learning'],'Connectionism','UPTET 2016',2016),
Q('primary','pedagogy','Which of the following is an "Objective Type Question"?',['Essay','Short answer','Multiple choice','None'],'Multiple choice','CTET 2016',2016),
Q('primary','pedagogy','The "Main Source of Knowledge" for a child is-',['Teacher','Parents','Environment','All of these'],'All of these','UPTET 2015',2015),
Q('primary','pedagogy','Which of the following is a "Social Motive"?',['Hunger','Thirst','Achievement','Sleep'],'Achievement','CTET 2015',2015),
Q('primary','pedagogy','The "Laws of Heredity" were given by-',['Mendel','Darwin','Lamarck','None'],'Mendel','UPTET 2014',2014),
Q('primary','pedagogy','Which of the following is a "Non-projected Aid"?',['Filmstrips','Slide projector','Blackboard','Overhead projector'],'Blackboard','CTET 2014',2014),
Q('primary','pedagogy','The "Dalton Plan" of education was given by-',['Helen Parkhurst','Dewey','Froebel','None'],'Helen Parkhurst','UPTET 2013',2013),
Q('primary','pedagogy','Which of the following is a "Psychomotor Activity"?',['Thinking','Feeling','Typing','Remembering'],'Typing','CTET 2013',2013),
Q('primary','pedagogy','The "Concept of Empathy" means-',['Feeling sorry for others','Understanding others\' feelings from their perspective','Ignoring others','Judging others'],'Understanding others\' feelings from their perspective','UPTET 2012',2012),
Q('primary','pedagogy','Which of the following is a "Reinforcement Schedule"?',['Fixed ratio','Variable interval','Continuous','All of these'],'All of these','CTET 2012',2012),
Q('primary','pedagogy','The "Stages of Psychosexual Development" were given by-',['Erikson','Piaget','Freud','Adler'],'Freud','UPTET 2011',2011),
Q('primary','pedagogy','Which of the following is a "Form of Assessment"?',['Peer assessment','Self assessment','Teacher assessment','All of these'],'All of these','CTET 2011',2011),
Q('primary','pedagogy','The "Idealism" philosophy in education emphasizes-',['Practicality','Values and ideas','Science','Social interaction'],'Values and ideas','UPTET 2023',2023),
Q('primary','pedagogy','Which of the following is a "Method of Personality Assessment"?',['T.A.T.','I.Q. Test','Achievement Test','None'],'T.A.T.','CTET 2023',2023),
Q('primary','pedagogy','The "Concept of Inclusive Education" was first popularized in-',['Salamanca Statement','World Bank Report','NEP 2020','None'],'Salamanca Statement','UPTET 2022',2022),
];
