const { v4: uuidv4 } = require('uuid');
const Q = (l,s,t,o,a,src,yr) => ({question_id:uuidv4(),level:l,subject:s,question_text:t,options:o,correct_answer:a,source:src,year:yr,language:'english',created_at:new Date()});

module.exports = [
Q('primary','evs','Which of the following is a biotic component of the environment?',['Air','Water','Plants','Soil'],'Plants','CTET 2011',2011),
Q('primary','evs','The main source of energy on Earth is-',['Moon','Sun','Stars','Fire'],'Sun','UPTET 2012',2012),
Q('primary','evs','World Environment Day is celebrated on-',['5th June','22nd April','16th September','11th July'],'5th June','CTET 2013',2013),
Q('primary','evs','The Ozone layer protects us from-',['Infrared rays','Ultraviolet rays','X-rays','Gamma rays'],'Ultraviolet rays','UPTET 2014',2014),
Q('primary','evs','Which gas is most abundant in the Earth\'s atmosphere?',['Oxygen','Nitrogen','Carbon Dioxide','Argon'],'Nitrogen','CTET 2015',2015),
Q('primary','evs','CNG stands for-',['Compressed Natural Gas','Common Natural Gas','Certified Natural Gas','None'],'Compressed Natural Gas','UPTET 2016',2016),
Q('primary','evs','The main cause of Global Warming is-',['Increase in Nitrogen','Increase in Oxygen','Increase in Carbon Dioxide','Increase in Argon'],'Increase in Carbon Dioxide','CTET 2017',2017),
Q('primary','evs','Which of the following is a renewable source of energy?',['Coal','Petroleum','Solar Energy','Natural Gas'],'Solar Energy','UPTET 2018',2018),
Q('primary','evs','Chipko Movement was started by-',['Medha Patkar','Sunderlal Bahuguna','Baba Amte','M.S. Swaminathan'],'Sunderlal Bahuguna','CTET 2019',2019),
Q('primary','evs','The process of turning water vapor into water is called-',['Evaporation','Condensation','Precipitation','Transpiration'],'Condensation','UPTET 2020',2020),
Q('primary','evs','Which of the following is an example of an ecosystem?',['Pond','Desert','Forest','All of these'],'All of these','CTET 2021',2021),
Q('primary','evs','The "Greenhouse Effect" is related to-',['Soil pollution','Air pollution','Water pollution','Noise pollution'],'Air pollution','UPTET 2021',2021),
Q('primary','evs','Plants take in carbon dioxide and release-',['Nitrogen','Oxygen','Hydrogen','Helium'],'Oxygen','CTET 2022',2022),
Q('primary','evs','The study of the relationship between organisms and their environment is called-',['Biology','Ecology','Geology','Zoology'],'Ecology','UPTET 2022',2022),
Q('primary','evs','Which state in India is known as the "Tiger State"?',['Gujarat','Rajasthan','Madhya Pradesh','Uttarakhand'],'Madhya Pradesh','CTET 2023',2023),
Q('primary','evs','The Chipko Movement is related to the protection of-',['Tigers','Trees','Rivers','Birds'],'Trees','UPTET 2023',2023),
Q('primary','evs','Acid rain is primarily caused by-',['Sulfur dioxide and Nitrogen oxides','Carbon monoxide','Methane','Carbon dioxide'],'Sulfur dioxide and Nitrogen oxides','CTET 2018',2018),
Q('primary','evs','Which of the following is NOT a fossil fuel?',['Coal','Petroleum','Wood','Natural Gas'],'Wood','UPTET 2017',2017),
Q('primary','evs','The unit of measuring the intensity of noise is-',['Decibel','Hertz','Watt','Pascal'],'Decibel','CTET 2016',2016),
Q('primary','evs','The "Kyoto Protocol" is an international agreement to-',['Reduce greenhouse gas emissions','Protect endangered species','Conserve water','Promote organic farming'],'Reduce greenhouse gas emissions','UPTET 2015',2015),
Q('primary','evs','Which of the following is a producer in a food chain?',['Lion','Snake','Grass','Eagle'],'Grass','CTET 2014',2014),
Q('primary','evs','The primary source of water on land is-',['Rivers','Lakes','Rain','Groundwater'],'Rain','UPTET 2013',2013),
Q('primary','evs','Which vitamin is synthesized in our body in the presence of sunlight?',['Vitamin A','Vitamin B','Vitamin C','Vitamin D'],'Vitamin D','CTET 2012',2012),
Q('primary','evs','The Red Data Book contains information about-',['Red colored plants','Endangered species','Rivers with high pollution','Active volcanoes'],'Endangered species','UPTET 2012',2012),
Q('primary','evs','Which of the following is a flightless bird?',['Ostrich','Peacock','Sparrow','Crow'],'Ostrich','CTET 2011',2011),
Q('primary','evs','The main source of Vitamin C is-',['Milk','Apple','Orange','Bread'],'Orange','UPTET 2011',2011),
Q('primary','evs','Photosynthesis occurs in-',['Roots','Stems','Leaves','Flowers'],'Leaves','CTET 2023',2023),
Q('primary','evs','Which of the following is a man-made disaster?',['Earthquake','Flood','Tsunami','Nuclear explosion'],'Nuclear explosion','UPTET 2020',2020),
Q('primary','evs','The percentage of Oxygen in the air is approximately-',['78%','21%','1%','0.03%'],'21%','CTET 2022',2022),
Q('primary','evs','The highest peak in India is-',['Mount Everest','Kanchenjunga','Nanda Devi','K2 (Mount Godwin-Austen)'],'K2 (Mount Godwin-Austen)','UPTET 2019',2019),
Q('primary','evs','Which planet is known as the "Red Planet"?',['Venus','Mars','Jupiter','Saturn'],'Mars','CTET 2021',2021),
Q('primary','evs','The longest river in India is-',['Yamuna','Ganga','Brahmaputra','Godavari'],'Ganga','UPTET 2018',2018),
Q('primary','evs','Which of the following is a primary consumer?',['Lion','Snake','Deer','Vulture'],'Deer','CTET 2020',2020),
Q('primary','evs','The "Bhopal Gas Tragedy" was caused by the leakage of-',['Methyl Isocyanate','Carbon Monoxide','Nitrous Oxide','Methane'],'Methyl Isocyanate','UPTET 2017',2017),
Q('primary','evs','Which of the following is a water-borne disease?',['Flu','Typhoid','Malaria','Asthma'],'Typhoid','CTET 2019',2019),
Q('primary','evs','The main objective of EVS at the primary level is to-',['Make students experts in science','Develop environmental awareness and sensitivity','Teach complex ecological theories','Prepare for engineering'],'Develop environmental awareness and sensitivity','CTET 2016',2016),
Q('primary','evs','Which of the following is a decomposer?',['Fungi','Green plants','Rabbit','Tiger'],'Fungi','UPTET 2022',2022),
Q('primary','evs','The "Silent Valley" National Park is located in-',['Tamil Nadu','Kerala','Karnataka','Andhra Pradesh'],'Kerala','CTET 2015',2015),
Q('primary','evs','Which of the following is NOT a greenhouse gas?',['Methane','Carbon dioxide','Nitrogen','Water vapor'],'Nitrogen','UPTET 2021',2021),
Q('primary','evs','The layer of the atmosphere where weather phenomena occur is-',['Stratosphere','Troposphere','Mesosphere','Thermosphere'],'Troposphere','CTET 2014',2014),
Q('primary','evs','Which of the following is a bio-degradable waste?',['Plastic bottles','Glass pieces','Paper','Aluminum cans'],'Paper','UPTET 2014',2014),
Q('primary','evs','The energy flow in an ecosystem is-',['Unidirectional','Bidirectional','Multidirectional','Cyclic'],'Unidirectional','CTET 2013',2013),
Q('primary','evs','Which of the following is a pollinator?',['Bee','Wind','Water','All of these'],'All of these','UPTET 2013',2013),
Q('primary','evs','The concentration of which gas is increasing due to deforestation?',['Oxygen','Carbon dioxide','Nitrogen','Hydrogen'],'Carbon dioxide','CTET 2012',2012),
Q('primary','evs','Which of the following is an example of an aquatic ecosystem?',['Desert','Grassland','Ocean','Forest'],'Ocean','UPTET 2012',2012),
Q('primary','evs','The standard for measuring the purity of gold is-',['Metre','Litre','Carat','Gram'],'Carat','CTET 2011',2011),
Q('primary','evs','Which of the following is a non-metal?',['Iron','Copper','Oxygen','Gold'],'Oxygen','UPTET 2011',2011),
Q('primary','evs','The source of energy in a food chain is-',['Producers','Consumers','Decomposers','Sun'],'Sun','CTET 2022',2022),
Q('primary','evs','Which of the following is a medicinal plant?',['Neem','Babul','Rose','Cactus'],'Neem','UPTET 2023',2023),
Q('primary','evs','The "Project Tiger" was launched in India in the year-',['1971','1973','1975','1980'],'1973','CTET 2020',2020),
];
