const { v4: uuidv4 } = require('uuid');
const Q = (l,s,t,o,a,src,yr) => ({question_id:uuidv4(),level:l,subject:s,question_text:t,options:o,correct_answer:a,source:src,year:yr,language:'english',created_at:new Date()});

module.exports = [
Q('junior','science','The chemical formula for Vinegar is-',['CH3COOH','HCl','H2SO4','NaOH'],'CH3COOH','CTET 2011',2011),
Q('junior','science','Which of the following is a physical change?',['Rusting of iron','Melting of wax','Cooking of food','Burning of paper'],'Melting of wax','UPTET 2012',2012),
Q('junior','science','The unit of frequency is-',['Joule','Watt','Hertz','Pascal'],'Hertz','CTET 2013',2013),
Q('junior','science','Which of the following is a source of carbohydrates?',['Rice','Milk','Meat','Egg'],'Rice','UPTET 2014',2014),
Q('junior','science','The process of transition from solid to gas directly is called-',['Sublimation','Evaporation','Melting','Boiling'],'Sublimation','CTET 2015',2015),
Q('junior','science','Which of the following is a good conductor of heat?',['Iron','Wood','Plastic','Glass'],'Iron','UPTET 2016',2016),
Q('junior','science','The instrument used to measure the intensity of light is-',['Photometer','Barometer','Hygrometer','Anemometer'],'Photometer','CTET 2017',2017),
Q('junior','science','Which of the following is a weak acid?',['Hydrochloric acid','Acetic acid','Sulfuric acid','Nitric acid'],'Acetic acid','UPTET 2018',2018),
Q('junior','science','The SI unit of force is-',['Newton','Watt','Joule','Pascal'],'Newton','CTET 2019',2019),
Q('junior','science','Which organ is responsible for sound production in humans?',['Larynx','Pharynx','Trachea','Lungs'],'Larynx','UPTET 2020',2020),
Q('junior','science','The part of the plant that helps in pollination is-',['Root','Stem','Flower','Leaf'],'Flower','CTET 2021',2021),
Q('junior','science','Which of the following is an exhaustible resource?',['Coal','Solar energy','Wind energy','Water'],'Coal','UPTET 2021',2021),
Q('junior','science','The total number of ribs in human body is-',['12 pairs','14 pairs','10 pairs','None'],'12 pairs','CTET 2022',2022),
Q('junior','science','Which of the following is a metal that is solid at room temperature?',['Mercury','Gold','Bromine','None'],'Gold','UPTET 2022',2022),
Q('junior','science','The study of heredity and variation is called-',['Biology','Botany','Genetics','Ecology'],'Genetics','CTET 2023',2023),
Q('junior','science','Which gas is consumed during combustion?',['Oxygen','Carbon dioxide','Nitrogen','Hydrogen'],'Oxygen','UPTET 2023',2023),
Q('junior','science','Which of the following is an alkali?',['NaOH','HCl','H2SO4','None'],'NaOH','CTET 2018',2018),
Q('junior','science','The pH value of an acidic solution is-',['Less than 7','Exactly 7','Greater than 7','14'],'Less than 7','UPTET 2017',2017),
Q('junior','science','Which of the following is a non-metal?',['Carbon','Iron','Gold','Silver'],'Carbon','CTET 2016',2016),
Q('junior','science','The phenomenon of light bouncing back from a surface is-',['Reflection','Refraction','Dispersion','Diffraction'],'Reflection','UPTET 2015',2015),
Q('junior','science','Which of the following is a natural fiber?',['Nylon','Rayon','Silk','None'],'Silk','CTET 2014',2014),
Q('junior','science','The acid found in curd is-',['Formic acid','Lactic acid','Citric acid','Acetic acid'],'Lactic acid','UPTET 2013',2013),
Q('junior','science','The coldest planet in the solar system is-',['Uranus','Neptune','Earth','Mars'],'Neptune','CTET 2012',2012),
Q('junior','science','Which of the following is a warm-blooded animal?',['Lizard','Bird','Snake','Fish'],'Bird','UPTET 2012',2012),
Q('junior','science','The brain of the cell is-',['Mitochondria','Ribosome','Nucleus','Lysosome'],'Nucleus','CTET 2011',2011),
Q('junior','science','Which of the following is an insulator?',['Silver','Glass','Copper','Aluminum'],'Glass','UPTET 2011',2011),
Q('junior','science','The instrument used to measure wind speed is-',['Thermometer','Barometer','Anemometer','Hygrometer'],'Anemometer','CTET 2023',2023),
Q('junior','science','Which of the following is a carbohydrate?',['Glucose','Keratin','Proteins','Fats'],'Glucose','UPTET 2020',2020),
Q('junior','science','The deficiency of Vitamin C causes-',['Scurvy','Rickets','Beriberi','Anaemia'],'Scurvy','CTET 2022',2022),
Q('junior','science','Which of the following is an omnivore?',['Lion','Bear','Deer','Rabbit'],'Bear','UPTET 2019',2019),
Q('junior','science','The boiling point of water in Celsius is-',['0°C','50°C','100°C','None'],'100°C','CTET 2021',2021),
Q('junior','science','Which of the following is a source of Vitamin A?',['Carrot','Meat','Egg','All of these'],'All of these','UPTET 2018',2018),
Q('junior','science','The process of separating solid from liquid by spinning is-',['Centrifugation','Filtration','Evaporation','Decantation'],'Centrifugation','CTET 2020',2020),
Q('junior','science','Which of the following is a chemical property?',['Boiling point','Flammability','Density','Color'],'Flammability','UPTET 2017',2017),
Q('junior','science','The value of gravity on Moon is ___ of Earth\'s gravity.',['1/2','1/4','1/6','None'],'1/6','CTET 2019',2019),
Q('junior','science','Which of the following is the protective part of a flower bud?',['Stamen','Pistil','Petal','Sepal'],'Sepal','CTET 2016',2016),
Q('junior','science','Which of the following is a magnetic material?',['Nickel','Paper','Wood','Plastic'],'Nickel','UPTET 2022',2022),
Q('junior','science','The pH value of an alkaline solution is-',['Less than 7','Exactly 7','Greater than 7','0'],'Greater than 7','CTET 2015',2015),
Q('junior','science','Which of the following is a secondary consumer?',['Snake','Grasshopper','Rabbit','Cow'],'Snake','UPTET 2021',2021),
Q('junior','science','The part of the eye that contains light-sensitive cells is-',['Cornea','Iris','Retina','Lens'],'Retina','CTET 2014',2014),
Q('junior','science','Which of the following is not a noble gas?',['Helium','Nitrogen','Neon','Argon'],'Nitrogen','UPTET 2014',2014),
Q('junior','science','The process of transition from liquid to gas is-',['Melting','Boiling','Sublimation','Condensation'],'Boiling','CTET 2013',2013),
Q('junior','science','Which of the following is an example of commensalism?',['Orchid on a tree','Parasitism','Predation','Competition'],'Orchid on a tree','UPTET 2013',2013),
Q('junior','science','The chemical symbol for Gold is-',['Go','Au','Ag','Fe'],'Au','CTET 2012',2012),
Q('junior','science','Which of the following is a cold-blooded animal?',['Frog','Human','Dog','Whale'],'Frog','UPTET 2012',2012),
Q('junior','science','The freezing point of water in Celsius is-',['0°C','32°C','100°C','None'],'0°C','CTET 2011',2011),
Q('junior','science','Which of the following is a metal?',['Carbon','Sulfur','Oxygen','Iron'],'Iron','UPTET 2023',2023),
Q('junior','science','Which of the following is a biotic component?',['Light','Plants','Water','Air'],'Plants','CTET 2020',2020),
Q('junior','science','The unit of speed is-',['m/s','m/s²','Newton','Joule'],'m/s','UPTET 2011',2011),
Q('junior','science','Which of the following is a simple machine?',['Pulley','Wedge','Inclined plane','All of these'],'All of these','CTET 2022',2022),
];
