const { v4: uuidv4 } = require('uuid');
const Q = (l,s,t,o,a,src,yr) => ({question_id:uuidv4(),level:l,subject:s,question_text:t,options:o,correct_answer:a,source:src,year:yr,created_at:new Date()});
module.exports = [
Q('primary','english','A collective noun is-',['Name of a person','Name of a group','Name of a place','Name of a thing'],'Name of a group','CTET 2019',2019),
Q('primary','english','The comparative degree of "good" is-',['Gooder','Best','Better','More good'],'Better','UPTET 2019',2019),
Q('primary','english','Which is an abstract noun?',['Table','Honesty','Dog','River'],'Honesty','CTET 2020',2020),
Q('primary','english','Identify the conjunction: "He is poor but honest."',['He','Poor','But','Honest'],'But','UPTET 2020',2020),
Q('primary','english','The superlative degree of "beautiful" is-',['More beautiful','Beautifulest','Most beautiful','Beautifuller'],'Most beautiful','CTET 2021',2021),
Q('primary','english','An interjection expresses-',['Action','Sudden feeling','Naming','Describing'],'Sudden feeling','UPTET 2021',2021),
Q('primary','english','Choose the correct spelling-',['Accomodation','Accommodation','Acomodation','Acommodation'],'Accommodation','CTET 2022',2022),
Q('primary','english','The indirect speech of "He said, I am happy" is-',['He said that I am happy','He said that he was happy','He said he is happy','He says he was happy'],'He said that he was happy','UPTET 2022',2022),
Q('primary','english','Mother tongue interference means-',['Using L1 patterns in L2','Forgetting L1','Learning L1 again','None'],'Using L1 patterns in L2','CTET 2023',2023),
Q('primary','english','Total Language Immersion means-',['Teaching only grammar','Complete exposure to target language','Translation method','Memorization'],'Complete exposure to target language','UPTET 2023',2023),
Q('primary','english','A homophone is a word that-',['Has same meaning','Sounds the same but different meaning','Looks the same','None'],'Sounds the same but different meaning','CTET 2018',2018),
Q('primary','english','Which is a determiner?',['Run','The','Beautiful','Quickly'],'The','UPTET 2018',2018),
Q('primary','english','Scaffolding in language learning means-',['Building walls','Providing temporary support','Testing students','Punishing errors'],'Providing temporary support','CTET 2017',2017),
Q('primary','english','Silent reading helps in-',['Speed and comprehension','Pronunciation','Listening','Speaking'],'Speed and comprehension','UPTET 2017',2017),
Q('primary','english','Error correction in language class should be-',['Immediate and harsh','Constructive and supportive','Avoided completely','Done publicly'],'Constructive and supportive','CTET 2016',2016),
Q('junior','english','An oxymoron is-',['Exaggeration','Contradictory terms together','Comparison using like','Giving human qualities to objects'],'Contradictory terms together','CTET 2019',2019),
Q('junior','english','Personification means-',['Exaggeration','Human qualities to non-human things','Comparison','Repetition'],'Human qualities to non-human things','UPTET 2019',2019),
Q('junior','english','Alliteration is-',['Repetition of vowel sounds','Repetition of consonant sounds at the start','Exaggeration','Comparison'],'Repetition of consonant sounds at the start','CTET 2020',2020),
Q('junior','english','A clause that can stand alone is called-',['Dependent clause','Independent clause','Relative clause','Noun clause'],'Independent clause','UPTET 2020',2020),
Q('junior','english','The genre of "The Merchant of Venice" is-',['Tragedy','Comedy','History','Sonnet'],'Comedy','CTET 2021',2021),
Q('junior','english','Critical thinking in reading means-',['Reading fast','Analyzing and evaluating the text','Memorizing','Copying'],'Analyzing and evaluating the text','UPTET 2021',2021),
Q('junior','english','Task-based language teaching focuses on-',['Grammar drills','Completing meaningful tasks','Translation','Memorization'],'Completing meaningful tasks','CTET 2022',2022),
Q('junior','english','Extensive reading means-',['Reading difficult texts slowly','Reading large amounts for pleasure','Reading aloud','Close reading'],'Reading large amounts for pleasure','UPTET 2022',2022),
Q('junior','english','Which is a modal verb?',['Run','Eat','Can','Happy'],'Can','CTET 2023',2023),
Q('junior','english','Peer assessment helps in-',['Competition','Collaborative learning and self-reflection','Ranking students','Punishment'],'Collaborative learning and self-reflection','UPTET 2023',2023),
Q('junior','english','A portfolio in language assessment includes-',['Only exam papers','Collection of student work over time','Only homework','Only attendance'],'Collection of student work over time','CTET 2018',2018),
Q('junior','english','Skimming means-',['Reading every word','Reading quickly for main idea','Reading aloud','Translating'],'Reading quickly for main idea','UPTET 2018',2018),
Q('junior','english','Scanning means-',['Reading for pleasure','Looking for specific information','Reading slowly','Writing summary'],'Looking for specific information','CTET 2017',2017),
Q('junior','english','Which is correct? "Each of the boys ___ present."',['are','were','is','have been'],'is','UPTET 2017',2017),
Q('junior','english','A rubric is used for-',['Teaching grammar','Structured assessment criteria','Attendance','Discipline'],'Structured assessment criteria','CTET 2016',2016),
];
