const { v4: uuidv4 } = require('uuid');
const Q = (l,s,t,o,a,src,yr) => ({question_id:uuidv4(),level:l,subject:s,question_text:t,options:o,correct_answer:a,source:src,year:yr,language:'english',created_at:new Date()});

module.exports = [
Q('junior','science','The chemical formula for water is-',['H2O','CO2','O2','NaCl'],'H2O','CTET 2011',2011),
Q('junior','science','Which of the following is a physical change?',['Burning of wood','Rusting of iron','Melting of wax','Cooking of food'],'Melting of wax','UPTET 2012',2012),
Q('junior','science','The fundamental unit of life is-',['Atom','Cell','Molecule','Tissue'],'Cell','CTET 2013',2013),
Q('junior','science','Which of the following is a greenhouse gas?',['Oxygen','Nitrogen','Carbon dioxide','Argon'],'Carbon dioxide','UPTET 2014',2014),
Q('junior','science','The force of attraction between any two objects in the universe is called-',['Friction','Magnetism','Gravitation','Inertia'],'Gravitation','CTET 2015',2015),
Q('junior','science','Which of the following is an insulator?',['Copper','Aluminum','Silver','Wood'],'Wood','UPTET 2016',2016),
Q('junior','science','The instrument used to measure the speed of wind is-',['Thermometer','Barometer','Anemometer','Hygrometer'],'Anemometer','CTET 2017',2017),
Q('junior','science','Which of the following is a base?',['Hydrochloric acid','Sulfuric acid','Sodium hydroxide','Citric acid'],'Sodium hydroxide','UPTET 2018',2018),
Q('junior','science','The unit of energy is-',['Newton','Watt','Joule','Pascal'],'Joule','CTET 2019',2019),
Q('junior','science','Which organ removes waste from the blood?',['Lungs','Kidneys','Liver','Heart'],'Kidneys','UPTET 2020',2020),
Q('junior','science','The process of breathing in plants occurs through-',['Roots','Flowers','Stomata','Bark'],'Stomata','CTET 2021',2021),
Q('junior','science','Which of the following is a renewable source of energy?',['Coal','Petroleum','Solar energy','Natural gas'],'Solar energy','UPTET 2021',2021),
Q('junior','science','The blood groups were discovered by-',['Charles Darwin','Gregor Mendel','Karl Landsteiner','Louis Pasteur'],'Karl Landsteiner','CTET 2022',2022),
Q('junior','science','Which of the following is a metal?',['Oxygen','Carbon','Iron','Nitrogen'],'Iron','UPTET 2022',2022),
Q('junior','science','The study of fossils is called-',['Biology','Geology','Paleontology','Ecology'],'Paleontology','CTET 2023',2023),
Q('junior','science','Which gas is released during respiration?',['Oxygen','Carbon dioxide','Nitrogen','Hydrogen'],'Carbon dioxide','UPTET 2023',2023),
Q('junior','science','Which of the following is a scalar quantity?',['Displacement','Velocity','Acceleration','Speed'],'Speed','CTET 2018',2018),
Q('junior','science','The average lifespan of human red blood cells is-',['10 days','60 days','120 days','365 days'],'120 days','UPTET 2017',2017),
Q('junior','science','Which of the following is a liquid at room temperature?',['Gold','Mercury','Copper','Iron'],'Mercury','CTET 2016',2016),
Q('junior','science','The reflection of sound is called-',['Refraction','Echo','Dispersion','Diffraction'],'Echo','UPTET 2015',2015),
Q('junior','science','Which of the following is a natural fiber?',['Nylon','Rayon','Silk','Polyester'],'Silk','CTET 2014',2014),
Q('junior','science','The acid found in lemons is-',['Acetic acid','Lactic acid','Citric acid','Formic acid'],'Citric acid','UPTET 2013',2013),
Q('junior','science','The nearest planet to the Sun is-',['Earth','Venus','Mercury','Mars'],'Mercury','CTET 2012',2012),
Q('junior','science','Which of the following is an amphibian?',['Fish','Frog','Snake','Bird'],'Frog','UPTET 2012',2012),
Q('junior','science','The brain of the cell is-',['Mitochondria','Ribosome','Nucleus','Lysosome'],'Nucleus','CTET 2011',2011),
Q('junior','science','Which of the following is a poor conductor of electricity?',['Silver','Copper','Rubber','Aluminum'],'Rubber','UPTET 2011',2011),
Q('junior','science','The instrument used to see very small objects is-',['Telescope','Microscope','Periscope','Stethoscope'],'Microscope','CTET 2023',2023),
Q('junior','science','Which of the following is a source of protein?',['Rice','Sugar','Egg','Butter'],'Egg','UPTET 2020',2020),
Q('junior','science','The deficiency of Vitamin C causes-',['Night blindness','Beriberi','Scurvy','Rickets'],'Scurvy','CTET 2022',2022),
Q('junior','science','Which of the following is a consumer in an ecosystem?',['Grass','Tree','Rabbit','Algae'],'Rabbit','UPTET 2019',2019),
Q('junior','science','The atmospheric pressure is measured with a-',['Thermometer','Hygrometer','Barometer','Anemometer'],'Barometer','CTET 2021',2021),
Q('junior','science','Which of the following is a rich source of Vitamin D?',['Orange','Lemon','Fish liver oil','Spinach'],'Fish liver oil','UPTET 2018',2018),
Q('junior','science','The chemical symbol for Silver is-',['Au','Ag','Fe','Cu'],'Ag','CTET 2020',2020),
Q('junior','science','Which of the following is a non-metal?',['Sodium','Calcium','Sulfur','Magnesium'],'Sulfur','UPTET 2017',2017),
Q('junior','science','The value of the speed of sound in air is approx-',['340 m/s','1500 m/s','300,000 km/s','None'],'340 m/s','CTET 2019',2019),
Q('junior','science','Which of the following is a hormone produced by the pancreas?',['Adrenaline','Insulin','Thyroxine','Estrogen'],'Insulin','CTET 2016',2016),
Q('junior','science','Which of the following is a good conductor of heat?',['Plastic','Wood','Iron','Glass'],'Iron','UPTET 2022',2022),
Q('junior','science','The pH value of an acidic solution is-',['Exactly 7','Greater than 7','Less than 7','14'],'Less than 7','CTET 2015',2015),
Q('junior','science','Which of the following is a primary source of energy?',['Sun','Moon','Battery','Generator'],'Sun','UPTET 2021',2021),
Q('junior','science','The part of the ear that helps in balancing is-',['Eardrum','Cochlea','Semicircular canals','Auditory nerve'],'Semicircular canals','CTET 2014',2014),
Q('junior','science','Which of the following is a compound?',['Oxygen','Hydrogen','Water','Gold'],'Water','UPTET 2014',2014),
Q('junior','science','The process of heating a solid to turn it into gas directly is-',['Melting','Boiling','Sublimation','Condensation'],'Sublimation','CTET 2013',2013),
Q('junior','science','Which of the following is a symbiotic relationship?',['Parasitism','Lichen','Predation','Competition'],'Lichen','UPTET 2013',2013),
Q('junior','science','The chemical symbol for Iron is-',['Ir','Fe','In','I'],'Fe','CTET 2012',2012),
Q('junior','science','Which of the following is a cold-blooded animal?',['Human','Dog','Snake','Pigeon'],'Snake','UPTET 2012',2012),
Q('junior','science','The freezing point of water in Celsius is-',['0°C','-10°C','32°C','100°C'],'0°C','CTET 2011',2011),
Q('junior','science','Which of the following is a non-metal?',['Carbon','Aluminum','Silver','Iron'],'Carbon','UPTET 2023',2023),
Q('junior','science','Which of the following is a biotic component?',['Air','Water','Plants','Soil'],'Plants','CTET 2020',2020),
Q('junior','science','The energy stored in a battery is-',['Kinetic energy','Potential energy','Chemical energy','Thermal energy'],'Chemical energy','UPTET 2011',2011),
Q('junior','science','Which of the following is an example of a simple machine?',['Pulley','Television','Refrigerator','Washing machine'],'Pulley','CTET 2022',2022),
];
