const { v4: uuidv4 } = require('uuid');
const Q = (l,s,t,o,a,src,yr) => ({question_id:uuidv4(),level:l,subject:s,question_text:t,options:o,correct_answer:a,source:src,year:yr,language:'english',created_at:new Date()});

module.exports = [
Q('junior','science','The chemical formula for Ammonia is-',['NH3','CH4','CO2','H2O'],'NH3','CTET 2011',2011),
Q('junior','science','Which of the following is a chemical change?',['Burning of candle','Melting of ice','Boiling of water','Cutting of wood'],'Burning of candle','UPTET 2012',2012),
Q('junior','science','The unit of work is-',['Joule','Watt','Newton','Pascal'],'Joule','CTET 2013',2013),
Q('junior','science','Which of the following is a source of roughage?',['Fruits','Milk','Egg','Meat'],'Fruits','UPTET 2014',2014),
Q('junior','science','The process of transition from gas to solid is called-',['Sublimation','Deposition','Freezing','Melting'],'Deposition','CTET 2015',2015),
Q('junior','science','Which of the following is a semi-conductor?',['Silver','Copper','Silicon','Aluminum'],'Silicon','UPTET 2016',2016),
Q('junior','science','The instrument used to measure the purity of milk is-',['Thermometer','Barometer','Lactometer','Hygrometer'],'Lactometer','CTET 2017',2017),
Q('junior','science','Which of the following is a strong acid?',['Hydrochloric acid','Acetic acid','Citric acid','Tartaric acid'],'Hydrochloric acid','UPTET 2018',2018),
Q('junior','science','The SI unit of pressure is-',['Newton','Watt','Joule','Pascal'],'Pascal','CTET 2019',2019),
Q('junior','science','Which organ is responsible for detoxification in the body?',['Kidney','Liver','Lungs','Heart'],'Liver','UPTET 2020',2020),
Q('junior','science','The part of the plant where food is stored is-',['Root','Stem','Leaf','All of these'],'All of these','CTET 2021',2021),
Q('junior','science','Which of the following is an inexhaustible resource?',['Coal','Petroleum','Solar energy','Natural gas'],'Solar energy','UPTET 2021',2021),
Q('junior','science','The total number of muscles in human body is approx-',['200','400','600','None'],'600','CTET 2022',2022),
Q('junior','science','Which of the following is a non-metal that is liquid at room temperature?',['Mercury','Bromine','Iodine','Sulfur'],'Bromine','UPTET 2022',2022),
Q('junior','science','The study of heredity is called-',['Biology','Botany','Genetics','Ecology'],'Genetics','CTET 2023',2023),
Q('junior','science','Which gas is release during fermentation?',['Oxygen','Carbon dioxide','Nitrogen','Hydrogen'],'Carbon dioxide','UPTET 2023',2023),
Q('junior','science','Which of the following is a base?',['Milk of Magnesia','Lemon juice','Vinegar','Battery acid'],'Milk of Magnesia','CTET 2018',2018),
Q('junior','science','The pH value of pure water is-',['0','7','14','None'],'7','UPTET 2017',2017),
Q('junior','science','Which of the following is a metalloid?',['Iron','Oxygen','Silicon','Silver'],'Silicon','CTET 2016',2016),
Q('junior','science','The phenomenon of light splitting into its constituent colors is-',['Reflection','Refraction','Dispersion','Diffraction'],'Dispersion','UPTET 2015',2015),
Q('junior','science','Which of the following is a semi-synthetic fiber?',['Nylon','Rayon','Cotton','Wool'],'Rayon','CTET 2014',2014),
Q('junior','science','The acid found in ant sting is-',['Formic acid','Lactic acid','Citric acid','Acetic acid'],'Formic acid','UPTET 2013',2013),
Q('junior','science','The hottest planet in the solar system is-',['Mercury','Venus','Earth','Mars'],'Venus','CTET 2012',2012),
Q('junior','science','Which of the following is an egg-laying mammal?',['Kangaroo','Bat','Platypus','Whale'],'Platypus','UPTET 2012',2012),
Q('junior','science','The suicide bag of the cell is-',['Mitochondria','Ribosome','Nucleus','Lysosome'],'Lysosome','CTET 2011',2011),
Q('junior','science','Which of the following is a good conductor of electricity?',['Silver','Glass','Rubber','Plastic'],'Silver','UPTET 2011',2011),
Q('junior','science','The instrument used to measure atmospheric pressure is-',['Thermometer','Barometer','Hygrometer','Anemometer'],'Barometer','CTET 2023',2023),
Q('junior','science','Which of the following is a protein?',['Glucose','Keratin','Starch','Cellulose'],'Keratin','UPTET 2020',2020),
Q('junior','science','The deficiency of Vitamin B1 causes-',['Scurvy','Rickets','Beriberi','Anaemia'],'Beriberi','CTET 2022',2022),
Q('junior','science','Which of the following is a scavenger?',['Lion','Vulture','Deer','Rabbit'],'Vulture','UPTET 2019',2019),
Q('junior','science','The boiling point of water in Fahrenheit is-',['32°F','100°F','212°F','None'],'212°F','CTET 2021',2021),
Q('junior','science','Which of the following is a source of Vitamin K?',['Leafy vegetables','Meat','Egg','All of these'],'All of these','UPTET 2018',2018),
Q('junior','science','The process of separating a liquid from solid is-',['Filtration','Evaporation','Centrifugation','All of these'],'All of these','CTET 2020',2020),
Q('junior','science','Which of the following is a physical property?',['Boiling point','Flammability','Reactivity','Color','Both A and D'],'Both A and D','UPTET 2017',2017),
Q('junior','science','The weight of an object on Moon is ___ of its weight on Earth.',['1/2','1/4','1/6','None'],'1/6','CTET 2019',2019),
Q('junior','science','Which of the following is a male reproductive part of a flower?',['Stamen','Pistil','Petal','Sepal'],'Stamen','CTET 2016',2016),
Q('junior','science','Which of the following is non-magnetic?',['Iron','Nickel','Cobalt','Aluminum'],'Aluminum','UPTET 2022',2022),
Q('junior','science','The pH value of human blood is approx-',['6.0','7.4','8.5','None'],'7.4','CTET 2015',2015),
Q('junior','science','Which of the following is a primary consumer in an ocean?',['Shark','Whale','Zooplankton','Small fish'],'Zooplankton','UPTET 2021',2021),
Q('junior','science','The part of the eye which provides color to the eye is-',['Cornea','Iris','Retina','Lens'],'Iris','CTET 2014',2014),
Q('junior','science','Which of the following is a noble gas?',['Helium','Nitrogen','Oxygen','Hydrogen'],'Helium','UPTET 2014',2014),
Q('junior','science','The process of transition from solid to gas directly is-',['Melting','Boiling','Sublimation','Condensation'],'Sublimation','CTET 2013',2013),
Q('junior','science','Which of the following is a symbiotic relationship?',['Mycorrhiza','Parasitism','Predation','Competition'],'Mycorrhiza','UPTET 2013',2013),
Q('junior','science','The chemical symbol for Potassium is-',['Po','P','K','Pt'],'K','CTET 2012',2012),
Q('junior','science','Which of the following is a cold-blooded animal?',['Lizard','Human','Dog','Whale'],'Lizard','UPTET 2012',2012),
Q('junior','science','The freezing point of water in Fahrenheit is-',['0°F','32°F','100°F','None'],'32°F','CTET 2011',2011),
Q('junior','science','Which of the following is a non-metal?',['Carbon','Sulfur','Oxygen','All of these'],'All of these','UPTET 2023',2023),
Q('junior','science','Which of the following is an abiotic component?',['Light','Plants','Animals','Bacteria'],'Light','CTET 2020',2020),
Q('junior','science','The unit of acceleration is-',['m/s','m/s²','km/h','None'],'m/s²','UPTET 2011',2011),
Q('junior','science','Which of the following is a simple machine?',['Wheel and axle','Wedge','Screw','All of these'],'All of these','CTET 2022',2022),
];
