const { v4: uuidv4 } = require('uuid');
const Q = (l,s,t,o,a,src,yr) => ({question_id:uuidv4(),level:l,subject:s,question_text:t,options:o,correct_answer:a,source:src,year:yr,language:'english',created_at:new Date()});

module.exports = [
Q('primary','evs','The animals that live on both land and water are called-',['Mammals','Reptiles','Amphibians','None'],'Amphibians','CTET 2011',2011),
Q('primary','evs','Which of the following is an example of a bulbous plant?',['Rose','Onion','Tulip','Both B and C'],'Both B and C','UPTET 2012',2012),
Q('primary','evs','The "Linen" fiber is obtained from which plant?',['Cotton','Flax','Jute','Hemp'],'Flax','CTET 2013',2013),
Q('primary','evs','Which of the following is a Zaid crop?',['Wheat','Rice','Watermelon','Mustard'],'Watermelon','UPTET 2014',2014),
Q('primary','evs','The process of transition from gas to solid is called-',['Sublimation','Deposition','Freezing','None'],'Deposition','CTET 2015',2015),
Q('primary','evs','Which bird is known as the "King of Birds"?',['Eagle','Peacock','Sparrow','Crow'],'Eagle','UPTET 2016',2016),
Q('primary','evs','The largest union territory of India by area is-',['Delhi','Ladakh','Chandigarh','Lakshadweep'],'Ladakh','CTET 2017',2017),
Q('primary','evs','Which of the following is a clean source of energy?',['Coal','Petroleum','Solar','None'],'Solar','UPTET 2018',2018),
Q('primary','evs','The main source of Vitamin B1 is-',['Milk','Rice (Polished)','Whole grains','Apple'],'Whole grains','CTET 2019',2019),
Q('primary','evs','Which of the following is a genetic disease?',['Flu','Diabetes','Hemophilia','Asthma'],'Hemophilia','UPTET 2020',2020),
Q('primary','evs','The highest plateau in the world is-',['Deccan','Tibet','Colorado','None'],'Tibet','CTET 2021',2021),
Q('primary','evs','Which planet is known as the "Blue Planet"?',['Earth','Mars','Jupiter','Saturn'],'Earth','UPTET 2021',2021),
Q('primary','evs','The process of transition from solid to gas is-',['Sublimation','Evaporation','Melting','None'],'Sublimation','CTET 2022',2022),
Q('primary','evs','Which of the following is a synthetic fiber?',['Cotton','Wool','Rayon','None'],'Rayon','UPTET 2022',2022),
Q('primary','evs','The study of the environment is called-',['Ecology','Geography','Astronomy','Biology'],'Ecology','CTET 2023',2023),
Q('primary','evs','Which of the following is a rich source of Vitamin E?',['Nuts and Seeds','Rice','Sugar','Oil'],'Nuts and Seeds','UPTET 2023',2023),
Q('primary','evs','The "Bandhavgarh National Park" is located in-',['Madhya Pradesh','Uttarakhand','Gujarat','Rajasthan'],'Madhya Pradesh','CTET 2018',2018),
Q('primary','evs','Which of the following gas is used in a light bulb?',['Oxygen','Nitrogen','Argon','Both B and C'],'Both B and C','UPTET 2017',2017),
Q('primary','evs','The "Nilgiri Biosphere Reserve" is located in-',['Tamil Nadu','Kerala','Karnataka','All of these'],'All of these','CTET 2016',2016),
Q('primary','evs','Which of the following is a non-renewable resource?',['Wind','Solar','Coal','Water'],'Coal','UPTET 2015',2015),
Q('primary','evs','The main component of air is-',['Oxygen','Nitrogen','Argon','None'],'Nitrogen','CTET 2014',2014),
Q('primary','evs','Which of the following is a bird that cannot fly?',['Penguin','Ostrich','Kiwi','All of these'],'All of these','UPTET 2013',2013),
Q('primary','evs','The deficiency of Vitamin B3 causes-',['Scurvy','Rickets','Pellagra','None'],'Pellagra','CTET 2012',2012),
Q('primary','evs','Which of the following is a warm-blooded animal?',['Snake','Fish','Human','Frog'],'Human','UPTET 2012',2012),
Q('primary','evs','The "Ozone Layer" protects us from-',['UV rays','Infrared rays','X-rays','None'],'UV rays','CTET 2011',2011),
Q('primary','evs','Which of the following is an artificial fiber?',['Silk','Wool','Nylon','Cotton'],'Nylon','UPTET 2011',2011),
Q('primary','evs','The "Blue Revolution" is related to-',['Milk','Agriculture','Fish','Cotton'],'Fish','CTET 2023',2023),
Q('primary','evs','Which of the following is a natural fiber from plants?',['Cotton','Silk','Wool','Nylon'],'Cotton','UPTET 2020',2020),
Q('primary','evs','The main source of light for the Earth is-',['Moon','Sun','Stars','Fire'],'Sun','CTET 2022',2022),
Q('primary','evs','Which of the following is a biotic factor?',['Water','Air','Bacteria','Light'],'Bacteria','UPTET 2019',2019),
Q('primary','evs','The process of boiling is used for-',['Sterilization','Melting','Sublimation','None'],'Sterilization','CTET 2021',2021),
Q('primary','evs','Which of the following is used to treat scurvy?',['Vitamin C','Aspirin','ORS','None'],'Vitamin C','UPTET 2018',2018),
Q('primary','evs','The "Exxon Valdez" spill was related to-',['Oil leak','Nuclear leak','Gas leak','None'],'Oil leak','CTET 2020',2020),
Q('primary','evs','Which of the following is a source of Iron?',['Spinach','Meat','Apple','All of these'],'All of these','UPTET 2017',2017),
Q('primary','evs','The "Indus" river originates from-',['Gangotri','Manasarovar Lake','Rohtang','None'],'Manasarovar Lake','CTET 2019',2019),
Q('primary','evs','Which of the following is a greenhouse gas?',['Oxygen','Nitrogen','Carbon Dioxide','None'],'Carbon Dioxide','UPTET 2016',2016),
Q('primary','evs','The "Periyar National Park" is located in-',['Kerala','Karnataka','Tamil Nadu','None'],'Kerala','CTET 2018',2018),
Q('primary','evs','Which of the following is a vector of West Nile virus?',['Culex Mosquito','Anopheles Mosquito','Aedes Mosquito','None'],'Culex Mosquito','UPTET 2015',2015),
Q('primary','evs','The "World Forestry Day" is celebrated on-',['21st March','5th June','22nd April','None'],'21st March','CTET 2017',2017),
Q('primary','evs','Which of the following is a source of tidal energy?',['Moon','Sun','Stars','None'],'Moon','UPTET 2014',2014),
Q('primary','evs','The "Mesosphere" is the ___ layer of atmosphere.',['Lowest','Middle','Highest','None'],'Middle','CTET 2016',2016),
Q('primary','evs','Which of the following is a non-biodegradable waste?',['Plastic','Metal','Glass','All of these'],'All of these','UPTET 2013',2013),
Q('primary','evs','The study of fish is called-',['Ichthyology','Botany','Zoology','None'],'Ichthyology','CTET 2015',2015),
Q('primary','evs','Which of the following is a source of Vitamin B2?',['Milk','Meat','Egg','All of these'],'All of these','UPTET 2012',2012),
Q('primary','evs','The "Project Snow Leopard" was launched in-',['1973','1992','2009','None'],'2009','CTET 2014',2014),
Q('primary','evs','Which of the following is a carnivore?',['Wolf','Deer','Rabbit','Sheep'],'Wolf','UPTET 2011',2011),
Q('primary','evs','The layer of the atmosphere where aurora occurs is-',['Thermosphere','Troposphere','Stratosphere','None'],'Thermosphere','CTET 2013',2013),
Q('primary','evs','Which of the following is a cause of water pollution?',['Planting trees','Industrial waste','Rain','None'],'Industrial waste','UPTET 2023',2023),
Q('primary','evs','The main source of light for the body is-',['Moon','Sun','Stars','Fire'],'Sun','CTET 2012',2012),
Q('primary','evs','How many legs does a centipede have?',['10','20','Variable','100'],'Variable','UPTET 2010',2010),
];
