const { v4: uuidv4 } = require('uuid');
const Q = (l,s,t,o,a,src,yr) => ({question_id:uuidv4(),level:l,subject:s,question_text:t,options:o,correct_answer:a,source:src,year:yr,language:'english',created_at:new Date()});

module.exports = [
Q('primary','evs','The main source of Vitamin B is-',['Milk','Rice','Meat','Egg','All of these'],'All of these','CTET 2011',2011),
Q('primary','evs','Which of the following is an example of a creeper?',['Rose','Money plant','Watermelon','Tulip'],'Watermelon','UPTET 2012',2012),
Q('primary','evs','The "Honey" is produced by which insect?',['Bee','Ant','Butterfly','Termite'],'Bee','CTET 2013',2013),
Q('primary','evs','Which of the following is a Zaid crop?',['Wheat','Rice','Cucumber','Cotton'],'Cucumber','UPTET 2014',2014),
Q('primary','evs','The gas released by plants during photosynthesis is-',['Oxygen','Nitrogen','Carbon Dioxide','Argon'],'Oxygen','CTET 2015',2015),
Q('primary','evs','Which bird is known as the "National Bird of USA"?',['Bald Eagle','Peacock','Sparrow','Pigeon'],'Bald Eagle','UPTET 2016',2016),
Q('primary','evs','The smallest Union Territory of India by area is-',['Chandigarh','Lakshadweep','Delhi','Ladakh'],'Lakshadweep','CTET 2017',2017),
Q('primary','evs','Which of the following is a fossil fuel?',['Coal','Solar','Wind','Water'],'Coal','UPTET 2018',2018),
Q('primary','evs','The main source of Vitamin D is-',['Milk','Orange','Sunlight','Apple'],'Sunlight','CTET 2019',2019),
Q('primary','evs','Which of the following is a skin disease?',['Typhoid','Cholera','Flu','Scabies'],'Scabies','UPTET 2020',2020),
Q('primary','evs','The largest ocean in the world is-',['Atlantic','Indian','Pacific','Arctic'],'Pacific','CTET 2021',2021),
Q('primary','evs','Which planet is known as the "Evening Star"?',['Venus','Mars','Jupiter','Saturn'],'Venus','UPTET 2021',2021),
Q('primary','evs','The process of transition from liquid to gas is-',['Evaporation','Condensation','Freezing','None'],'Evaporation','CTET 2022',2022),
Q('primary','evs','Which of the following is a synthetic fiber?',['Cotton','Wool','Polyester','Silk'],'Polyester','UPTET 2022',2022),
Q('primary','evs','The study of history through physical remains is-',['Geography','Archaeology','Biology','Physics'],'Archaeology','CTET 2023',2023),
Q('primary','evs','Which of the following is a rich source of Calcium?',['Milk','Rice','Sugar','Oil'],'Milk','UPTET 2023',2023),
Q('primary','evs','The "Gir National Park" is located in-',['Assam','Kerala','Gujarat','Rajasthan'],'Gujarat','CTET 2018',2018),
Q('primary','evs','Which of the following gas is used in soda water?',['Oxygen','Nitrogen','Carbon Dioxide','Hydrogen'],'Carbon Dioxide','UPTET 2017',2017),
Q('primary','evs','The "Kanchenjunga" peak is located in-',['Uttarakhand','Sikkim','Himachal Pradesh','Arunachal Pradesh'],'Sikkim','CTET 2016',2016),
Q('primary','evs','Which of the following is a renewable source of energy?',['Coal','Petroleum','Wind','Natural Gas'],'Wind','UPTET 2015',2015),
Q('primary','evs','The percentage of Oxygen in the atmosphere is approx-',['21%','78%','1%','0.03%'],'21%','CTET 2014',2014),
Q('primary','evs','Which of the following is a nocturnal animal?',['Lion','Deer','Owl','Rabbit'],'Owl','UPTET 2013',2013),
Q('primary','evs','The deficiency of Iron causes-',['Scurvy','Rickets','Anaemia','Goitre'],'Anaemia','CTET 2012',2012),
Q('primary','evs','Which of the following is an egg-laying mammal?',['Platypus','Kangaroo','Bat','Whale'],'Platypus','UPTET 2012',2012),
Q('primary','evs','The "Earth Day" is celebrated on-',['5th June','22nd April','16th Sept','1st Dec'],'22nd April','CTET 2011',2011),
Q('primary','evs','Which of the following is a terrestrial ecosystem?',['A pond','A forest','An ocean','A river'],'A forest','UPTET 2011',2011),
Q('primary','evs','The "Silver Revolution" is related to-',['Milk','Agriculture','Eggs','Cotton'],'Eggs','CTET 2023',2023),
Q('primary','evs','Which of the following is a plant fiber?',['Wool','Silk','Jute','Nylon'],'Jute','UPTET 2020',2020),
Q('primary','evs','The main source of Vitamin K is-',['Leafy vegetables','Orange','Rice','Potato'],'Leafy vegetables','CTET 2022',2022),
Q('primary','evs','Which of the following is a biotic component?',['Air','Water','Fungi','Light'],'Fungi','UPTET 2019',2019),
Q('primary','evs','The process of melting is also called-',['Fusion','Evaporation','Sublimation','None'],'Fusion','CTET 2021',2021),
Q('primary','evs','Which of the following is a natural indicator?',['Turmeric','Phenolphthalein','Methyl orange','None'],'Turmeric','UPTET 2018',2018),
Q('primary','evs','The "Minamata Disease" was caused by-',['Lead','Mercury','Cadmium','Arsenic'],'Mercury','CTET 2020',2020),
Q('primary','evs','Which of the following is a source of Vitamin E?',['Vegetable oils','Orange','Rice','Milk'],'Vegetable oils','UPTET 2017',2017),
Q('primary','evs','The "Yamuna" river originates from-',['Gangotri','Yamunotri','Manasarovar','Rohtang'],'Yamunotri','CTET 2019',2019),
Q('primary','evs','Which of the following is not a greenhouse gas?',['Oxygen','Methane','Carbon Dioxide','Nitrous Oxide'],'Oxygen','UPTET 2016',2016),
Q('primary','evs','The "Appiko Movement" was started in which state?',['Kerala','Karnataka','Tamil Nadu','Goa'],'Karnataka','CTET 2018',2018),
Q('primary','evs','Which of the following is a vector of Zika virus?',['Anopheles Mosquito','Aedes Mosquito','Housefly','Cockroach'],'Aedes Mosquito','UPTET 2015',2015),
Q('primary','evs','The "World Environment Day" is celebrated on-',['22nd March','5th June','22nd April','None'],'5th June','CTET 2017',2017),
Q('primary','evs','Which of the following is a source of Solar Energy?',['Moon','Sun','Stars','Earth'],'Sun','UPTET 2014',2014),
Q('primary','evs','The "Stratosphere" contains which protective layer?',['Ozone','Carbon','Nitrogen','Oxygen'],'Ozone','CTET 2016',2016),
Q('primary','evs','Which of the following is a biodegradable material?',['Plastic','Wood','Glass','Metal'],'Wood','UPTET 2013',2013),
Q('primary','evs','The study of reptiles and amphibians is called-',['Ornithology','Herpetology','Botany','None'],'Herpetology','CTET 2015',2015),
Q('primary','evs','Which of the following is a rich source of Vitamin B12?',['Milk','Spinach','Orange','Rice'],'Milk','UPTET 2012',2012),
Q('primary','evs','The "Project Rhino" was launched in-',['1973','1987','2005','None'],'2005','CTET 2014',2014),
Q('primary','evs','Which of the following is a decomposer?',['Lion','Rabbit','Bacteria','Tree'],'Bacteria','UPTET 2011',2011),
Q('primary','evs','The layer of the atmosphere where weather occurs is-',['Troposphere','Stratosphere','Mesosphere','None'],'Troposphere','CTET 2013',2013),
Q('primary','evs','Which of the following is a cause of air pollution?',['Planting trees','Burning fossils','Using bicycles','None'],'Burning fossils','UPTET 2023',2023),
Q('primary','evs','The main source of salt is-',['Rivers','Sea','Lakes','Rain'],'Sea','CTET 2012',2012),
Q('primary','evs','How many legs does a spider have?',['4','6','8','10'],'8','UPTET 2010',2010),
];
