const { v4: uuidv4 } = require('uuid');
const Q = (l,s,t,o,a,src,yr) => ({question_id:uuidv4(),level:l,subject:s,question_text:t,options:o,correct_answer:a,source:src,year:yr,language:'english',created_at:new Date()});

module.exports = [
Q('junior','science','The main component of natural gas is-',['Methane','Ethane','Propane','Butane'],'Methane','CTET 2011',2011),
Q('junior','science','Which of the following is a chemical change?',['Burning of magnesium','Melting of ice','Sublimation of iodine','Boiling of water'],'Burning of magnesium','UPTET 2012',2012),
Q('junior','science','The unit of power is-',['Joule','Watt','Newton','Pascal'],'Watt','CTET 2013',2013),
Q('junior','science','Which of the following is a balanced diet?',['Rich in fats','Rich in proteins','Containing all nutrients in right proportions','Rich in carbohydrates'],'Containing all nutrients in right proportions','UPTET 2014',2014),
Q('junior','science','The process of transition from solid to liquid is called-',['Freezing','Melting','Evaporation','Condensation'],'Melting','CTET 2015',2015),
Q('junior','science','Which of the following is a good conductor of heat?',['Plastic','Wood','Silver','Glass'],'Silver','UPTET 2016',2016),
Q('junior','science','The speed of sound is highest in-',['Air','Water','Steel','Vacuum'],'Steel','CTET 2017',2017),
Q('junior','science','Which of the following is an acid?',['Baking soda','Soap','Vinegar','Washing soda'],'Vinegar','UPTET 2018',2018),
Q('junior','science','The SI unit of temperature is-',['Celsius','Fahrenheit','Kelvin','None'],'Kelvin','CTET 2019',2019),
Q('junior','science','Which organ is known as the "Filter of the body"?',['Heart','Kidney','Lungs','Liver'],'Kidney','UPTET 2020',2020),
Q('junior','science','The part of the plant that helps in absorption of water is-',['Leaves','Stems','Roots','Flowers'],'Roots','CTET 2021',2021),
Q('junior','science','Which of the following is a non-renewable resource?',['Solar energy','Wind energy','Natural gas','Biomass'],'Natural gas','UPTET 2021',2021),
Q('junior','science','The total number of bones in an adult human is-',['200','206','300','None'],'206','CTET 2022',2022),
Q('junior','science','Which of the following is used in making jewelry?',['Iron','Copper','Gold','Aluminum'],'Gold','UPTET 2022',2022),
Q('junior','science','The study of plants is called-',['Zoology','Botany','Ecology','Geology'],'Botany','CTET 2023',2023),
Q('junior','science','Which gas is consumed during respiration?',['Oxygen','Carbon dioxide','Nitrogen','Hydrogen'],'Oxygen','UPTET 2023',2023),
Q('junior','science','Which of the following is a vector quantity?',['Distance','Speed','Displacement','Time'],'Displacement','CTET 2018',2018),
Q('junior','science','The normal blood pressure of a healthy human is-',['120/80 mmHg','140/90 mmHg','100/60 mmHg','None'],'120/80 mmHg','UPTET 2017',2017),
Q('junior','science','Which of the following is a noble gas?',['Argon','Oxygen','Chlorine','Fluorine'],'Argon','CTET 2016',2016),
Q('junior','science','The splitting of white light into seven colors is called-',['Reflection','Refraction','Dispersion','Diffraction'],'Dispersion','UPTET 2015',2015),
Q('junior','science','Which of the following is a natural fiber?',['Nylon','Rayon','Wool','Polyester'],'Wool','CTET 2014',2014),
Q('junior','science','The chemical formula for Sulfuric acid is-',['HCl','H2SO4','HNO3','CH3COOH'],'H2SO4','UPTET 2013',2013),
Q('junior','science','Which planet is known as the "Morning Star"?',['Venus','Mars','Jupiter','Saturn'],'Venus','CTET 2012',2012),
Q('junior','science','Which of the following is a reptile?',['Frog','Lizard','Fish','Bird'],'Lizard','UPTET 2012',2012),
Q('junior','science','The part of the cell responsible for protein synthesis is-',['Nucleus','Ribosome','Mitochondria','Lysosome'],'Ribosome','CTET 2011',2011),
Q('junior','science','Which of the following is a conductor of electricity?',['Pure water','Salt water','Distilled water','Sugar water'],'Salt water','UPTET 2011',2011),
Q('junior','science','The instrument used to measure humidity is-',['Thermometer','Barometer','Hygrometer','Anemometer'],'Hygrometer','CTET 2023',2023),
Q('junior','science','Which of the following is a vitamin?',['Glucose','Ascorbic acid','Starch','Cellulose'],'Ascorbic acid','UPTET 2020',2020),
Q('junior','science','The deficiency of Iodine causes-',['Scurvy','Rickets','Goitre','Anaemia'],'Goitre','CTET 2022',2022),
Q('junior','science','Which of the following is a producer in a forest?',['Lion','Snake','Tree','Deer'],'Tree','UPTET 2019',2019),
Q('junior','science','The value of atmospheric pressure at sea level is approx-',['1 atm','10 atm','0.5 atm','None'],'1 atm','CTET 2021',2021),
Q('junior','science','Which of the following is a source of Vitamin A?',['Milk','Rice','Meat','Egg'],'Milk','UPTET 2018',2018),
Q('junior','science','The process of separating cream from milk is-',['Centrifugation','Filtration','Evaporation','Decantation'],'Centrifugation','CTET 2020',2020),
Q('junior','science','Which of the following is a chemical property?',['Boiling point','Density','Flammability','Color'],'Flammability','UPTET 2017',2017),
Q('junior','science','The value of escape velocity on Earth is approx-',['11.2 km/s','9.8 km/s','5.5 km/s','None'],'11.2 km/s','CTET 2019',2019),
Q('junior','science','Which of the following is a reproductive part of a plant?',['Root','Stem','Flower','Leaf'],'Flower','CTET 2016',2016),
Q('junior','science','Which of the following is a magnet?',['Iron nail','Lodestone','Steel bar','All of these'],'All of these','UPTET 2022',2022),
Q('junior','science','The pH value of a neutral solution is-',['0','7','14','None'],'7','CTET 2015',2015),
Q('junior','science','Which of the following is a fossil fuel?',['Coal','Wood','Sunlight','Wind'],'Coal','UPTET 2021',2021),
Q('junior','science','The part of the eye which controls the amount of light entering is-',['Cornea','Iris','Retina','Lens'],'Iris','CTET 2014',2014),
Q('junior','science','Which of the following is an example of an element?',['Water','Air','Carbon','Sugar'],'Carbon','UPTET 2014',2014),
Q('junior','science','The process of gas turning into liquid is called-',['Sublimation','Condensation','Evaporation','Melting'],'Condensation','CTET 2013',2013),
Q('junior','science','Which of the following is an example of an omnivore?',['Lion','Deer','Bear','Rabbit'],'Bear','UPTET 2013',2013),
Q('junior','science','The chemical symbol for Copper is-',['Co','Cu','Cr','Ca'],'Cu','CTET 2012',2012),
Q('junior','science','Which of the following is an invertebrate?',['Fish','Frog','Earthworm','Snake'],'Earthworm','UPTET 2012',2012),
Q('junior','science','The temperature at which water is densest is-',['0°C','4°C','100°C','None'],'4°C','CTET 2011',2011),
Q('junior','science','Which of the following is a non-metal?',['Nitrogen','Iron','Silver','Gold'],'Nitrogen','UPTET 2023',2023),
Q('junior','science','Which of the following is a biotic component?',['Light','Temperature','Bacteria','pH'],'Bacteria','CTET 2020',2020),
Q('junior','science','The energy of motion is called-',['Potential energy','Kinetic energy','Chemical energy','Thermal energy'],'Kinetic energy','UPTET 2011',2011),
Q('junior','science','Which of the following is an example of a lever?',['Scissors','Wheel','Inclined plane','Screw'],'Scissors','CTET 2022',2022),
];
