const { v4: uuidv4 } = require('uuid');
const Q = (l,s,t,o,a,src,yr) => ({question_id:uuidv4(),level:l,subject:s,question_text:t,options:o,correct_answer:a,source:src,year:yr,language:'english',created_at:new Date()});

module.exports = [
Q('primary','pedagogy','According to Erikson, "Industry vs Inferiority" occurs during-',['Infancy','Early Childhood','School Age','Adolescence'],'School Age','CTET 2018',2018),
Q('primary','pedagogy','The concept of "Mental Retardation" is now called-',['Learning disability','Intellectual disability','Physical disability','None'],'Intellectual disability','UPTET 2017',2017),
Q('primary','pedagogy','Which of the following is a "Social Learning Theory"?',['Skinner\'s','Pavlov\'s','Bandura\'s','Thorndike\'s'],'Bandura\'s','CTET 2019',2019),
Q('primary','pedagogy','Who gave the "Three-Dimensional Theory of Intelligence"?',['Spearman','Gardner','Guilford','Thurstone'],'Guilford','UPTET 2016',2016),
Q('primary','pedagogy','In a child-centered classroom, the teacher acts as a-',['Master','Facilitator','Observer','Evaluator'],'Facilitator','CTET 2021',2021),
Q('primary','pedagogy','The stage of "Initiative vs Guilt" occurs during-',['Infancy','Early Childhood','Middle Childhood','Adolescence'],'Early Childhood','CTET 2022',2022),
Q('primary','pedagogy','Which of the following is a secondary law of learning?',['Law of Readiness','Law of Analogy','Law of Exercise','Law of Effect'],'Law of Analogy','UPTET 2018',2018),
Q('primary','pedagogy','The "Case Study Method" was first used in psychology by-',['Freud','Watson','Tiedemann','None'],'Tiedemann','CTET 2020',2020),
Q('primary','pedagogy','According to Vygotsky, "Private Speech" is-',['Sign of madness','Tool for self-regulation','Distraction','None'],'Tool for self-regulation','CTET 2019',2019),
Q('primary','pedagogy','The "Unit Plan" was developed by-',['Morrison','Dewey','Kilpatrick','Froebel'],'Morrison','UPTET 2021',2021),
Q('primary','pedagogy','Which of the following is a type of "Creative Thinking"?',['Lateral thinking','Vertical thinking','Rote thinking','None'],'Lateral thinking','CTET 2022',2022),
Q('primary','pedagogy','The term "Praise" is an example of-',['Positive reinforcement','Negative reinforcement','Punishment','None'],'Positive reinforcement','CTET 2023',2023),
Q('primary','pedagogy','Who gave the "Law of Exercise"?',['Thorndike','Skinner','Pavlov','Watson'],'Thorndike','UPTET 2020',2020),
Q('primary','pedagogy','Which of the following is a "3D Aid"?',['Map','Chart','Model','Blackboard'],'Model','CTET 2017',2017),
Q('primary','pedagogy','The "Humanistic Approach" to learning is associated with-',['Skinner','Pavlov','Maslow','Thorndike'],'Maslow','CTET 2016',2016),
Q('primary','pedagogy','What is the focus of "Summative Assessment"?',['Learning process','Learning outcomes','Attendance','Discipline'],'Learning outcomes','UPTET 2019',2019),
Q('primary','pedagogy','Which of the following is an "External Reward"?',['Self-satisfaction','Money','Interest','Curiosity'],'Money','CTET 2015',2015),
Q('primary','pedagogy','The term "Maturation" is primarily a ___ process.',['Social','Biological','Emotional','Cognitive'],'Biological','CTET 2014',2014),
Q('primary','pedagogy','Which of the following is a characteristic of "Concrete Operational Stage"?',['Abstract reasoning','Reversibility','Object permanence','Animism'],'Reversibility','CTET 2013',2013),
Q('primary','pedagogy','The "National Curriculum Framework" (NCF) was last revised in-',['2000','2005','2010','2020'],'2005','CTET 2012',2012),
Q('primary','pedagogy','Who developed the "Multiple Intelligence Theory"?',['Spearman','Gardner','Binet','Stern'],'Gardner','CTET 2011',2011),
Q('primary','pedagogy','Which of the following is a "Principle of Individual Differences"?',['All children learn at the same pace','Each child is unique','Environment is the only factor','None'],'Each child is unique','UPTET 2012',2012),
Q('primary','pedagogy','The "Action Research" cycle is-',['Plan, Act, Observe, Reflect','Reflect, Plan, Act, Observe','Observe, Reflect, Plan, Act','None'],'Plan, Act, Observe, Reflect','UPTET 2011',2011),
Q('primary','pedagogy','Learning is most permanent when it is-',['By rote','By seeing','By doing','By listening'],'By doing','CTET 2023',2023),
Q('primary','pedagogy','The "Father of Behaviorism" is-',['Watson','Skinner','Pavlov','Thorndike'],'Watson','UPTET 2023',2023),
Q('primary','pedagogy','Which of the following is a "Barriers to Learning"?',['Motivation','High anxiety','Interest','Clear goals'],'High anxiety','CTET 2022',2022),
Q('primary','pedagogy','The "Activity Based Learning" (ABL) is suitable for-',['Primary classes','Higher secondary','Ph.D.','None'],'Primary classes','CTET 2021',2021),
Q('primary','pedagogy','Who gave the "Law of Readiness"?',['Thorndike','Skinner','Pavlov','None'],'Thorndike','UPTET 2022',2022),
Q('primary','pedagogy','Which of the following is a "Diagnostic Aid"?',['Remedial teaching','Standardized test','Oral test','None'],'Remedial teaching','CTET 2020',2020),
Q('primary','pedagogy','The "Concept of Scaffolding" was popularized by-',['Bruner','Piaget','Skinner','None'],'Bruner','UPTET 2021',2021),
Q('primary','pedagogy','Which of the following is a "Social Process" of development?',['Growth in weight','Learning language','Breathing','Walking'],'Learning language','CTET 2019',2019),
Q('primary','pedagogy','The "Resource Room" in schools is for-',['Special needs children','Gifted children','Teachers','None'],'Special needs children','UPTET 2020',2020),
Q('primary','pedagogy','Which of the following is a "Non-probability Sampling" method?',['Simple random','Systematic','Quota','Stratified'],'Quota','CTET 2018',2018),
Q('primary','pedagogy','The term "Schema" was used by-',['Piaget','Skinner','Pavlov','None'],'Piaget','UPTET 2017',2017),
Q('primary','pedagogy','Which of the following is a "Self-learning" method?',['Lecture','Programmed instruction','Group discussion','None'],'Programmed instruction','CTET 2017',2017),
Q('primary','pedagogy','The "Theory of Operant Conditioning" was tested on-',['Dogs','Rats and Pigeons','Chimpanzees','Cats'],'Rats and Pigeons','UPTET 2016',2016),
Q('primary','pedagogy','Which of the following is an "Open-ended Question"?',['What is your name?','How can we save water?','Is Earth round?','None'],'How can we save water?','CTET 2016',2016),
Q('primary','pedagogy','The "Secondary Agency of Socialization" for a child is-',['Family','School','Relatives','None'],'School','UPTET 2015',2015),
Q('primary','pedagogy','Which of the following is a "Psychological Motive"?',['Hunger','Sleep','Achievement','Thirst'],'Achievement','CTET 2015',2015),
Q('primary','pedagogy','The "Principle of Integration" means-',['Whole to parts','Parts to whole','Interaction of both','None'],'Interaction of both','UPTET 2014',2014),
Q('primary','pedagogy','Which of the following is a "Non-projected Visual Aid"?',['Maps','Filmstrips','Slide','None'],'Maps','CTET 2014',2014),
Q('primary','pedagogy','The "Inductive Method" goes from-',['General to specific','Specific to general','Simple to complex','None'],'Specific to general','UPTET 2013',2013),
Q('primary','pedagogy','Which of the following is a "Conative Activity"?',['Thinking','Feeling','Willing/Acting','Remembering'],'Willing/Acting','CTET 2013',2013),
Q('primary','pedagogy','The "Concept of Identification" refers to-',['Ignoring others','Becoming like someone one admires','Judging others','None'],'Becoming like someone one admires','UPTET 2012',2012),
Q('primary','pedagogy','Which of the following is a "Reinforcer"?',['Token','Food','Smile','All of these'],'All of these','CTET 2012',2012),
Q('primary','pedagogy','The "Laws of Learning" were formulated by-',['Thorndike','Pavlov','Skinner','None'],'Thorndike','UPTET 2011',2011),
Q('primary','pedagogy','Which of the following is an "Assessment for Learning"?',['Summative','Formative','Final exam','None'],'Formative','CTET 2011',2011),
Q('primary','pedagogy','The "Naturalism" philosophy in education emphasizes-',['Textbooks','Nature and environment','Society','Discipline'],'Nature and environment','UPTET 2023',2023),
Q('primary','pedagogy','Which of the following is a "Personality Inventory"?',['MMPI','I.Q. Test','Achievement Test','None'],'MMPI','CTET 2023',2023),
Q('primary','pedagogy','The "Concept of Child-centered Education" was given by-',['Rousseau','Piaget','Vygotsky','None'],'Rousseau','UPTET 2022',2022),
];
