const { v4: uuidv4 } = require('uuid');
const Q = (l,s,t,o,a,src,yr) => ({question_id:uuidv4(),level:l,subject:s,question_text:t,options:o,correct_answer:a,source:src,year:yr,language:'english',created_at:new Date()});

module.exports = [
Q('primary','evs','The animals that eat only plants are called-',['Herbivores','Carnivores','Omnivores','Decomposers'],'Herbivores','CTET 2011',2011),
Q('primary','evs','Which of the following is an example of an underwater plant?',['Rose','Lotus','Hydrilla','Tulip'],'Hydrilla','UPTET 2012',2012),
Q('primary','evs','The "Pashmina" wool is obtained from which animal?',['Sheep','Goat','Rabbit','Camel'],'Goat','CTET 2013',2013),
Q('primary','evs','Which of the following is a Kharif crop?',['Wheat','Rice','Mustard','Gram'],'Rice','UPTET 2014',2014),
Q('primary','evs','The process by which plants make their food is called-',['Respiration','Photosynthesis','Transpiration','Digestion'],'Photosynthesis','CTET 2015',2015),
Q('primary','evs','Which bird is known for its ability to mimic human speech?',['Parrot','Sparrow','Pigeon','Crow'],'Parrot','UPTET 2016',2016),
Q('primary','evs','The smallest state in India by area is-',['Sikkim','Goa','Tripura','Manipur'],'Goa','CTET 2017',2017),
Q('primary','evs','Which of the following is a non-renewable source of energy?',['Solar','Wind','Coal','Water'],'Coal','UPTET 2018',2018),
Q('primary','evs','The main source of Vitamin A is-',['Carrot','Milk','Egg','Apple'],'Carrot','CTET 2019',2019),
Q('primary','evs','Which of the following is a water-borne disease?',['Flu','Typhoid','Malaria','Asthma'],'Typhoid','UPTET 2020',2020),
Q('primary','evs','The highest peak in the world is-',['K2','Mount Everest','Kanchenjunga','Nanda Devi'],'Mount Everest','CTET 2021',2021),
Q('primary','evs','Which planet is known as the "Earth\'s Twin"?',['Venus','Mars','Jupiter','Saturn'],'Venus','UPTET 2021',2021),
Q('primary','evs','The process of filtering water is called-',['Purification','Distillation','Decantation','All of these'],'All of these','CTET 2022',2022),
Q('primary','evs','Which of the following is a natural fiber?',['Nylon','Rayon','Cotton','Polyester'],'Cotton','UPTET 2022',2022),
Q('primary','evs','The study of coins is called-',['Numismatics','Archaeology','Epigraphy','Philately'],'Numismatics','CTET 2023',2023),
Q('primary','evs','Which of the following is a source of Vitamin C?',['Milk','Orange','Bread','Egg'],'Orange','UPTET 2023',2023),
Q('primary','evs','The "Jim Corbett National Park" is located in-',['Madhya Pradesh','Uttarakhand','Gujarat','Rajasthan'],'Uttarakhand','CTET 2018',2018),
Q('primary','evs','Which of the following gas is used in a fire extinguisher?',['Oxygen','Nitrogen','Carbon Dioxide','Hydrogen'],'Carbon Dioxide','UPTET 2017',2017),
Q('primary','evs','The "Silent Valley" is located in which state?',['Kerala','Tamil Nadu','Karnataka','Assam'],'Kerala','CTET 2016',2016),
Q('primary','evs','Which of the following is a renewable source of energy?',['Coal','Petroleum','Wind','Natural Gas'],'Wind','UPTET 2015',2015),
Q('primary','evs','The main component of LPG is-',['Methane','Ethane','Propane and Butane','Nitrogen'],'Propane and Butane','CTET 2014',2014),
Q('primary','evs','Which of the following is a flightless bird?',['Ostrich','Peacock','Sparrow','Emu','Both A and D'],'Both A and D','UPTET 2013',2013),
Q('primary','evs','The deficiency of Iodine causes-',['Scurvy','Rickets','Goitre','Anaemia'],'Goitre','CTET 2012',2012),
Q('primary','evs','Which of the following is a cold-blooded animal?',['Lion','Snake','Human','Bird'],'Snake','UPTET 2012',2012),
Q('primary','evs','The Earth rotates on its axis from-',['East to West','West to East','North to South','South to North'],'West to East','CTET 2011',2011),
Q('primary','evs','Which of the following is an example of an ecosystem?',['A pond','A forest','An aquarium','All of these'],'All of these','UPTET 2011',2011),
Q('primary','evs','The "White Revolution" is related to-',['Cotton','Milk','Fish','Grain'],'Milk','CTET 2023',2023),
Q('primary','evs','Which of the following is a man-made fiber?',['Wool','Silk','Nylon','Cotton'],'Nylon','UPTET 2020',2020),
Q('primary','evs','The primary source of energy on Earth is-',['Moon','Sun','Stars','Fire'],'Sun','CTET 2022',2022),
Q('primary','evs','Which of the following is a biotic factor?',['Air','Water','Plants','Soil'],'Plants','UPTET 2019',2019),
Q('primary','evs','The process of boiling water kills-',['Bacteria','Viruses','Germs','All of these'],'All of these','CTET 2021',2021),
Q('primary','evs','Which of the following is a medicinal plant?',['Neem','Babul','Rose','Cactus'],'Neem','UPTET 2018',2018),
Q('primary','evs','The "Bhopal Gas Tragedy" occurred in which year?',['1980','1982','1984','1986'],'1984','CTET 2020',2020),
Q('primary','evs','Which of the following is a source of Vitamin D?',['Carrot','Orange','Sunlight','Spinach'],'Sunlight','UPTET 2017',2017),
Q('primary','evs','The "Ganga" river originates from-',['Yamunotri','Gangotri','Manasarovar','Rohtang Pass'],'Gangotri','CTET 2019',2019),
Q('primary','evs','Which of the following is a greenhouse gas?',['Oxygen','Nitrogen','Methane','Argon'],'Methane','UPTET 2016',2016),
Q('primary','evs','The "Chipko Movement" was started in which state?',['Uttar Pradesh (now Uttarakhand)','Madhya Pradesh','Rajasthan','Bihar'],'Uttar Pradesh (now Uttarakhand)','CTET 2018',2018),
Q('primary','evs','Which of the following is a vector of Malaria?',['Anopheles Mosquito','Aedes Mosquito','Housefly','Cockroach'],'Anopheles Mosquito','UPTET 2015',2015),
Q('primary','evs','The "Red Data Book" keeps records of-',['Endangered species','Rivers','Mountains','Forests'],'Endangered species','CTET 2017',2017),
Q('primary','evs','Which of the following is a fossil fuel?',['Wood','Coal','Bio-gas','Solar energy'],'Coal','UPTET 2014',2014),
Q('primary','evs','The "Ozone Layer" is found in-',['Troposphere','Stratosphere','Mesosphere','Thermosphere'],'Stratosphere','CTET 2016',2016),
Q('primary','evs','Which of the following is a bio-degradable waste?',['Paper','Plastic','Glass','Aluminum'],'Paper','UPTET 2013',2013),
Q('primary','evs','The study of flowers is called-',['Botany','Floriculture','Zoology','Geology'],'Floriculture','CTET 2015',2015),
Q('primary','evs','Which of the following is a source of Iron?',['Milk','Apple','Spinach','Both B and C'],'Both B and C','UPTET 2012',2012),
Q('primary','evs','The "Project Tiger" was launched in-',['1971','1973','1975','1980'],'1973','CTET 2014',2014),
Q('primary','evs','Which of the following is an omnivore?',['Lion','Deer','Human','Rabbit'],'Human','UPTET 2011',2011),
Q('primary','evs','The layer of the atmosphere where planes fly is-',['Troposphere','Stratosphere','Mesosphere','Thermosphere'],'Stratosphere','CTET 2013',2013),
Q('primary','evs','Which of the following is a component of air?',['Oxygen','Nitrogen','Carbon Dioxide','All of these'],'All of these','UPTET 2023',2023),
Q('primary','evs','The main source of water for plants is-',['Rain','Lakes','Rivers','Groundwater'],'Rain','CTET 2012',2012),
Q('primary','evs','How many colors are there in a rainbow?',['5','6','7','8'],'7','UPTET 2010',2010),
];
