const { v4: uuidv4 } = require('uuid');
const Q = (l,s,t,o,a,src,yr) => ({question_id:uuidv4(),level:l,subject:s,question_text:t,options:o,correct_answer:a,source:src,year:yr,language:'english',created_at:new Date()});

module.exports = [
Q('junior','social','The "Gautama Buddha" was born at-',['Lumbini','Sarnath','Bodh Gaya','Kushinagar'],'Lumbini','CTET 2011',2011),
Q('junior','social','Who was the first President of India?',['Dr. Rajendra Prasad','Dr. S. Radhakrishnan','Zakir Husain','V.V. Giri'],'Dr. Rajendra Prasad','UPTET 2012',2012),
Q('junior','social','The "Great Bath" was found in which site of Indus Valley?',['Harappa','Mohenjo-daro','Lothal','Kalibangan'],'Mohenjo-daro','CTET 2013',2013),
Q('junior','social','The "Simon Commission" visited India in-',['1927','1928','1930','1942'],'1928','UPTET 2014',2014),
Q('junior','social','Which article of the Indian Constitution deals with the "Right to Life"?',['Article 14','Article 19','Article 21','Article 32'],'Article 21','CTET 2015',2015),
Q('junior','social','The "Lok Sabha" is also known as-',['House of States','House of People','Council of Ministers','None'],'House of People','UPTET 2016',2016),
Q('junior','social','The "Sahara Desert" is located in which continent?',['Asia','Africa','North America','Australia'],'Africa','CTET 2017',2017),
Q('junior','social','Who was the architect of the Indian Constitution?',['Mahatma Gandhi','Jawaharlal Nehru','B.R. Ambedkar','Sardar Patel'],'B.R. Ambedkar','UPTET 2018',2018),
Q('junior','social','The "Non-Cooperation Movement" was suspended after the-',['Jallianwala Bagh massacre','Chauri Chaura incident','Dandi March','Quit India Movement'],'Chauri Chaura incident','CTET 2019',2019),
Q('junior','social','The "High Court" judges are appointed by-',['Chief Justice','Governor','President','Prime Minister'],'President','UPTET 2020',2020),
Q('junior','social','Which planet is closest to the Sun?',['Mercury','Venus','Earth','Mars'],'Mercury','CTET 2021',2021),
Q('junior','social','The "Second Battle of Panipat" was fought between-',['Babur and Ibrahim Lodi','Akbar and Hemu','Marathas and Ahmad Shah Abdali','None'],'Akbar and Hemu','UPTET 2021',2021),
Q('junior','social','Who founded the "Ramakrishna Mission"?',['Swami Dayananda','Swami Vivekananda','Raja Ram Mohan Roy','None'],'Swami Vivekananda','CTET 2022',2022),
Q('junior','social','The "First General Elections" in India were held in-',['1947','1950','1951-52','1955'],'1951-52','UPTET 2022',2022),
Q('junior','social','The "Prime Meridian" passes through-',['Paris','London (Greenwich)','New York','Delhi'],'London (Greenwich)','CTET 2023',2023),
Q('junior','social','Who was the first woman President of India?',['Indira Gandhi','Pratibha Patil','Sarojini Naidu','None'],'Pratibha Patil','UPTET 2023',2023),
Q('junior','social','The "Arya Samaj" was founded in-',['1875','1885','1895','1905'],'1875','CTET 2018',2018),
Q('junior','social','Which is the largest coffee-producing country in the world?',['India','Brazil','Vietnam','Colombia'],'Brazil','UPTET 2017',2017),
Q('junior','social','The "Fundamental Rights" are included in which part of the Constitution?',['Part II','Part III','Part IV','Part V'],'Part III','CTET 2016',2016),
Q('junior','social','The "Panchayati Raj" was given constitutional status by which amendment?',['42nd','44th','73rd','74th'],'73rd','UPTET 2015',2015),
Q('junior','social','Who was the first Viceroy of India?',['Lord Canning','Lord Dalhousie','Lord Mountbatten','Lord Curzon'],'Lord Canning','CTET 2014',2014),
Q('junior','social','Which city is known as the "Manchester of India"?',['Mumbai','Ahmedabad','Kanpur','Coimbatore'],'Ahmedabad','UPTET 2013',2013),
Q('junior','social','The "League of Nations" was established after-',['World War I','World War II','French Revolution','Russian Revolution'],'World War I','CTET 2012',2012),
Q('junior','social','The "National Emblem" of India was taken from-',['Sanchi Stupa','Sarnath Lion Capital','Ellora Caves','Ajanta Caves'],'Sarnath Lion Capital','UPTET 2012',2012),
Q('junior','social','Who was the last Mughal Emperor?',['Aurangzeb','Bahadur Shah Zafar','Shah Alam II','Akbar II'],'Bahadur Shah Zafar','CTET 2011',2011),
Q('junior','social','The "Rig Veda" contains how many hymns?',['1000','1028','1500','None'],'1028','UPTET 2011',2011),
Q('junior','social','The "National Anthem" was composed by-',['Bankim Chandra Chatterjee','Rabindranath Tagore','Sarojini Naidu','None'],'Rabindranath Tagore','CTET 2023',2023),
Q('junior','social','Which is the largest state of India in terms of area?',['Uttar Pradesh','Maharashtra','Rajasthan','Madhya Pradesh'],'Rajasthan','UPTET 2020',2020),
Q('junior','social','The "Vice-President" of India is the ex-officio Chairman of-',['Lok Sabha','Rajya Sabha','Planning Commission','None'],'Rajya Sabha','CTET 2022',2022),
Q('junior','social','Who was the first woman to become the Governor of an Indian state?',['Sucheta Kripalani','Sarojini Naidu','Indira Gandhi','None'],'Sarojini Naidu','UPTET 2019',2019),
Q('junior','social','The "Jallianwala Bagh massacre" took place in which city?',['Amritsar','Lahore','Delhi','Meerut'],'Amritsar','CTET 2021',2021),
Q('junior','social','The "Meenakshi Temple" is located at-',['Madurai','Thanjavur','Kanchipuram','Puri'],'Madurai','UPTET 2018',2018),
Q('junior','social','The "Blue Revolution" is related to-',['Milk','Agriculture','Fish','Oilseeds'],'Fish','CTET 2020',2020),
Q('junior','social','Who founded the "Brahmo Samaj"?',['Raja Ram Mohan Roy','Swami Dayananda','Swami Vivekananda','None'],'Raja Ram Mohan Roy','UPTET 2017',2017),
Q('junior','social','The "Maximum gap" between two sessions of Parliament can be-',['3 months','6 months','9 months','1 year'],'6 months','CTET 2019',2019),
Q('junior','social','Which is the largest island in the world?',['Greenland','New Guinea','Borneo','Madagascar'],'Greenland','CTET 2016',2016),
Q('junior','social','The "Battle of Buxar" was fought in-',['1757','1764','1857','1947'],'1764','UPTET 2022',2022),
Q('junior','social','The "Directive Principles of State Policy" were taken from which constitution?',['USA','UK','Ireland','Canada'],'Ireland','CTET 2015',2015),
Q('junior','social','Which river is known as the "Sorrow of Bihar"?',['Ganga','Yamuna','Kosi','Gandak'],'Kosi','UPTET 2021',2021),
Q('junior','social','The "Bhagavad Gita" is a part of which epic?',['Ramayana','Mahabharata','Vedas','Puranas'],'Mahabharata','CTET 2014',2014),
Q('junior','social','Who was the first Indian woman to reach Antarctica?',['Meher Moos','Bachendri Pal','Santosh Yadav','None'],'Meher Moos','UPTET 2014',2014),
Q('junior','social','The "Taj Mahal" was built by Shah Jahan in memory of-',['Mumtaz Mahal','Noor Jahan','Jodha Bai','None'],'Mumtaz Mahal','CTET 2013',2013),
Q('junior','social','Which is the deepest ocean in the world?',['Atlantic','Indian','Pacific','Arctic'],'Pacific','UPTET 2013',2013),
Q('junior','social','The "Gir National Park" is famous for-',['Tigers','Lions','Elephants','Rhinos'],'Lions','CTET 2012',2012),
Q('junior','social','The "Indian Constitution" is the ___ constitution in the world.',['Shortest','Longest written','Smallest','None'],'Longest written','UPTET 2012',2012),
Q('junior','social','The "Nobel Prize" was first awarded in-',['1901','1911','1921','1931'],'1901','CTET 2011',2011),
Q('junior','social','Which of the following is a Rabi crop?',['Rice','Maize','Wheat','Cotton'],'Wheat','UPTET 2023',2023),
Q('junior','social','The "Finance Commission" is appointed by-',['President','Prime Minister','Finance Minister','RBI Governor'],'President','CTET 2020',2020),
Q('junior','social','The "Yellow Revolution" is related to-',['Gold','Oilseeds','Egg','Pulses'],'Oilseeds','UPTET 2011',2011),
Q('junior','social','The "International Yoga Day" is celebrated on-',['21st June','5th June','22nd April','None'],'21st June','CTET 2022',2022),
];
