const { v4: uuidv4 } = require('uuid');
const Q = (l,s,t,o,a,src,yr) => ({question_id:uuidv4(),level:l,subject:s,question_text:t,options:o,correct_answer:a,source:src,year:yr,language:'english',created_at:new Date()});

module.exports = [
Q('junior','science','The chemical formula for Common Salt is-',['NaCl','KCl','CaCl2','MgCl2'],'NaCl','CTET 2011',2011),
Q('junior','science','Which of the following is a physical change?',['Souring of milk','Cutting of wood','Burning of coal','Digestion of food'],'Cutting of wood','UPTET 2012',2012),
Q('junior','science','The unit of force is-',['Joule','Watt','Newton','Pascal'],'Newton','CTET 2013',2013),
Q('junior','science','Which of the following is a source of roughage?',['Milk','Egg','Fruits and Vegetables','Sugar'],'Fruits and Vegetables','UPTET 2014',2014),
Q('junior','science','The process of transition from liquid to solid is called-',['Freezing','Melting','Evaporation','Condensation'],'Freezing','CTET 2015',2015),
Q('junior','science','Which of the following is a good conductor of electricity?',['Rubber','Glass','Copper','Plastic'],'Copper','UPTET 2016',2016),
Q('junior','science','The instrument used to measure the depth of the ocean is-',['Altimeter','Fathometer','Barometer','Hygrometer'],'Fathometer','CTET 2017',2017),
Q('junior','science','Which of the following is a neutral substance?',['Salt','Vinegar','Soap','Lemon juice'],'Salt','UPTET 2018',2018),
Q('junior','science','The unit of frequency is-',['Joule','Watt','Hertz','Newton'],'Hertz','CTET 2019',2019),
Q('junior','science','Which organ is responsible for pumping blood?',['Lungs','Liver','Kidney','Heart'],'Heart','UPTET 2020',2020),
Q('junior','science','The green pigment in leaves is called-',['Hemoglobin','Chlorophyll','Melanin','None'],'Chlorophyll','CTET 2021',2021),
Q('junior','science','Which of the following is a renewable resource?',['Coal','Petroleum','Wind energy','Natural gas'],'Wind energy','UPTET 2021',2021),
Q('junior','science','The largest bone in the human body is-',['Femur','Humerus','Stapes','Tibia'],'Femur','CTET 2022',2022),
Q('junior','science','Which of the following is used in making electric wires?',['Iron','Lead','Copper','Tin'],'Copper','UPTET 2022',2022),
Q('junior','science','The study of insects is called-',['Zoology','Botany','Entomology','Ecology'],'Entomology','CTET 2023',2023),
Q('junior','science','Which gas is released during photosynthesis?',['Oxygen','Carbon dioxide','Nitrogen','Hydrogen'],'Oxygen','UPTET 2023',2023),
Q('junior','science','Which of the following is a scalar quantity?',['Force','Velocity','Mass','Acceleration'],'Mass','CTET 2018',2018),
Q('junior','science','The normal temperature of a healthy human body in Celsius is-',['37°C','98.6°C','100°C','None'],'37°C','UPTET 2017',2017),
Q('junior','science','Which of the following is a gas at room temperature?',['Mercury','Oxygen','Iron','Copper'],'Oxygen','CTET 2016',2016),
Q('junior','science','The phenomenon of light bending as it passes from one medium to another is-',['Reflection','Refraction','Dispersion','Diffraction'],'Refraction','UPTET 2015',2015),
Q('junior','science','Which of the following is a synthetic fiber?',['Silk','Cotton','Nylon','Wool'],'Nylon','CTET 2014',2014),
Q('junior','science','The acid found in tamarind is-',['Acetic acid','Lactic acid','Tartaric acid','Citric acid'],'Tartaric acid','UPTET 2013',2013),
Q('junior','science','The largest planet in the solar system is-',['Earth','Venus','Jupiter','Saturn'],'Jupiter','CTET 2012',2012),
Q('junior','science','Which of the following is a vertebrate?',['Ant','Spider','Fish','Earthworm'],'Fish','UPTET 2012',2012),
Q('junior','science','The power house of the cell is-',['Nucleus','Ribosome','Mitochondria','Lysosome'],'Mitochondria','CTET 2011',2011),
Q('junior','science','Which of the following is an insulator?',['Copper','Silver','Aluminum','Rubber'],'Rubber','UPTET 2011',2011),
Q('junior','science','The instrument used to measure the intensity of an earthquake is-',['Seismograph','Barometer','Thermometer','Hygrometer'],'Seismograph','CTET 2023',2023),
Q('junior','science','Which of the following is a fat-soluble vitamin?',['Vitamin B','Vitamin C','Vitamin A','None'],'Vitamin A','UPTET 2020',2020),
Q('junior','science','The deficiency of Vitamin A causes-',['Scurvy','Night blindness','Rickets','Beriberi'],'Night blindness','CTET 2022',2022),
Q('junior','science','Which of the following is a carnivore?',['Deer','Rabbit','Wolf','Cow'],'Wolf','UPTET 2019',2019),
Q('junior','science','The atmospheric pressure is measured using a-',['Barometer','Thermometer','Anemometer','Hygrometer'],'Barometer','CTET 2021',2021),
Q('junior','science','Which of the following is a source of Vitamin C?',['Milk','Meat','Orange','Bread'],'Orange','UPTET 2018',2018),
Q('junior','science','The chemical symbol for Gold is-',['Ag','Au','Fe','Cu'],'Au','CTET 2020',2020),
Q('junior','science','Which of the following is a metal?',['Oxygen','Nitrogen','Aluminum','Sulfur'],'Aluminum','UPTET 2017',2017),
Q('junior','science','The acceleration due to gravity on Earth is approx-',['9.8 m/s²','1.6 m/s²','11.2 m/s²','None'],'9.8 m/s²','CTET 2019',2019),
Q('junior','science','Which of the following is the female reproductive part of a flower?',['Stamen','Pistil','Petal','Sepal'],'Pistil','CTET 2016',2016),
Q('junior','science','Which of the following is attracted to a magnet?',['Paper','Wood','Iron','Plastic'],'Iron','UPTET 2022',2022),
Q('junior','science','The pH scale ranges from-',['0 to 7','1 to 14','0 to 14','None'],'0 to 14','CTET 2015',2015),
Q('junior','science','Which of the following is a clean source of energy?',['Coal','Solar energy','Petroleum','Wood'],'Solar energy','UPTET 2021',2021),
Q('junior','science','The part of the eye where the image is formed is-',['Cornea','Iris','Retina','Lens'],'Retina','CTET 2014',2014),
Q('junior','science','Which of the following is a mixture?',['Water','Air','Gold','Oxygen'],'Air','UPTET 2014',2014),
Q('junior','science','The process of solid turning directly into gas is-',['Boiling','Melting','Sublimation','Condensation'],'Sublimation','CTET 2013',2013),
Q('junior','science','Which of the following is a primary consumer?',['Grasshopper','Lion','Fungi','Snake'],'Grasshopper','UPTET 2013',2013),
Q('junior','science','The chemical symbol for Sodium is-',['S','Na','So','Sn'],'Na','CTET 2012',2012),
Q('junior','science','Which of the following is a warm-blooded animal?',['Fish','Frog','Snake','Whale'],'Whale','UPTET 2012',2012),
Q('junior','science','The boiling point of water in Celsius is-',['0°C','50°C','100°C','None'],'100°C','CTET 2011',2011),
Q('junior','science','Which of the following is an example of a gas?',['Oxygen','Water','Iron','Wood'],'Oxygen','UPTET 2023',2023),
Q('junior','science','Which of the following is an abiotic component of environment?',['Plants','Animals','Bacteria','Water'],'Water','CTET 2020',2020),
Q('junior','science','The energy of position is called-',['Kinetic energy','Potential energy','Chemical energy','Thermal energy'],'Potential energy','UPTET 2011',2011),
Q('junior','science','Which of the following is a simple machine?',['Lever','Pulley','Inclined plane','All of these'],'All of these','CTET 2022',2022),
];
