const { v4: uuidv4 } = require('uuid');
const Q = (l,s,t,o,a,src,yr) => ({question_id:uuidv4(),level:l,subject:s,question_text:t,options:o,correct_answer:a,source:src,year:yr,language:'english',created_at:new Date()});

module.exports = [
Q('junior','social','The "Kushana Empire" reached its peak under-',['Kanishka','Vima Kadphises','Kujula Kadphises','None'],'Kanishka','CTET 2011',2011),
Q('junior','social','Who was the first woman President of the Indian National Congress?',['Sarojini Naidu','Annie Besant','Indira Gandhi','None'],'Annie Besant','UPTET 2012',2012),
Q('junior','social','The "Arthashastra" was written by-',['Chanakya','Megasthenes','Kalidasa','None'],'Chanakya','CTET 2013',2013),
Q('junior','social','The "Swaraj Party" was founded by-',['Motilal Nehru and C.R. Das','Mahatma Gandhi','Sardar Patel','None'],'Motilal Nehru and C.R. Das','UPTET 2014',2014),
Q('junior','social','Which article of the Indian Constitution deals with the "Abolition of Titles"?',['Article 14','Article 15','Article 17','Article 18'],'Article 18','CTET 2015',2015),
Q('junior','social','The "Governor" of a state is appointed by the-',['Chief Minister','President','Prime Minister','None'],'President','UPTET 2016',2016),
Q('junior','social','The "Gobi Desert" is located in-',['Africa','Asia','South America','Australia'],'Asia','CTET 2017',2017),
Q('junior','social','Who was the first Indian woman to win an Olympic medal?',['Karnam Malleswari','P.T. Usha','Mary Kom','None'],'Karnam Malleswari','UPTET 2018',2018),
Q('junior','social','The "Poona Pact" was signed between-',['Gandhi and Ambedkar','Gandhi and Jinnah','Nehru and Ambedkar','None'],'Gandhi and Ambedkar','CTET 2019',2019),
Q('junior','social','The "NITI Aayog" was established in-',['2012','2014','2015','2017'],'2015','UPTET 2020',2020),
Q('junior','social','Which planet is known as "Earth\'s Twin"?',['Venus','Mars','Jupiter','Saturn'],'Venus','CTET 2021',2021),
Q('junior','social','The "Battle of Plassey" was fought in-',['1757','1764','1857','None'],'1757','UPTET 2021',2021),
Q('junior','social','Who founded the "Self-Respect Movement"?',['E.V. Ramasamy (Periyar)','Jyotiba Phule','Ambedkar','None'],'E.V. Ramasamy (Periyar)','CTET 2022',2022),
Q('junior','social','The "Fundamental Rights" were inspired by which country\'s constitution?',['UK','USA','Canada','Ireland'],'USA','UPTET 2022',2022),
Q('junior','social','The "Arctic Circle" is located at-',['66.5° N','66.5° S','23.5° N','23.5° S'],'66.5° N','CTET 2023',2023),
Q('junior','social','Who was the first woman Chief Minister of an Indian state?',['Sucheta Kripalani','Sarojini Naidu','Indira Gandhi','None'],'Sucheta Kripalani','UPTET 2023',2023),
Q('junior','social','The "Home Rule League" was started by-',['Annie Besant and Tilak','Mahatma Gandhi','Nehru','None'],'Annie Besant and Tilak','CTET 2018',2018),
Q('junior','social','Which state is the largest producer of rice in India?',['Uttar Pradesh','West Bengal','Punjab','Andhra Pradesh'],'West Bengal','UPTET 2017',2017),
Q('junior','social','The "Right to Education" is a Fundamental Right under Article-',['19','21','21A','25'],'21A','CTET 2016',2016),
Q('junior','social','The "Minimum age" for becoming the President of India is-',['25 years','30 years','35 years','None'],'35 years','UPTET 2015',2015),
Q('junior','social','Who was the last Governor-General of independent India?',['Lord Mountbatten','C. Rajagopalachari','Jawaharlal Nehru','None'],'C. Rajagopalachari','CTET 2014',2014),
Q('junior','social','Which city is known as the "Pink City" of India?',['Jodhpur','Jaipur','Udaipur','None'],'Jaipur','UPTET 2013',2013),
Q('junior','social','The "UNESCO" is headquartered at-',['New York','Washington D.C.','Paris','Geneva'],'Paris','CTET 2012',2012),
Q('junior','social','The "Equator" does not pass through which continent?',['Africa','South America','Asia','Europe'],'Europe','UPTET 2012',2012),
Q('junior','social','Who was the first woman to win a Nobel Peace Prize?',['Mother Teresa','Malala Yousafzai','Jane Addams','None'],'Jane Addams','CTET 2011',2011),
Q('junior','social','The "Manusmriti" deals with-',['Music','Law','Rituals','None'],'Law','UPTET 2011',2011),
Q('junior','social','The "National Animal" of India is-',['Lion','Tiger','Elephant','Cow'],'Tiger','CTET 2023',2023),
Q('junior','social','Which is the largest coffee-producing state in India?',['Tamil Nadu','Kerala','Karnataka','Andhra Pradesh'],'Karnataka','UPTET 2020',2020),
Q('junior','social','The "Chief Justice of India" is appointed by-',['President','Prime Minister','Law Minister','None'],'President','CTET 2022',2022),
Q('junior','social','Who said "Swaraj is my birthright and I shall have it"?',['B.G. Tilak','Mahatma Gandhi','Subhash Chandra Bose','None'],'B.G. Tilak','UPTET 2019',2019),
Q('junior','social','The "Champaran Satyagraha" was related to which crop?',['Indigo','Cotton','Rice','None'],'Indigo','CTET 2021',2021),
Q('junior','social','The "Hampi" ruins are located in which state?',['Andhra Pradesh','Karnataka','Tamil Nadu','None'],'Karnataka','UPTET 2018',2018),
Q('junior','social','The "Pink Revolution" is related to-',['Onion and Prawn','Milk','Eggs','Horticulture'],'Onion and Prawn','CTET 2020',2020),
Q('junior','social','Who founded the "Azad Hind Fauj" (INA)?',['Subhash Chandra Bose','Rash Behari Bose','Mohan Singh','None'],'Rash Behari Bose (later led by Bose)','UPTET 2017',2017),
Q('junior','social','The "Maximum membership" of Rajya Sabha is-',['200','238','250','None'],'250','CTET 2019',2019),
Q('junior','social','Which is the highest waterfall in the world?',['Angel Falls','Niagara Falls','Victoria Falls','None'],'Angel Falls','CTET 2016',2016),
Q('junior','social','The "Kakori Train Robbery" took place in-',['1922','1925','1927','1930'],'1925','UPTET 2022',2022),
Q('junior','social','The "Concept of Fundamental Duties" was taken from-',['USA','UK','USSR (Russia)','Canada'],'USSR (Russia)','CTET 2015',2015),
Q('junior','social','Which river is known as the "Sorrow of Bengal"?',['Ganga','Yamuna','Damodar','Kosi'],'Damodar','UPTET 2021',2021),
Q('junior','social','The "Mahabharata" was written by-',['Valmiki','Ved Vyas','Tulsidas','None'],'Ved Vyas','CTET 2014',2014),
Q('junior','social','Who was the first woman to climb Mount Everest twice?',['Santosh Yadav','Bachendri Pal','Sunita Williams','None'],'Santosh Yadav','UPTET 2014',2014),
Q('junior','social','The "Gol Gumbaz" is located at-',['Bijapur','Hyderabad','Delhi','Agra'],'Bijapur','CTET 2013',2013),
Q('junior','social','Which is the largest lake in India?',['Wular Lake','Chilika Lake','Vembanad Lake','None'],'Chilika Lake (Brackish) / Wular (Fresh)','UPTET 2013',2013),
Q('junior','social','The "Kanha National Park" is famous for-',['Tigers','Lions','Elephants','Rhinos'],'Tigers','CTET 2012',2012),
Q('junior','social','The "Indian Constitution" was adopted on-',['15th Aug 1947','26th Nov 1949','26th Jan 1950','None'],'26th Nov 1949','UPTET 2012',2012),
Q('junior','social','The "Second World War" ended in-',['1918','1939','1945','1950'],'1945','CTET 2011',2011),
Q('junior','social','Which of the following is a Fiber crop?',['Wheat','Rice','Jute','Sugarcane'],'Jute','UPTET 2023',2023),
Q('junior','social','The "Chief Minister" of a state is appointed by-',['President','Governor','Prime Minister','None'],'Governor','CTET 2020',2020),
Q('junior','social','The "Black Revolution" is related to-',['Coal','Petroleum','Fish','None'],'Petroleum','UPTET 2011',2011),
Q('junior','social','The "International Day of Non-Violence" is celebrated on-',['30th Jan','2nd Oct','14th Nov','None'],'2nd Oct','CTET 2022',2022),
];
