const { v4: uuidv4 } = require('uuid');
const Q = (l,s,t,o,a,src,yr) => ({question_id:uuidv4(),level:l,subject:s,question_text:t,options:o,correct_answer:a,source:src,year:yr,language:'english',created_at:new Date()});

module.exports = [
Q('primary','pedagogy','According to Gardner, "Intrapersonal Intelligence" refers to-',['Understanding others','Understanding oneself','Logical reasoning','Musical ability'],'Understanding oneself','CTET 2018',2018),
Q('primary','pedagogy','The concept of "Mental Age" was introduced by-',['Binet','Stern','Terman','None'],'Binet','UPTET 2017',2017),
Q('primary','pedagogy','Which of the following is a "Cognitive Theory" of learning?',['Skinner\'s','Pavlov\'s','Piaget\'s','Thorndike\'s'],'Piaget\'s','CTET 2019',2019),
Q('primary','pedagogy','Who is known for the "Theory of Moral Development"?',['Piaget','Kohlberg','Erikson','Freud'],'Kohlberg','UPTET 2016',2016),
Q('primary','pedagogy','In an inclusive school, a teacher should-',['Focus only on gifted children','Treat all children equally regardless of their background','Segregate disabled children','Follow a rigid curriculum'],'Treat all children equally regardless of their background','CTET 2021',2021),
Q('primary','pedagogy','The stage of "Autonomy vs Shame and Doubt" occurs during-',['Infancy','Early Childhood','Middle Childhood','Adolescence'],'Early Childhood','CTET 2022',2022),
Q('primary','pedagogy','Which of the following is a primary law of learning according to Thorndike?',['Law of Readiness','Law of Intensity','Law of Frequency','None'],'Law of Readiness','UPTET 2018',2018),
Q('primary','pedagogy','The "Lecture Method" is best suited for-',['Primary classes','Higher classes','Special children','None'],'Higher classes','CTET 2020',2020),
Q('primary','pedagogy','According to Vygotsky, the "MKO" (More Knowledgeable Other) can be-',['A teacher','A peer','An adult','All of these'],'All of these','CTET 2019',2019),
Q('primary','pedagogy','The "Five Step System" of lesson planning was given by-',['Herbart','Dewey','Kilpatrick','Froebel'],'Herbart','UPTET 2021',2021),
Q('primary','pedagogy','Which of the following is a characteristic of "Convergent Thinking"?',['Multiple solutions','One correct solution','Creativity','Divergence'],'One correct solution','CTET 2022',2022),
Q('primary','pedagogy','The term "Scaffolding" in education means-',['Physical support','Temporary support to learners','A building structure','None'],'Temporary support to learners','CTET 2023',2023),
Q('primary','pedagogy','Who gave the "Law of Effect"?',['Pavlov','Skinner','Thorndike','Watson'],'Thorndike','UPTET 2020',2020),
Q('primary','pedagogy','Which of the following is an "Audio-Visual Aid"?',['Radio','Television','Blackboard','Charts'],'Television','CTET 2017',2017),
Q('primary','pedagogy','The "Behaviorist" view of learning focuses on-',['Internal mental processes','Observable behavior','Emotions','Social context'],'Observable behavior','CTET 2016',2016),
Q('primary','pedagogy','What is the purpose of "Continuous and Comprehensive Evaluation" (CCE)?',['To rank students','To identify learning gaps and fix them','To test memory','To compare schools'],'To identify learning gaps and fix them','UPTET 2019',2019),
Q('primary','pedagogy','Which of the following is a "Social Reward"?',['Praise','Money','Trophy','A grade'],'Praise','CTET 2015',2015),
Q('primary','pedagogy','The term "Nurture" in "Nature vs Nurture" refers to-',['Heredity','Environment','Biology','Genetics'],'Environment','CTET 2014',2014),
Q('primary','pedagogy','Which of the following is a characteristic of "Pre-operational Stage"?',['Logical reasoning','Ego-centrism','Abstract thinking','Conservation'],'Ego-centrism','CTET 2013',2013),
Q('primary','pedagogy','The "RTE Act" was implemented in India from-',['1st April 2009','1st April 2010','15th August 1947','None'],'1st April 2010','CTET 2012',2012),
Q('primary','pedagogy','Who developed the "Ecological Systems Theory"?',['Vygotsky','Bronfenbrenner','Piaget','Bandura'],'Bronfenbrenner','CTET 2011',2011),
Q('primary','pedagogy','Which of the following is a "Principle of Development"?',['Development is linear','Development is a continuous process','Development is same for all','None'],'Development is a continuous process','UPTET 2012',2012),
Q('primary','pedagogy','The "Discovery Method" of teaching is based on-',['Memorization','Activity and inquiry','Lecture','Dictation'],'Activity and inquiry','UPTET 2011',2011),
Q('primary','pedagogy','Learning by "Doing" is the philosophy of-',['Idealism','Pragmatism','Realism','Naturalism'],'Pragmatism','CTET 2023',2023),
Q('primary','pedagogy','The "Father of Educational Psychology" is-',['Thorndike','Pavlov','Skinner','Piaget'],'Thorndike','UPTET 2023',2023),
Q('primary','pedagogy','Which of the following is a type of "Non-verbal Communication"?',['Facial expressions','Writing','Speaking','Emailing'],'Facial expressions','CTET 2022',2022),
Q('primary','pedagogy','The "Montessori Method" focuses on-',['Teacher authority','Self-directed activity and hands-on learning','Strict discipline','Rote learning'],'Self-directed activity and hands-on learning','CTET 2021',2021),
Q('primary','pedagogy','Who is the founder of "Kindergarten"?',['Froebel','Dewey','Kilpatrick','None'],'Froebel','UPTET 2022',2022),
Q('primary','pedagogy','Which of the following is a "Standardized Test"?',['Teacher-made test','I.Q. Test','Class quiz','None'],'I.Q. Test','CTET 2020',2020),
Q('primary','pedagogy','The "Concept of ZPD" was introduced by-',['Piaget','Vygotsky','Bruner','None'],'Vygotsky','UPTET 2021',2021),
Q('primary','pedagogy','Which of the following is a "Physical Process" of development?',['Thinking','Growth in height','Making friends','Feeling happy'],'Growth in height','CTET 2019',2019),
Q('primary','pedagogy','The "Individualized Education Program" (IEP) is for-',['Special children','Gifted children','All children','None'],'Special children','UPTET 2020',2020),
Q('primary','pedagogy','Which of the following is a "Method of Qualitative Research"?',['Survey','Experiment','Case study','Correlation'],'Case study','CTET 2018',2018),
Q('primary','pedagogy','The term "Maturation" was used by-',['Gessel','Piaget','Erikson','None'],'Gessel','UPTET 2017',2017),
Q('primary','pedagogy','Which of the following is a "Collaborative Learning" technique?',['Group discussion','Individual reading','Silent writing','Listening to lecture'],'Group discussion','CTET 2017',2017),
Q('primary','pedagogy','The "Theory of Reinforcement" is associated with-',['Pavlov','Skinner','Watson','None'],'Skinner','UPTET 2016',2016),
Q('primary','pedagogy','Which of the following is a "Closed-ended Question"?',['How do you feel?','What is the capital of India?','Why do you like science?','None'],'What is the capital of India?','CTET 2016',2016),
Q('primary','pedagogy','The "Main Agency of Socialization" for a child is-',['Family','School','Media','All of these'],'All of these','UPTET 2015',2015),
Q('primary','pedagogy','Which of the following is a "Biological Motive"?',['Achievement','Thirst','Affiliation','Power'],'Thirst','CTET 2015',2015),
Q('primary','pedagogy','The "Principle of Continuity" means-',['Development stops at adulthood','Development is a lifelong process','Development is random','None'],'Development is a lifelong process','UPTET 2014',2014),
Q('primary','pedagogy','Which of the following is a "Projected Aid"?',['Overhead projector','Blackboard','Globe','Maps'],'Overhead projector','CTET 2014',2014),
Q('primary','pedagogy','The "Unit Method" of teaching was given by-',['Morrison','Dewey','Froebel','None'],'Morrison','UPTET 2013',2013),
Q('primary','pedagogy','Which of the following is a "Cognitive Activity"?',['Running','Singing','Problem solving','Breathing'],'Problem solving','CTET 2013',2013),
Q('primary','pedagogy','The "Concept of Sympathy" means-',['Feeling exactly like others','Feeling for others in distress','Ignoring others','Judging others'],'Feeling for others in distress','UPTET 2012',2012),
Q('primary','pedagogy','Which of the following is a "Type of Reinforcement"?',['Positive','Negative','Punishment','Both A and B'],'Both A and B','CTET 2012',2012),
Q('primary','pedagogy','The "Hierarchy of Learning" was given by-',['Gagne','Piaget','Bruner','None'],'Gagne','UPTET 2011',2011),
Q('primary','pedagogy','Which of the following is a "Form of Evaluation"?',['Summative','Formative','Diagnostic','All of these'],'All of these','CTET 2011',2011),
Q('primary','pedagogy','The "Realism" philosophy in education emphasizes-',['Ideas','Physical world and facts','Emotions','Values'],'Physical world and facts','UPTET 2023',2023),
Q('primary','pedagogy','Which of the following is a "Creativity Test"?',['Torrance Test','I.Q. Test','Achievement Test','None'],'Torrance Test','CTET 2023',2023),
Q('primary','pedagogy','The "Concept of Life-long Learning" was popularized by-',['UNESCO','World Bank','NEP 2020','None'],'UNESCO','UPTET 2022',2022),
];
