const { v4: uuidv4 } = require('uuid');
const Q = (l,s,t,o,a,src,yr) => ({question_id:uuidv4(),level:l,subject:s,question_text:t,options:o,correct_answer:a,source:src,year:yr,language:'english',created_at:new Date()});

module.exports = [
Q('junior','social','The "Pala Dynasty" was founded by-',['Gopala','Dharmapala','Devapala','None'],'Gopala','CTET 2011',2011),
Q('junior','social','Who was the first woman to be the President of the UN General Assembly?',['Vijaya Lakshmi Pandit','Sarojini Naidu','Indira Gandhi','None'],'Vijaya Lakshmi Pandit','UPTET 2012',2012),
Q('junior','social','The "Indica" was written by-',['Chanakya','Megasthenes','Kalidasa','None'],'Megasthenes','CTET 2013',2013),
Q('junior','social','The "Ghadar Party" was founded in-',['USA','India','UK','Germany'],'USA','UPTET 2014',2014),
Q('junior','social','Which article of the Indian Constitution deals with the "Protection of Interests of Minorities"?',['Article 29','Article 30','Article 32','Article 44'],'Article 29','CTET 2015',2015),
Q('junior','social','The "Vice-President" of India is elected by-',['Lok Sabha','Rajya Sabha','Both Houses of Parliament','None'],'Both Houses of Parliament','UPTET 2016',2016),
Q('junior','social','The "Atacama Desert" is located in-',['Africa','South America','Asia','Australia'],'South America','CTET 2017',2017),
Q('junior','social','Who was the first Indian woman to win a Nobel Prize?',['Mother Teresa','Sarojini Naidu','Indira Gandhi','None'],'Mother Teresa','UPTET 2018',2018),
Q('junior','social','The "Lucknow Pact" was signed in-',['1915','1916','1919','1921'],'1916','CTET 2019',2019),
Q('junior','social','The "Finance Commission" is constituted every ___ years.',['3','5','6','10'],'5','UPTET 2020',2020),
Q('junior','social','Which planet is known as the "Hottest Planet"?',['Mercury','Venus','Jupiter','Saturn'],'Venus','CTET 2021',2021),
Q('junior','social','The "Third Battle of Panipat" was fought in-',['1526','1556','1761','1857'],'1761','UPTET 2021',2021),
Q('junior','social','Who founded the "Satya Shodhak Samaj"?',['Jyotiba Phule','Ambedkar','Gandhi','None'],'Jyotiba Phule','CTET 2022',2022),
Q('junior','social','The "Directive Principles" were inspired by which country\'s constitution?',['USA','Ireland','Canada','UK'],'Ireland','UPTET 2022',2022),
Q('junior','social','The "Antarctic Circle" is located at-',['66.5° N','66.5° S','23.5° N','23.5° S'],'66.5° S','CTET 2023',2023),
Q('junior','social','Who was the first woman Speaker of Lok Sabha?',['Meira Kumar','Sushma Swaraj','Sumitra Mahajan','None'],'Meira Kumar','UPTET 2023',2023),
Q('junior','social','The "Quit India Movement" started in which year?',['1940','1942','1945','1947'],'1942','CTET 2018',2018),
Q('junior','social','Which state is the largest producer of tea in India?',['Assam','West Bengal','Kerala','Tamil Nadu'],'Assam','UPTET 2017',2017),
Q('junior','social','The "Right against Exploitation" is covered under Articles-',['14-18','19-22','23-24','25-28'],'23-24','CTET 2016',2016),
Q('junior','social','The "Maximum age" for a Supreme Court judge is-',['60 years','62 years','65 years','70 years'],'65 years','UPTET 2015',2015),
Q('junior','social','Who was the first Governor-General of India?',['Warren Hastings','Lord William Bentinck','Lord Canning','None'],'Lord William Bentinck','CTET 2014',2014),
Q('junior','social','Which state is known as the "Land of Five Rivers"?',['Punjab','Haryana','Uttar Pradesh','None'],'Punjab','UPTET 2013',2013),
Q('junior','social','The "WHO" is headquartered at-',['New York','Washington D.C.','Geneva','Paris'],'Geneva','CTET 2012',2012),
Q('junior','social','The "Standard Meridian" of India is-',['82° 30\' E','80° E','85° E','None'],'82° 30\' E','UPTET 2012',2012),
Q('junior','social','Who was the first Indian to win an Oscar?',['Bhanu Athaiya','Satyajit Ray','A.R. Rahman','None'],'Bhanu Athaiya','CTET 2011',2011),
Q('junior','social','The "Puranas" are how many in number?',['10','18','108','None'],'18','UPTET 2011',2011),
Q('junior','social','The "National Fruit" of India is-',['Apple','Mango','Banana','Orange'],'Mango','CTET 2023',2023),
Q('junior','social','Which is the largest cotton-producing state in India?',['Maharashtra','Gujarat','Punjab','None'],'Gujarat','UPTET 2020',2020),
Q('junior','social','The "Governor-General of India" title was created by which act?',['Charter Act 1833','Regulating Act 1773','Pitts India Act','None'],'Charter Act 1833','CTET 2022',2022),
Q('junior','social','Who gave the slogan "Jai Hind"?',['Subhash Chandra Bose','Mahatma Gandhi','Bhagat Singh','None'],'Subhash Chandra Bose','UPTET 2019',2019),
Q('junior','social','The "Jallianwala Bagh massacre" happened during the viceroyalty of-',['Lord Chelmsford','Lord Irwin','Lord Curzon','None'],'Lord Chelmsford','CTET 2021',2021),
Q('junior','social','The "Khajuraho" temples were built in which state?',['Uttar Pradesh','Madhya Pradesh','Rajasthan','None'],'Madhya Pradesh','UPTET 2018',2018),
Q('junior','social','The "Round Revolution" is related to-',['Potato','Tomato','Milk','Egg'],'Potato','CTET 2020',2020),
Q('junior','social','Who founded the "Indian National Congress" (INC)?',['A.O. Hume','Dadabhai Naoroji','W.C. Bonnerjee','None'],'A.O. Hume','UPTET 2017',2017),
Q('junior','social','The "Quorum" of Lok Sabha is-',['1/5','1/10','1/20','None'],'1/10','CTET 2019',2019),
Q('junior','social','Which is the largest ocean by area?',['Atlantic','Pacific','Indian','Arctic'],'Pacific','CTET 2016',2016),
Q('junior','social','The "Simon Commission" was appointed in-',['1925','1927','1928','1930'],'1927','UPTET 2022',2022),
Q('junior','social','The "Concept of Rule of Law" was taken from-',['USA','UK','France','None'],'UK','CTET 2015',2015),
Q('junior','social','Which river is known as the "Lifeline of Kerala"?',['Periyar','Bharatapuzha','Pamba','None'],'Periyar','UPTET 2021',2021),
Q('junior','social','The "Ramcharitmanas" was written by-',['Valmiki','Ved Vyas','Tulsidas','None'],'Tulsidas','CTET 2014',2014),
Q('junior','social','Who was the first Indian to win a Nobel Prize in Physics?',['C.V. Raman','H.J. Bhabha','S. Chandrasekhar','None'],'C.V. Raman','UPTET 2014',2014),
Q('junior','social','The "Sun Temple" of Konark is in which state?',['Odisha','Tamil Nadu','Karnataka','None'],'Odisha','CTET 2013',2013),
Q('junior','social','Which is the smallest continent by area?',['Europe','Australia','Antarctica','None'],'Australia','UPTET 2013',2013),
Q('junior','social','The "Kaziranga" National Park is in which state?',['Assam','Manipur','Sikkim','None'],'Assam','CTET 2012',2012),
Q('junior','social','The "Fundamental Rights" are in which Part of the Constitution?',['Part II','Part III','Part IV','None'],'Part III','UPTET 2012',2012),
Q('junior','social','The "Russian Revolution" took place in-',['1905','1917','1921','1939'],'1917','CTET 2011',2011),
Q('junior','social','Which of the following is a Plantation crop?',['Wheat','Rice','Rubber','Maize'],'Rubber','UPTET 2023',2023),
Q('junior','social','The "Chief of Army Staff" is appointed by-',['President','Prime Minister','Defence Minister','None'],'President','CTET 2020',2020),
Q('junior','social','The "Grey Revolution" is related to-',['Fertilizers','Milk','Fish','None'],'Fertilizers','UPTET 2011',2011),
Q('junior','social','The "International Day of Yoga" is celebrated on-',['21st June','5th June','22nd April','None'],'21st June','CTET 2022',2022),
];
