const { v4: uuidv4 } = require('uuid');
const Q = (l,s,t,o,a,src,yr) => ({question_id:uuidv4(),level:l,subject:s,question_text:t,options:o,correct_answer:a,source:src,year:yr,language:'english',created_at:new Date()});

module.exports = [
Q('junior','social','The "Gupta Dynasty" was founded by-',['Chandragupta I','Sri Gupta','Samudragupta','None'],'Sri Gupta','CTET 2011',2011),
Q('junior','social','Who was the first Governor-General of independent India?',['Lord Mountbatten','C. Rajagopalachari','Jawaharlal Nehru','None'],'Lord Mountbatten','UPTET 2012',2012),
Q('junior','social','The "Yajur Veda" deals with-',['Hymns','Rituals','Music','Magic'],'Rituals','CTET 2013',2013),
Q('junior','social','The "Khilafat Movement" was started to support-',['Turkish Caliph','Indian Independence','Peasants','None'],'Turkish Caliph','UPTET 2014',2014),
Q('junior','social','Which article of the Indian Constitution prohibits "Untouchability"?',['Article 14','Article 15','Article 17','Article 18'],'Article 17','CTET 2015',2015),
Q('junior','social','The "President" of India can nominate how many members to Rajya Sabha?',['2','10','12','15'],'12','UPTET 2016',2016),
Q('junior','social','The "Sahara Desert" is the ___ hot desert in the world.',['Largest','Smallest','Oldest','None'],'Largest','CTET 2017',2017),
Q('junior','social','Who was the first woman to reach space from India?',['Kalpana Chawla','Sunita Williams','Sarojini Naidu','None'],'Kalpana Chawla','UPTET 2018',2018),
Q('junior','social','The "Rowlatt Act" was passed in-',['1915','1919','1921','1930'],'1919','CTET 2019',2019),
Q('junior','social','The "Planning Commission" was replaced by-',['Finance Commission','NITI Aayog','Zonal Council','None'],'NITI Aayog','UPTET 2020',2020),
Q('junior','social','Which is the largest planet in the solar system?',['Mercury','Venus','Jupiter','Saturn'],'Jupiter','CTET 2021',2021),
Q('junior','social','The "First Battle of Tarain" was fought in-',['1191','1192','1526','1556'],'1191','UPTET 2021',2021),
Q('junior','social','Who founded the "Servants of India Society"?',['Gopal Krishna Gokhale','Mahatma Gandhi','B.G. Tilak','None'],'Gopal Krishna Gokhale','CTET 2022',2022),
Q('junior','social','The "Right to Property" was removed from Fundamental Rights by-',['42nd Amendment','44th Amendment','73rd Amendment','None'],'44th Amendment','UPTET 2022',2022),
Q('junior','social','The "Tropic of Capricorn" is located at-',['23.5° N','23.5° S','66.5° N','66.5° S'],'23.5° S','CTET 2023',2023),
Q('junior','social','Who was the first Law Minister of India?',['B.R. Ambedkar','Jawaharlal Nehru','Sardar Patel','None'],'B.R. Ambedkar','UPTET 2023',2023),
Q('junior','social','The "Theosophical Society" was founded by-',['Annie Besant','Madame Blavatsky and Col. Olcott','Raja Ram Mohan Roy','None'],'Madame Blavatsky and Col. Olcott','CTET 2018',2018),
Q('junior','social','Which is the largest wheat-producing state in India?',['Punjab','Haryana','Uttar Pradesh','Madhya Pradesh'],'Uttar Pradesh','UPTET 2017',2017),
Q('junior','social','The "Fundamental Rights" can be suspended during-',['Election','Financial crisis','National Emergency','None'],'National Emergency','CTET 2016',2016),
Q('junior','social','The "Panchayati Raj" was first introduced in which state?',['Rajasthan','Andhra Pradesh','Gujarat','Bihar'],'Rajasthan','UPTET 2015',2015),
Q('junior','social','Who was the first Governor-General of Bengal?',['Warren Hastings','Lord Cornwallis','Lord Wellesley','None'],'Warren Hastings','CTET 2014',2014),
Q('junior','social','Which river is known as the "Dakshin Ganga"?',['Krishna','Godavari','Cauvery','None'],'Godavari','UPTET 2013',2013),
Q('junior','social','The "World Bank" is headquartered at-',['New York','Washington D.C.','Geneva','Paris'],'Washington D.C.','CTET 2012',2012),
Q('junior','social','The "Standard Meridian" of India passes through-',['Delhi','Mumbai','Mirzapur (UP)','Chennai'],'Mirzapur (UP)','UPTET 2012',2012),
Q('junior','social','Who was the political guru of Mahatma Gandhi?',['G.K. Gokhale','Dadabhai Naoroji','B.G. Tilak','None'],'G.K. Gokhale','CTET 2011',2011),
Q('junior','social','The "Atharva Veda" is related to-',['Hymns','Music','Rituals','Magic and Medicine'],'Magic and Medicine','UPTET 2011',2011),
Q('junior','social','The "National Flower" of India is-',['Rose','Lotus','Lily','Sunflower'],'Lotus','CTET 2023',2023),
Q('junior','social','Which is the longest river in the world?',['Amazon','Nile','Mississippi','Yangtze'],'Nile','UPTET 2020',2020),
Q('junior','social','The "Chief Election Commissioner" is appointed by-',['President','Prime Minister','Parliament','None'],'President','CTET 2022',2022),
Q('junior','social','Who gave the slogan "Inquilab Zindabad"?',['Bhagat Singh','Subhash Chandra Bose','Mahatma Gandhi','None'],'Bhagat Singh','UPTET 2019',2019),
Q('junior','social','The "Dandi March" started from-',['Sabarmati Ashram','Dandi','Ahmedabad','None'],'Sabarmati Ashram','CTET 2021',2021),
Q('junior','social','The "Kailash Temple" at Ellora was built by-',['Rashtrakutas','Cholas','Pallavas','None'],'Rashtrakutas','UPTET 2018',2018),
Q('junior','social','The "Golden Revolution" is related to-',['Gold','Honey and Horticulture','Grain','Milk'],'Honey and Horticulture','CTET 2020',2020),
Q('junior','social','Who founded the "Wahabi Movement" in India?',['Sayyid Ahmad of Rae Bareli','Sir Sayyid Ahmad Khan','Shah Waliullah','None'],'Sayyid Ahmad of Rae Bareli','UPTET 2017',2017),
Q('junior','social','The "Maximum membership" of Lok Sabha is-',['500','545','552','None'],'552','CTET 2019',2019),
Q('junior','social','Which is the largest desert in Asia?',['Gobi','Thar','Sahara','Atacama'],'Gobi','CTET 2016',2016),
Q('junior','social','The "Chauri Chaura incident" took place in-',['1919','1921','1922','1930'],'1922','UPTET 2022',2022),
Q('junior','social','The "Concept of Welfare State" is mentioned in-',['Fundamental Rights','Directive Principles','Preamble','None'],'Directive Principles','CTET 2015',2015),
Q('junior','social','Which river is known as the "Tsangpo" in Tibet?',['Ganga','Yamuna','Brahmaputra','Indus'],'Brahmaputra','UPTET 2021',2021),
Q('junior','social','The "Ramayana" was written by-',['Valmiki','Ved Vyas','Tulsidas','None'],'Valmiki','CTET 2014',2014),
Q('junior','social','Who was the first woman to climb Mount Everest?',['Junko Tabei','Bachendri Pal','Santosh Yadav','None'],'Junko Tabei','UPTET 2014',2014),
Q('junior','social','The "Fatehpur Sikri" was built by-',['Akbar','Shah Jahan','Humayun','None'],'Akbar','CTET 2013',2013),
Q('junior','social','Which is the saltier ocean in the world?',['Atlantic','Indian','Pacific','Arctic'],'Atlantic','UPTET 2013',2013),
Q('junior','social','The "Bandipur National Park" is located in-',['Karnataka','Kerala','Tamil Nadu','None'],'Karnataka','CTET 2012',2012),
Q('junior','social','The "National Song" of India was taken from-',['Anandamath','Gitanjali','Bharat Bharti','None'],'Anandamath','UPTET 2012',2012),
Q('junior','social','The "French Revolution" took place in-',['1776','1789','1799','1804'],'1789','CTET 2011',2011),
Q('junior','social','Which of the following is a Cash crop?',['Wheat','Rice','Sugarcane','Maize'],'Sugarcane','UPTET 2023',2023),
Q('junior','social','The "Attorney General of India" is appointed by-',['President','Chief Justice','Prime Minister','None'],'President','CTET 2020',2020),
Q('junior','social','The "Red Revolution" is related to-',['Meat and Tomato','Milk','Egg','None'],'Meat and Tomato','UPTET 2011',2011),
Q('junior','social','The "International Labour Day" is celebrated on-',['1st May','5th June','1st Dec','None'],'1st May','CTET 2022',2022),
];
