const { v4: uuidv4 } = require('uuid');
const Q = (l,s,t,o,a,src,yr) => ({question_id:uuidv4(),level:l,subject:s,question_text:t,options:o,correct_answer:a,source:src,year:yr,language:'english',created_at:new Date()});

module.exports = [
Q('primary','evs','The animals that give birth to young ones are called-',['Mammals','Reptiles','Birds','Amphibians'],'Mammals','CTET 2011',2011),
Q('primary','evs','Which of the following is an example of a climber?',['Money plant','Rose','Tulip','Grass'],'Money plant','UPTET 2012',2012),
Q('primary','evs','The "Cotton" is obtained from which part of the plant?',['Seed','Root','Stem','Flower'],'Seed','CTET 2013',2013),
Q('primary','evs','Which of the following is a Kharif crop?',['Wheat','Rice','Mustard','Gram'],'Rice','UPTET 2014',2014),
Q('primary','evs','The gas used by plants during respiration is-',['Oxygen','Nitrogen','Carbon Dioxide','Argon'],'Oxygen','CTET 2015',2015),
Q('primary','evs','Which bird is known for its beautiful dance during rain?',['Peacock','Sparrow','Pigeon','Crow'],'Peacock','UPTET 2016',2016),
Q('primary','evs','The largest state in India by population is-',['Uttar Pradesh','Maharashtra','Bihar','West Bengal'],'Uttar Pradesh','CTET 2017',2017),
Q('primary','evs','Which of the following is a non-renewable resource?',['Solar','Wind','Coal','Water'],'Coal','UPTET 2018',2018),
Q('primary','evs','The main source of Vitamin B12 is-',['Milk and Meat','Orange','Apple','Rice'],'Milk and Meat','CTET 2019',2019),
Q('primary','evs','Which of the following is a contagious disease?',['Flu','Diabetes','Cancer','Asthma'],'Flu','UPTET 2020',2020),
Q('primary','evs','The highest mountain range in the world is-',['Andes','Alps','Himalayas','Rockies'],'Himalayas','CTET 2021',2021),
Q('primary','evs','Which planet is known as the "Red Planet"?',['Mars','Venus','Jupiter','Saturn'],'Mars','UPTET 2021',2021),
Q('primary','evs','The process of transition from gas to liquid is-',['Condensation','Evaporation','Freezing','None'],'Condensation','CTET 2022',2022),
Q('primary','evs','Which of the following is a natural fiber obtained from animals?',['Wool','Cotton','Jute','Nylon'],'Wool','UPTET 2022',2022),
Q('primary','evs','The study of outer space is called-',['Geography','Astronomy','Biology','Physics'],'Astronomy','CTET 2023',2023),
Q('primary','evs','Which of the following is a rich source of Vitamin D?',['Egg and Sunlight','Orange','Rice','Bread'],'Egg and Sunlight','UPTET 2023',2023),
Q('primary','evs','The "Kanha National Park" is located in-',['Madhya Pradesh','Uttarakhand','Gujarat','Rajasthan'],'Madhya Pradesh','CTET 2018',2018),
Q('primary','evs','Which of the following gas is used in a fire extinguisher?',['Oxygen','Nitrogen','Carbon Dioxide','Hydrogen'],'Carbon Dioxide','UPTET 2017',2017),
Q('primary','evs','The "Sundarbans" are located in which state?',['West Bengal','Odisha','Andhra Pradesh','Tamil Nadu'],'West Bengal','CTET 2016',2016),
Q('primary','evs','Which of the following is a renewable source of energy?',['Coal','Petroleum','Solar','Natural Gas'],'Solar','UPTET 2015',2015),
Q('primary','evs','The percentage of Nitrogen in the atmosphere is approx-',['21%','78%','1%','0.03%'],'78%','CTET 2014',2014),
Q('primary','evs','Which of the following is an aquatic mammal?',['Fish','Whale','Shark','Octopus'],'Whale','UPTET 2013',2013),
Q('primary','evs','The deficiency of Vitamin K causes-',['Scurvy','Rickets','Excessive bleeding from wounds','Night blindness'],'Excessive bleeding from wounds','CTET 2012',2012),
Q('primary','evs','Which of the following is a cold-blooded animal?',['Human','Dog','Snake','Cat'],'Snake','UPTET 2012',2012),
Q('primary','evs','The "World Environment Day" is celebrated on-',['5th June','22nd April','16th Sept','1st Dec'],'5th June','CTET 2011',2011),
Q('primary','evs','Which of the following is a pond ecosystem component?',['Water','Fish','Algae','All of these'],'All of these','UPTET 2011',2011),
Q('primary','evs','The "Yellow Revolution" is related to-',['Milk','Oilseeds','Fish','Cotton'],'Oilseeds','CTET 2023',2023),
Q('primary','evs','Which of the following is a man-made fiber?',['Wool','Silk','Nylon','Cotton'],'Nylon','UPTET 2020',2020),
Q('primary','evs','The main source of Vitamin E is-',['Vegetable oils','Orange','Rice','Potato'],'Vegetable oils','CTET 2022',2022),
Q('primary','evs','Which of the following is an abiotic component?',['Plants','Animals','Water','Fungi'],'Water','UPTET 2019',2019),
Q('primary','evs','The process of water cycle includes-',['Evaporation','Condensation','Precipitation','All of these'],'All of these','CTET 2021',2021),
Q('primary','evs','Which of the following is used to treat dehydration?',['ORS','Aspirin','Antibiotics','None'],'ORS','UPTET 2018',2018),
Q('primary','evs','The "Bhopal Gas Tragedy" was caused by-',['Methyl Isocyanate','Carbon Monoxide','Methane','None'],'Methyl Isocyanate','CTET 2020',2020),
Q('primary','evs','Which of the following is a source of Vitamin A?',['Carrot','Milk','Egg','All of these'],'All of these','UPTET 2017',2017),
Q('primary','evs','The "Godavari" river originates from-',['Gangotri','Trimbakeshwar','Rohtang','None'],'Trimbakeshwar','CTET 2019',2019),
Q('primary','evs','Which of the following is a greenhouse gas?',['Oxygen','Nitrogen','Methane','Argon'],'Methane','UPTET 2016',2016),
Q('primary','evs','The "Silent Valley" is located in-',['Kerala','Karnataka','Tamil Nadu','Goa'],'Kerala','CTET 2018',2018),
Q('primary','evs','Which of the following is a vector of Chikungunya?',['Anopheles Mosquito','Aedes Mosquito','Housefly','Cockroach'],'Aedes Mosquito','UPTET 2015',2015),
Q('primary','evs','The "World Water Day" is celebrated on-',['22nd March','5th June','22nd April','None'],'22nd March','CTET 2017',2017),
Q('primary','evs','Which of the following is a fossil fuel?',['Coal','Wood','Sunlight','Wind'],'Coal','UPTET 2014',2014),
Q('primary','evs','The "Exosphere" is the ___ layer of atmosphere.',['Lowest','Middle','Highest','None'],'Highest','CTET 2016',2016),
Q('primary','evs','Which of the following is a biodegradable material?',['Plastic','Food waste','Glass','Metal'],'Food waste','UPTET 2013',2013),
Q('primary','evs','The study of plants is called-',['Botany','Zoology','Geology','None'],'Botany','CTET 2015',2015),
Q('primary','evs','Which of the following is a source of Vitamin C?',['Lemon','Amla','Orange','All of these'],'All of these','UPTET 2012',2012),
Q('primary','evs','The "Project Elephant" was launched in-',['1973','1992','2005','None'],'1992','CTET 2014',2014),
Q('primary','evs','Which of the following is a primary consumer?',['Lion','Rabbit','Snake','Eagle'],'Rabbit','UPTET 2011',2011),
Q('primary','evs','The layer of the atmosphere where satellites orbit is-',['Exosphere','Troposphere','Stratosphere','None'],'Exosphere','CTET 2013',2013),
Q('primary','evs','Which of the following is a pollutant?',['Oxygen','Nitrogen','Sulfur Dioxide','Argon'],'Sulfur Dioxide','UPTET 2023',2023),
Q('primary','evs','The main source of heat for Earth is-',['Moon','Sun','Stars','Lamp'],'Sun','CTET 2012',2012),
Q('primary','evs','How many colors are there in a rainbow?',['5','6','7','8'],'7','UPTET 2010',2010),
];
